import { Permission, UserRole } from '@shared/models';

const ALL_PERMISSIONS: Permission[] = Object.values(Permission).filter((v): v is Permission => typeof v === 'number');

const VIEWER_PERMISSIONS: Permission[] = [
    Permission.ORGANIZATION_VIEW,
    Permission.USERS_VIEW,
    Permission.INVITATIONS_VIEW,
    Permission.ROLES_VIEW,
    Permission.PROJECTS_VIEW,
    Permission.STAFF_VIEW,
    Permission.TOOLS_VIEW,
    Permission.WORKSPACE_FLOWS_VIEW,
    Permission.KNOWLEDGE_SOURCES_VIEW,
    Permission.STORAGE_VIEW,
    Permission.CHATS_VIEW,
    Permission.LLM_CONFIGS_VIEW,
    Permission.API_KEYS_VIEW,
    Permission.WORKFLOW_FLOWS_VIEW,
    Permission.SESSIONS_VIEW,
    Permission.TEMPLATES_VIEW,
    Permission.COLLECTIONS_VIEW,
    Permission.NAIVE_RAG_VIEW,
    Permission.GRAPH_RAG_VIEW,
];

const MEMBER_PERMISSIONS: Permission[] = [
    // Organizations & Access — view only
    Permission.ORGANIZATION_VIEW,
    Permission.USERS_VIEW,
    Permission.INVITATIONS_VIEW,
    Permission.ROLES_VIEW,
    // Workspace Resources — full access
    Permission.PROJECTS_VIEW,
    Permission.PROJECTS_CREATE,
    Permission.PROJECTS_EDIT,
    Permission.PROJECTS_DELETE,
    Permission.PROJECTS_EXPORT,
    Permission.STAFF_VIEW,
    Permission.STAFF_CREATE,
    Permission.STAFF_EDIT,
    Permission.STAFF_DELETE,
    Permission.TOOLS_VIEW,
    Permission.TOOLS_CREATE,
    Permission.TOOLS_EDIT,
    Permission.TOOLS_DELETE,
    Permission.WORKSPACE_FLOWS_VIEW,
    Permission.WORKSPACE_FLOWS_CREATE,
    Permission.WORKSPACE_FLOWS_EDIT,
    Permission.WORKSPACE_FLOWS_DELETE,
    Permission.KNOWLEDGE_SOURCES_VIEW,
    Permission.KNOWLEDGE_SOURCES_CREATE,
    Permission.KNOWLEDGE_SOURCES_EDIT,
    Permission.KNOWLEDGE_SOURCES_DELETE,
    Permission.STORAGE_VIEW,
    Permission.STORAGE_CREATE,
    Permission.STORAGE_EDIT,
    Permission.STORAGE_DELETE,
    Permission.STORAGE_EXPORT,
    Permission.CHATS_VIEW,
    Permission.CHATS_CREATE,
    // Configuration — view only
    Permission.LLM_CONFIGS_VIEW,
    // Workflows — full access
    Permission.WORKFLOW_FLOWS_VIEW,
    Permission.WORKFLOW_FLOWS_CREATE,
    Permission.WORKFLOW_FLOWS_EDIT,
    Permission.WORKFLOW_FLOWS_DELETE,
    Permission.SESSIONS_VIEW,
    Permission.SESSIONS_DELETE,
    Permission.TEMPLATES_VIEW,
    Permission.TEMPLATES_CREATE,
    Permission.TEMPLATES_EDIT,
    Permission.TEMPLATES_DELETE,
    // Knowledge Sources — view only
    Permission.COLLECTIONS_VIEW,
    Permission.NAIVE_RAG_VIEW,
    Permission.GRAPH_RAG_VIEW,
];

const ORG_ADMIN_PERMISSIONS: Permission[] = [
    // Organizations & Access — manage (no org create/delete, that's superadmin)
    Permission.ORGANIZATION_VIEW,
    Permission.ORGANIZATION_EDIT,
    Permission.USERS_VIEW,
    Permission.USERS_CREATE,
    Permission.USERS_EDIT,
    Permission.USERS_DELETE,
    Permission.USERS_EXPORT,
    Permission.INVITATIONS_VIEW,
    Permission.INVITATIONS_CREATE,
    Permission.INVITATIONS_DELETE,
    Permission.ROLES_VIEW,
    Permission.ROLES_CREATE,
    Permission.ROLES_EDIT,
    Permission.ROLES_DELETE,
    // Workspace Resources — full access
    Permission.PROJECTS_VIEW,
    Permission.PROJECTS_CREATE,
    Permission.PROJECTS_EDIT,
    Permission.PROJECTS_DELETE,
    Permission.PROJECTS_EXPORT,
    Permission.STAFF_VIEW,
    Permission.STAFF_CREATE,
    Permission.STAFF_EDIT,
    Permission.STAFF_DELETE,
    Permission.TOOLS_VIEW,
    Permission.TOOLS_CREATE,
    Permission.TOOLS_EDIT,
    Permission.TOOLS_DELETE,
    Permission.WORKSPACE_FLOWS_VIEW,
    Permission.WORKSPACE_FLOWS_CREATE,
    Permission.WORKSPACE_FLOWS_EDIT,
    Permission.WORKSPACE_FLOWS_DELETE,
    Permission.KNOWLEDGE_SOURCES_VIEW,
    Permission.KNOWLEDGE_SOURCES_CREATE,
    Permission.KNOWLEDGE_SOURCES_EDIT,
    Permission.KNOWLEDGE_SOURCES_DELETE,
    Permission.STORAGE_VIEW,
    Permission.STORAGE_CREATE,
    Permission.STORAGE_EDIT,
    Permission.STORAGE_DELETE,
    Permission.STORAGE_EXPORT,
    Permission.CHATS_VIEW,
    Permission.CHATS_CREATE,
    // Configuration & Secrets — full access
    Permission.LLM_CONFIGS_VIEW,
    Permission.LLM_CONFIGS_CREATE,
    Permission.LLM_CONFIGS_EDIT,
    Permission.LLM_CONFIGS_DELETE,
    Permission.API_KEYS_VIEW,
    Permission.API_KEYS_CREATE,
    Permission.API_KEYS_DELETE,
    // Workflows — full access
    Permission.WORKFLOW_FLOWS_VIEW,
    Permission.WORKFLOW_FLOWS_CREATE,
    Permission.WORKFLOW_FLOWS_EDIT,
    Permission.WORKFLOW_FLOWS_DELETE,
    Permission.SESSIONS_VIEW,
    Permission.SESSIONS_DELETE,
    Permission.TEMPLATES_VIEW,
    Permission.TEMPLATES_CREATE,
    Permission.TEMPLATES_EDIT,
    Permission.TEMPLATES_DELETE,
    // Knowledge Sources — full access
    Permission.COLLECTIONS_VIEW,
    Permission.COLLECTIONS_CREATE,
    Permission.COLLECTIONS_EDIT,
    Permission.COLLECTIONS_DELETE,
    Permission.NAIVE_RAG_VIEW,
    Permission.NAIVE_RAG_CREATE,
    Permission.NAIVE_RAG_EDIT,
    Permission.NAIVE_RAG_DELETE,
    Permission.GRAPH_RAG_VIEW,
    Permission.GRAPH_RAG_CREATE,
    Permission.GRAPH_RAG_EDIT,
    Permission.GRAPH_RAG_DELETE,
];

export const BUILT_IN_ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
    [UserRole.SUPER_ADMIN]: ALL_PERMISSIONS,
    [UserRole.ORG_ADMIN]: ORG_ADMIN_PERMISSIONS,
    [UserRole.MEMBER]: MEMBER_PERMISSIONS,
    [UserRole.VIEWER]: VIEWER_PERMISSIONS,
};
