export enum NodeType {
    AGENT = 'agent',
    TASK = 'task',
    TOOL = 'tool',
    LLM = 'llm',
    PROJECT = 'project',
    PYTHON = 'python',
    EDGE = 'edge',
    START = 'start',
    GROUP = 'group',
    TABLE = 'table',
    NOTE = 'note',
    FILE_EXTRACTOR = 'file-extractor',
    WEBHOOK_TRIGGER = 'webhook-trigger',
    END = 'end',
}
