export enum NodeType {
    AGENT = 'agent',
    TASK = 'task',
    TOOL = 'tool',
    LLM = 'llm',
    PROJECT = 'project',
    PYTHON = 'python',
    EDGE = 'edge',
    START = 'start',
    GROUP = 'group',
    TABLE = 'table',
    NOTE = 'note',
    FILE_EXTRACTOR = 'file-extractor',
    WEBHOOK_TRIGGER = 'webhook-trigger',
    TELEGRAM_TRIGGER = 'telegram-trigger',
    END = 'end',
    SUBGRAPH = 'subgraph',
    AUDIO_TO_TEXT = 'audio-to-text-node',
    CODE_AGENT = 'code-agent'
}
