FROM python:3.12.10-slim

WORKDIR /home/user/root/app

# RUN pip install --upgrade pip setuptools wheel
RUN pip install poetry

COPY ./manager/pyproject.toml .
COPY ./manager/poetry.lock .

RUN poetry config virtualenvs.create false && poetry install --no-root && rm -rf /root/.cache

COPY ./manager .
COPY ./tool ./tool


CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "1"]
