FROM node:20.17.0 AS build-stage

WORKDIR /home/user/root/app

COPY . .

RUN npm install --force && npm cache clean --force

RUN npm run build -- --configuration production

FROM docker.io/library/nginx:alpine AS production-stage

COPY --from=build-stage /home/user/root/app/dist/frontend-crewai/browser/ /usr/share/nginx/html/

COPY 50x.html /usr/share/nginx/html/
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
