"""
Django settings for django_app project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import sys
from datetime import timedelta
from pathlib import Path

import environ
from loguru import logger

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
env.read_env(BASE_DIR / ".env")

if env.bool("LOAD_DEBUG_ENV", False):
    logger.info("Load debug environments")
    env.read_env(BASE_DIR.parent / "debug.env", overwrite=True)

# SECURITY WARNING: don't run with debug turned on in production!
# SECURITY WARNING: keep the secret key used in production secret!
DEBUG = env.bool("DEBUG", False)

SECRET_KEY = env.str("SECRET_KEY")

ALLOWED_HOSTS = [
    "*",  # host.strip() for host in os.getenv("ALLOWED_HOSTS", "0.0.0.0, 127.0.0.1").split(",")
]


# Logging

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "loguru": {
            "class": "logging.StreamHandler",
            "stream": sys.stdout,
        },
    },
    "root": {
        "handlers": ["loguru"],
        "level": "DEBUG",
    },
}


# Application definition

INSTALLED_APPS = [
    "health_check",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "tables",
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "drf_spectacular",
    "django_filters",
    "corsheaders",
    "django_redis",
]


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "corsheaders.middleware.CorsMiddleware",
]


REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.LimitOffsetPagination",
    "PAGE_SIZE": 500000,
    "DEFAULT_FILTER_BACKENDS": ["django_filters.rest_framework.DjangoFilterBackend"],
    "EXCEPTION_HANDLER": "utils.exception_handler.custom_exception_handler",
    "DEFAULT_RENDERER_CLASSES": ["rest_framework.renderers.JSONRenderer"],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "tables.services.rbac.authentication.JwtOrApiKeyAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "login": env.str("LOGIN_THROTTLE_RATE", "5/min"),
        "password_reset_request": env.str(
            "PASSWORD_RESET_REQUEST_THROTTLE_RATE", "5/hour"
        ),
    },
}

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

JWT_SECRET = env.str("JWT_SECRET", SECRET_KEY)

SIMPLE_JWT = {
    "SIGNING_KEY": JWT_SECRET,
    "ALGORITHM": "HS256",
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=env.int("JWT_ACCESS_MINUTES", 15)),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=env.int("JWT_REFRESH_DAYS", 7)),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}

ROOT_URLCONF = "django_app.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env.str("POSTGRES_DB", "crew"),
        "USER": env.str("DB_USER", "postgres"),
        "PASSWORD": env.str("POSTGRES_PASSWORD", "admin"),
        "HOST": env.str("DB_HOST_NAME", "localhost"),
        "PORT": env.str("DB_PORT", "5432"),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
    {
        "NAME": "tables.services.rbac.utils.printable_ascii_password_validator.PrintableAsciiPasswordValidator",
    },
]

TELEGRAM_TRIGGER_FIELDS_PATH = (
    BASE_DIR / "tables" / "utils" / "data" / "telegram_fields.json"
)

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


REDIS_HOST = env.str("REDIS_HOST", "localhost")
REDIS_PORT = env.int("REDIS_PORT", 6379)
REDIS_PASSWORD = env.str("REDIS_PASSWORD")
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"redis://{REDIS_HOST}:{REDIS_PORT}/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "SERIALIZER": "django_redis.serializers.json.JSONSerializer",
            "PASSWORD": REDIS_PASSWORD,
        },
    }
}
MEDIA_ROOT = env.path("DJANGO_MEDIA_ROOT", BASE_DIR / "media")
MEDIA_URL = "/media/"

AUTH_USER_MODEL = "tables.User"

PASSWORD_RESET_TOKEN_TTL = env.int("PASSWORD_RESET_TOKEN_TTL", 900)  # 15m

# Email / password-recovery delivery.
#
# Two independent knobs:
#   * `EMAIL_HOST`         — "is SMTP delivery configured at all?" If set,
#                            Django uses the SMTP backend; if blank, it
#                            falls back to the console backend so the
#                            reset link is still observable in stdout.
#   * `EMAIL_HOST_USER` +  — "should Django authenticate?" Both blank =
#     `EMAIL_HOST_PASSWORD`  unauthenticated relay (mailpit, local Postfix,
#                            some corporate MTAs). Both set = plain SMTP
#                            AUTH against the configured host.
#
# Setting a user/password against a server that does NOT implement SMTP
# AUTH (mailpit is the common one) will raise `SMTPNotSupportedError` —
# leave them blank for those servers.
#
# Business-layer code that needs to branch on "should we advertise email
# delivery to the end user?" must ask `SmtpConfigService.is_configured()`
# rather than inspecting `EMAIL_BACKEND`.
EMAIL_HOST = env.str("EMAIL_HOST", "")
EMAIL_PORT = env.int("EMAIL_PORT", 587)
EMAIL_HOST_USER = env.str("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = env.str("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS", True)
EMAIL_USE_SSL = env.bool("EMAIL_USE_SSL", False)

DEFAULT_FROM_EMAIL = env.str("DEFAULT_FROM_EMAIL", "no-reply@epicstaff.local")

if EMAIL_HOST:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
else:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

FRONTEND_BASE_URL = env.str("FRONTEND_BASE_URL", "http://localhost:4200").rstrip("/")
FRONTEND_PASSWORD_RESET_PATH = env.str(
    "FRONTEND_PASSWORD_RESET_PATH", "/reset-password"
)

SSE_TICKET_TTL_SECONDS = 30

DEFAULT_ORGANIZATION_NAME = env.str("DEFAULT_ORGANIZATION_NAME", "Default Organization")

# Story 6 — User profile
PASSWORD_CHANGE_TICKET_TTL_SECONDS = env.int(
    "PASSWORD_CHANGE_TICKET_TTL_SECONDS", 300
)  # 5m
AVATAR_MAX_BYTES = env.int("AVATAR_MAX_BYTES", 5 * 1024 * 1024)  # 5MB
AVATAR_ALLOWED_FORMATS = [
    fmt.strip()
    for fmt in env.list("AVATAR_ALLOWED_FORMATS", default=["JPEG", "PNG"])
    if fmt.strip()
]

# Object storage
STORAGE_BACKEND = env.str("STORAGE_BACKEND", "s3")
STORAGE_ENDPOINT = env.str("STORAGE_ENDPOINT", "")
STORAGE_ACCESS_KEY = env.str("STORAGE_ACCESS_KEY", "")
STORAGE_SECRET_KEY = env.str("STORAGE_SECRET_KEY", "")
STORAGE_BUCKET_NAME = env.str("STORAGE_BUCKET_NAME", "epicstaff")
STORAGE_LOCAL_ROOT = env.str("STORAGE_LOCAL_ROOT", "/app/storage")

MAX_TOTAL_FILE_SIZE = 10 * 1024 * 1024  # 10MB

REDIS_TUNNEL_CONFIG_CHANNEL = env.str(
    "REDIS_TUNNEL_CONFIG_CHANNEL", "REDIS_TUNNEL_CONFIG_CHANNEL"
)
TUNNEL_URLS_HASH_KEY = env.str("TUNNEL_URLS_HASH_KEY", "tunnel_urls")
KNOWLEDGE_DOCUMENT_CHUNK_CHANNEL = env.str(
    "KNOWLEDGE_DOCUMENT_CHUNK_CHANNEL", "knowledge:chunk"
)
KNOWLEDGE_DOCUMENT_CHUNK_RESPONSE = env.str(
    "KNOWLEDGE_DOCUMENT_CHUNK_RESPONSE", "knowledge:chunk:response"
)
KNOWLEDGE_INDEXING_CHANNEL = env.str("KNOWLEDGE_INDEXING_CHANNEL", "knowledge:indexing")
STOP_SESSION_CHANNEL = env.str("STOP_SESSION_CHANNEL", "sessions:stop")

WEBHOOK_USE_TUNNEL = env.bool("WEBHOOK_USE_TUNNEL", False)

if WEBHOOK_USE_TUNNEL:
    WEBHOOK_TUNNEL = env("WEBHOOK_TUNNEL", default=None)
else:
    WEBHOOK_TUNNEL = None

REQUEST_WEBHOOK_UPDATE_CHANNEL = env.str(
    "REQUEST_WEBHOOK_UPDATE_CHANNEL", "REQUEST_WEBHOOK_UPDATE_CHANNEL"
)
SESSION_STATUS_CHANNEL = env.str("SESSION_STATUS_CHANNEL", "sessions:session_status")
CODE_RESULT_CHANNEL = env.str("CODE_RESULT_CHANNEL", "code_results")
GRAPH_MESSAGES_CHANNEL = env.str("GRAPH_MESSAGES_CHANNEL", "graph:messages")
GRAPH_MESSAGE_UPDATE_CHANNEL = env.str(
    "GRAPH_MESSAGE_UPDATE_CHANNEL", "graph:message:update"
)
WEBHOOK_MESSAGE_CHANNEL = env.str("WEBHOOK_MESSAGE_CHANNEL", "webhooks")
STORAGE_MUTATION_CHANNEL = env.str("STORAGE_MUTATION_CHANNEL", "storage_mutations")
TELEGRAM_TRIGGER_PREFIX = "telegram-trigger/"


WEBHOOK_HOST_NAME = env.str("WEBHOOK_HOST_NAME", "localhost")
WEBHOOK_PORT = env.int("WEBHOOK_PORT", 8009)

SPECTACULAR_SETTINGS = {
    "TITLE": "CrewAI SheetsUI API",
    "VERSION": "v1",
    "SERVE_INCLUDE_SCHEMA": False,
    "SWAGGER_UI_SETTINGS": {
        "persistAuthorization": True,
    },
    "POSTPROCESSING_HOOKS": [
        "drf_spectacular.hooks.postprocess_schema_enums",
        "django_app.spectacular_hooks.assign_tags_postprocessing_hook",
    ],
}
