export enum Permission {
    // Organizations & Access
    ORGANIZATION_VIEW = 1,
    ORGANIZATION_CREATE = 2,
    ORGANIZATION_EDIT = 3,
    ORGANIZATION_DELETE = 4,
    ORGANIZATION_EXPORT = 5,

    USERS_VIEW = 6,
    USERS_CREATE = 7,
    USERS_EDIT = 8,
    USERS_DELETE = 9,
    USERS_EXPORT = 10,

    ROLES_VIEW = 11,
    ROLES_CREATE = 12,
    ROLES_EDIT = 13,
    ROLES_DELETE = 14,
    ROLES_EXPORT = 15,

    INVITATIONS_VIEW = 16,
    INVITATIONS_CREATE = 17,
    INVITATIONS_EDIT = 18,
    INVITATIONS_DELETE = 19,
    INVITATIONS_EXPORT = 20,

    // Workspace Resources
    PROJECTS_VIEW = 21,
    PROJECTS_CREATE = 22,
    PROJECTS_EDIT = 23,
    PROJECTS_DELETE = 24,
    PROJECTS_EXPORT = 25,

    STAFF_VIEW = 26,
    STAFF_CREATE = 27,
    STAFF_EDIT = 28,
    STAFF_DELETE = 29,
    STAFF_EXPORT = 30,

    TOOLS_VIEW = 31,
    TOOLS_CREATE = 32,
    TOOLS_EDIT = 33,
    TOOLS_DELETE = 34,
    TOOLS_EXPORT = 35,

    WORKSPACE_FLOWS_VIEW = 36,
    WORKSPACE_FLOWS_CREATE = 37,
    WORKSPACE_FLOWS_EDIT = 38,
    WORKSPACE_FLOWS_DELETE = 39,
    WORKSPACE_FLOWS_EXPORT = 40,

    KNOWLEDGE_SOURCES_VIEW = 41,
    KNOWLEDGE_SOURCES_CREATE = 42,
    KNOWLEDGE_SOURCES_EDIT = 43,
    KNOWLEDGE_SOURCES_DELETE = 44,
    KNOWLEDGE_SOURCES_EXPORT = 45,

    STORAGE_VIEW = 46,
    STORAGE_CREATE = 47,
    STORAGE_EDIT = 48,
    STORAGE_DELETE = 49,
    STORAGE_EXPORT = 50,

    CHATS_VIEW = 51,
    CHATS_CREATE = 52,
    CHATS_EDIT = 53,
    CHATS_DELETE = 54,
    CHATS_EXPORT = 55,

    // Configuration & Secrets
    LLM_CONFIGS_VIEW = 56,
    LLM_CONFIGS_CREATE = 57,
    LLM_CONFIGS_EDIT = 58,
    LLM_CONFIGS_DELETE = 59,
    LLM_CONFIGS_EXPORT = 60,

    API_KEYS_VIEW = 61,
    API_KEYS_CREATE = 62,
    API_KEYS_DELETE = 63,
    API_KEYS_UPDATE = 64,
    API_KEYS_EXPORT = 65,

    // Workflows
    WORKFLOW_FLOWS_VIEW = 66,
    WORKFLOW_FLOWS_CREATE = 67,
    WORKFLOW_FLOWS_EDIT = 68,
    WORKFLOW_FLOWS_DELETE = 69,
    WORKFLOW_FLOWS_EXPORT = 70,

    SESSIONS_VIEW = 71,
    SESSIONS_CREATE = 72,
    SESSIONS_EDIT = 73,
    SESSIONS_DELETE = 74,
    SESSIONS_EXPORT = 75,

    TEMPLATES_VIEW = 76,
    TEMPLATES_CREATE = 77,
    TEMPLATES_EDIT = 78,
    TEMPLATES_DELETE = 79,
    TEMPLATES_EXPORT = 80,

    // Knowledge Sources
    COLLECTIONS_VIEW = 81,
    COLLECTIONS_CREATE = 82,
    COLLECTIONS_EDIT = 83,
    COLLECTIONS_DELETE = 84,
    COLLECTIONS_EXPORT = 85,

    NAIVE_RAG_VIEW = 86,
    NAIVE_RAG_CREATE = 87,
    NAIVE_RAG_EDIT = 88,
    NAIVE_RAG_DELETE = 89,
    NAIVE_RAG_EXPORT = 90,

    GRAPH_RAG_VIEW = 91,
    GRAPH_RAG_CREATE = 92,
    GRAPH_RAG_EDIT = 93,
    GRAPH_RAG_DELETE = 94,
    GRAPH_RAG_EXPORT = 95,
}
