export interface Language {
  id: string | null;
  name: string;
}

export const AVAILABLE_LANGUAGES: Language[] = [
  { id: null, name: 'Auto' },
  { id: 'en', name: 'English' },
  { id: 'nl', name: 'Dutch' },
  { id: 'uk', name: 'Ukrainian' },
  { id: 'fr', name: 'French' },

  { id: 'ar', name: 'Arabic' },

  { id: 'bs', name: 'Bosnian' },
  { id: 'bg', name: 'Bulgarian' },
  { id: 'ca', name: 'Catalan' },
  { id: 'zh', name: 'Chinese' },
  { id: 'hr', name: 'Croatian' },
  { id: 'cs', name: 'Czech' },
  { id: 'da', name: 'Danish' },

  { id: 'et', name: 'Estonian' },
  { id: 'fi', name: 'Finnish' },

  { id: 'gl', name: 'Galician' },
  { id: 'de', name: 'German' },
  { id: 'el', name: 'Greek' },
  { id: 'he', name: 'Hebrew' },
  { id: 'hi', name: 'Hindi' },
  { id: 'hu', name: 'Hungarian' },
  { id: 'is', name: 'Icelandic' },
  { id: 'id', name: 'Indonesian' },
  { id: 'it', name: 'Italian' },
  { id: 'ja', name: 'Japanese' },
  { id: 'kn', name: 'Kannada' },
  { id: 'kk', name: 'Kazakh' },
  { id: 'ko', name: 'Korean' },
  { id: 'lv', name: 'Latvian' },
  { id: 'lt', name: 'Lithuanian' },
  { id: 'mk', name: 'Macedonian' },
  { id: 'ms', name: 'Malay' },
  { id: 'mr', name: 'Marathi' },
  { id: 'mi', name: 'Maori' },
  { id: 'ne', name: 'Nepali' },
  { id: 'no', name: 'Norwegian' },
  { id: 'fa', name: 'Persian' },
  { id: 'pl', name: 'Polish' },
  { id: 'pt', name: 'Portuguese' },
  { id: 'ro', name: 'Romanian' },
  { id: 'sr', name: 'Serbian' },
  { id: 'sk', name: 'Slovak' },
  { id: 'sl', name: 'Slovenian' },
  { id: 'es', name: 'Spanish' },
  { id: 'sw', name: 'Swahili' },
  { id: 'sv', name: 'Swedish' },
  { id: 'tl', name: 'Tagalog' },
  { id: 'ta', name: 'Tamil' },
  { id: 'th', name: 'Thai' },
  { id: 'tr', name: 'Turkish' },
  { id: 'af', name: 'Afrikaans' },
  { id: 'hy', name: 'Armenian' },
  { id: 'az', name: 'Azerbaijani' },
  { id: 'ur', name: 'Urdu' },
  { id: 'vi', name: 'Vietnamese' },
  { id: 'cy', name: 'Welsh' },
];
