FROM docker:latest


RUN apk add --no-cache \
    bash \
    redis \
    curl \
    docker-cli-compose

# Create working directory
WORKDIR /app

# Copy the monitoring script
COPY redis-monitor/redis-monitor.sh /app/redis-monitor.sh
COPY docker-compose.yaml /app/docker-compose.yaml

# Make script executable
RUN chmod +x /app/redis-monitor.sh

# Run the monitoring script
CMD ["/app/redis-monitor.sh"]