# Generated by Django 5.1.1 on 2024-09-26 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConfigLLM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("temperature", models.FloatField(default=0.7)),
                ("num_ctx", models.IntegerField(default=25)),
            ],
        ),
        migrations.CreateModel(
            name="EmbeddingModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="LLMModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("comments", models.TextField(blank=True, null=True)),
                ("context_size", models.IntegerField(default=0)),
                ("base_url", models.URLField(blank=True, null=True)),
                ("deployment", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.TextField()),
                ("goal", models.TextField()),
                ("backstory", models.TextField()),
                ("allow_delegation", models.BooleanField(default=False)),
                ("memory", models.TextField(blank=True, null=True)),
                ("max_iter", models.IntegerField(default=25)),
                (
                    "fcm_llm_config",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fcm_agents_config",
                        to="tables.configllm",
                    ),
                ),
                (
                    "llm_config",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="llm_agents_config",
                        to="tables.configllm",
                    ),
                ),
                (
                    "fcm_llm_model",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fcm_agents",
                        to="tables.llmmodel",
                    ),
                ),
                (
                    "llm_model",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="llm_agents",
                        to="tables.llmmodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ManagerLLMModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "llm_config",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tables.configllm",
                    ),
                ),
                (
                    "llm_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tables.llmmodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Crew",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comments", models.TextField(blank=True, null=True)),
                ("name", models.TextField()),
                ("assignment", models.TextField()),
                (
                    "process",
                    models.CharField(
                        choices=[
                            ("sequential", "Sequential"),
                            ("hierarchical", "Hierarchical"),
                        ],
                        default="sequential",
                        max_length=255,
                    ),
                ),
                ("verbose", models.BooleanField(default=False)),
                ("memory", models.BooleanField(default=False)),
                ("temperature", models.FloatField()),
                ("agents", models.ManyToManyField(to="tables.agent")),
                (
                    "embedding_model",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tables.embeddingmodel",
                    ),
                ),
                (
                    "manager_llm_model",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tables.managerllmmodel",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="llmmodel",
            name="llm_provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="tables.provider"
            ),
        ),
        migrations.AddField(
            model_name="embeddingmodel",
            name="embedding_provider",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tables.provider",
            ),
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("end", "End"),
                            ("run", "Run"),
                            ("wait_for_user", "Wait For User"),
                            ("error", "Error"),
                        ],
                        default="run",
                        max_length=255,
                    ),
                ),
                (
                    "crew",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tables.crew",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("instructions", models.TextField()),
                ("expected_output", models.TextField()),
                ("order", models.IntegerField()),
                (
                    "agent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tables.agent",
                    ),
                ),
                (
                    "crew",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tables.crew",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TemplateAgent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tables.agent"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("description", models.TextField()),
                ("requires_model", models.BooleanField()),
                (
                    "embedding_model",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tables.embeddingmodel",
                    ),
                ),
                (
                    "llm_config",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tables.configllm",
                    ),
                ),
                (
                    "llm_model",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tables.llmmodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EnabledTools",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tools", models.ManyToManyField(to="tables.tool")),
            ],
        ),
        migrations.AddField(
            model_name="agent",
            name="tools",
            field=models.ManyToManyField(to="tables.tool"),
        ),
    ]
