# Generated by Django 5.1.1 on 2024-09-26 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="crew",
            name="temperature",
        ),
        migrations.AddField(
            model_name="crew",
            name="manager_llm_config",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tables.configllm",
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="conversation",
            field=models.TextField(blank=True),
        ),
    ]
