# Generated by Django 5.1.1 on 2024-09-26 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0002_remove_crew_temperature_crew_manager_llm_config_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="status",
            field=models.CharField(
                choices=[
                    ("end", "End"),
                    ("run", "Run"),
                    ("wait_for_user", "Wait For User"),
                    ("error", "Error"),
                ],
                max_length=255,
            ),
        ),
    ]
