# Generated by Django 5.1.1 on 2024-09-26 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0003_alter_session_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message_from",
                    models.CharField(
                        choices=[("user", "User"), ("crew", "Crew")], max_length=255
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tables.session"
                    ),
                ),
            ],
        ),
    ]
