# Generated by Django 5.1.1 on 2024-10-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0004_sessionmessage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="crew",
            name="manager_llm_config",
        ),
        migrations.AlterField(
            model_name="agent",
            name="tools",
            field=models.ManyToManyField(blank=True, to="tables.tool"),
        ),
        migrations.AlterField(
            model_name="crew",
            name="agents",
            field=models.ManyToManyField(blank=True, to="tables.agent"),
        ),
    ]
