# Generated by Django 5.1.1 on 2024-10-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tables",
            "0006_alter_crew_manager_llm_model_crew_manager_llm_config_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="tool",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name="EnabledTools",
        ),
    ]
