# Generated by Django 5.1.1 on 2024-10-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0007_tool_enabled_delete_enabledtools"),
    ]

    operations = [
        migrations.AddField(
            model_name="embeddingmodel",
            name="base_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="embeddingmodel",
            name="deployment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
