# Generated by Django 5.1.1 on 2024-10-04 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tables",
            "0009_alter_agent_fcm_llm_config_alter_agent_fcm_llm_model_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="templateagent",
            name="agent",
        ),
        migrations.AddField(
            model_name="templateagent",
            name="allow_delegation",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="templateagent",
            name="backstory",
            field=models.TextField(default="string"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="templateagent",
            name="fcm_llm_config",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fcm_template_agents_config",
                to="tables.configllm",
            ),
        ),
        migrations.AddField(
            model_name="templateagent",
            name="fcm_llm_model",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fcm_template_agents",
                to="tables.llmmodel",
            ),
        ),
        migrations.AddField(
            model_name="templateagent",
            name="goal",
            field=models.TextField(default="string"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="templateagent",
            name="llm_config",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="llm_template_agents_config",
                to="tables.configllm",
            ),
        ),
        migrations.AddField(
            model_name="templateagent",
            name="llm_model",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="llm_template_agents",
                to="tables.llmmodel",
            ),
        ),
        migrations.AddField(
            model_name="templateagent",
            name="max_iter",
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name="templateagent",
            name="memory",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="templateagent",
            name="role",
            field=models.TextField(default="Some role"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="templateagent",
            name="tools",
            field=models.ManyToManyField(blank=True, default=[], to="tables.tool"),
        ),
    ]
