# Generated by Django 5.1.1 on 2024-10-07 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0010_remove_templateagent_agent_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="llmmodel",
            name="context_size",
        ),
    ]
