# Generated by Django 5.1.2 on 2024-10-16 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0011_remove_llmmodel_context_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='name_alias',
            field=models.TextField(default='name_alias'),
            preserve_default=False,
        ),
    ]
