# Generated by Django 5.1.2 on 2024-10-18 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0012_tool_name_alias'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'get_latest_by': ['id']},
        ),
    ]
