# Generated by Django 5.1.2 on 2024-10-23 09:04

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0013_alter_session_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="llmmodel",
            old_name="comments",
            new_name="description",
        ),
        migrations.RemoveField(
            model_name="crew",
            name="verbose",
        ),
        migrations.RemoveField(
            model_name="session",
            name="conversation",
        ),
        migrations.AddField(
            model_name="session",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now
            ),
        ),
        migrations.RemoveField(
            model_name="agent",
            name="memory",
        ),
        migrations.AddField(
            model_name="agent",
            name="memory",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="crew",
            name="assignment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
