# Generated by Django 5.1.2 on 2024-10-23 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0014_rename_comments_llmmodel_description_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="crew",
            old_name="comments",
            new_name="description",
        ),
    ]
