# Generated by Django 5.1.2 on 2024-10-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0015_rename_comments_crew_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="templateagent",
            name="memory",
            field=models.BooleanField(default=False),
        ),
    ]
