# Generated by Django 5.1.2 on 2024-11-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0016_alter_templateagent_memory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="order",
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="tool",
            name="requires_model",
            field=models.BooleanField(default=False),
        ),
    ]
