# Generated by Django 5.1.2 on 2024-11-12 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0017_alter_task_order_alter_tool_requires_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
