# Generated by Django 5.1.2 on 2024-11-15 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0018_session_finished_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='crew',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tables.crew'),
        ),
    ]
