# Generated by Django 5.1.2 on 2024-11-20 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0019_alter_session_crew'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmmodel',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='crew',
            name='embedding_model',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.embeddingmodel'),
        ),
        migrations.AlterField(
            model_name='crew',
            name='manager_llm_config',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crew_manager_llm_config', to='tables.configllm'),
        ),
        migrations.AlterField(
            model_name='crew',
            name='manager_llm_model',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crew_manager_llm_model', to='tables.llmmodel'),
        ),
        migrations.CreateModel(
            name='LLMDefaultAgentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_llm_config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_agent_llm_config', to='tables.configllm')),
                ('default_llm_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_agent_llm_model', to='tables.llmmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LLMDefaultCrewConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_llm_config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_crew_llm_config', to='tables.configllm')),
                ('default_llm_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_crew_llm_model', to='tables.llmmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
