# Generated by Django 5.1.3 on 2024-11-22 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0022_create_default_llm_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llmdefaultcrewconfig',
            name='default_llm_config',
        ),
        migrations.RemoveField(
            model_name='llmdefaultcrewconfig',
            name='default_llm_model',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='fcm_llm_model',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='llm_model',
        ),
        migrations.RemoveField(
            model_name='crew',
            name='manager_llm_model',
        ),
        migrations.RemoveField(
            model_name='templateagent',
            name='fcm_llm_model',
        ),
        migrations.RemoveField(
            model_name='templateagent',
            name='llm_model',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='llm_model',
        ),
        migrations.AlterField(
            model_name='agent',
            name='fcm_llm_config',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fcm_agents', to='tables.configllm'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='llm_config',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_agents', to='tables.configllm'),
        ),
        migrations.AlterField(
            model_name='crew',
            name='manager_llm_config',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_crews', to='tables.configllm'),
        ),
        migrations.AlterField(
            model_name='templateagent',
            name='fcm_llm_config',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fcm_template_agents', to='tables.configllm'),
        ),
        migrations.AlterField(
            model_name='templateagent',
            name='llm_config',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_template_agents', to='tables.configllm'),
        ),
        migrations.CreateModel(
            name='DefaultAgentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_llm_config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_agent_config', to='tables.configllm')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DefaultCrewConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_llm_config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_crew_config', to='tables.configllm')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='LLMDefaultAgentConfig',
        ),
        migrations.DeleteModel(
            name='LLMDefaultCrewConfig',
        ),
    ]
