# Generated by Django 5.1.3 on 2024-11-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0023_remove_llmdefaultcrewconfig_default_llm_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configllm',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
