# Generated by Django 5.1.3 on 2024-11-25 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0024_configllm_is_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultLLMConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('llm_config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='default_llm_config', to='tables.configllm')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
