# Generated by Django 5.1.3 on 2024-11-25 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0025_defaultllmconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultagentconfig',
            name='allow_delegation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='defaultagentconfig',
            name='max_iter',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='defaultagentconfig',
            name='memory',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='defaultagentconfig',
            name='default_llm_config',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='default_agent_config', to='tables.configllm'),
        ),
    ]
