# Generated by Django 5.1.3 on 2024-11-25 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0026_defaultagentconfig_allow_delegation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='defaultagentconfig',
            old_name='default_llm_config',
            new_name='llm_config',
        ),
    ]
