# Generated by Django 5.1.3 on 2024-11-25 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0027_rename_default_llm_config_defaultagentconfig_llm_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaultcrewconfig',
            name='default_llm_config',
        ),
        migrations.AddField(
            model_name='defaultcrewconfig',
            name='embedding_model',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.embeddingmodel'),
        ),
        migrations.AddField(
            model_name='defaultcrewconfig',
            name='manager_llm_config',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='default_crew_config', to='tables.configllm'),
        ),
        migrations.AddField(
            model_name='defaultcrewconfig',
            name='memory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='defaultcrewconfig',
            name='process',
            field=models.CharField(choices=[('sequential', 'Sequential'), ('hierarchical', 'Hierarchical')], default='sequential', max_length=255),
        ),
    ]
