# Generated by Django 5.1.3 on 2024-11-26 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0028_remove_defaultcrewconfig_default_llm_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultagentconfig',
            name='fcm_llm_config',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_agent_fcm_config', to='tables.configllm'),
        ),
        migrations.AlterField(
            model_name='defaultagentconfig',
            name='llm_config',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_agent_config', to='tables.configllm'),
        ),
        migrations.AlterField(
            model_name='defaultcrewconfig',
            name='manager_llm_config',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_crew_config', to='tables.configllm'),
        ),
    ]
