# Generated by Django 5.1.3 on 2024-11-27 09:21

import django.utils.timezone
from django.db import migrations, models


def populate_custom_name(apps, schema_editor):
    ConfigLLM = apps.get_model('tables', 'ConfigLLM')

    for user_id in ConfigLLM.objects.values_list('model__llm_provider__id', flat=True).distinct():
        configs = ConfigLLM.objects.filter(model__llm_provider__id=user_id)
        for index, config in enumerate(configs, start=1):
            config.custom_name = f"llm_config_{index}"
            config.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0029_defaultagentconfig_fcm_llm_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configllm',
            name='custom_name',
            field=models.TextField(null=True, unique=True)
        ),
        migrations.RunPython(populate_custom_name),
        migrations.AlterField(
            model_name='configllm',
            name='custom_name',
            field=models.TextField(unique=True),
        ),
    ]
