# Generated by Django 5.1.3 on 2024-12-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0030_configllm_custom_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='crew_schema',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='session',
            name='finished_at',
            field=models.DateTimeField(null=True),
        ),
    ]
