# Generated by Django 5.1.3 on 2024-12-02 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0031_session_crew_schema_alter_session_finished_at"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ConfigLLM",
            new_name="LLMConfig",
        ),
        migrations.RemoveField(
            model_name="agent",
            name="tools",
        ),
        migrations.RemoveField(
            model_name="crew",
            name="embedding_model",
        ),
        migrations.RemoveField(
            model_name="defaultcrewconfig",
            name="embedding_model",
        ),
        migrations.RemoveField(
            model_name="defaultllmconfig",
            name="llm_config",
        ),
        migrations.RemoveField(
            model_name="templateagent",
            name="tools",
        ),
        migrations.RemoveField(
            model_name="tool",
            name="embedding_model",
        ),
        migrations.RemoveField(
            model_name="tool",
            name="llm_config",
        ),
        migrations.RemoveField(
            model_name="tool",
            name="requires_model",
        ),
        migrations.AddField(
            model_name="defaultllmconfig",
            name="is_visible",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="defaultllmconfig",
            name="model",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="tables.llmmodel",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="defaultllmconfig",
            name="num_ctx",
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name="defaultllmconfig",
            name="temperature",
            field=models.FloatField(default=0.7),
        ),
        migrations.AddField(
            model_name="embeddingmodel",
            name="predefined",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="llmmodel",
            name="predefined",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="DefaultEmbeddingConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[("retrieval_document", "Retrieval Doc")],
                        default="retrieval_document",
                        max_length=255,
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tables.embeddingmodel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EmbeddingConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("custom_name", models.TextField(unique=True)),
                (
                    "task_type",
                    models.CharField(
                        choices=[("retrieval_document", "Retrieval Doc")],
                        default="retrieval_document",
                        max_length=255,
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tables.embeddingmodel",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="crew",
            name="embedding_config",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tables.embeddingconfig",
            ),
        ),
        migrations.AddField(
            model_name="defaultcrewconfig",
            name="embedding_config",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tables.embeddingconfig",
            ),
        ),
        migrations.CreateModel(
            name="ToolConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("configuration", models.JSONField(default=dict)),
                (
                    "tool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tables.tool"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="agent",
            name="configured_tools",
            field=models.ManyToManyField(
                blank=True, default=[], to="tables.toolconfig"
            ),
        ),
        migrations.AddField(
            model_name="templateagent",
            name="configured_tools",
            field=models.ManyToManyField(
                blank=True, default=[], to="tables.toolconfig"
            ),
        ),
        migrations.CreateModel(
            name="ToolConfigField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("llm_config", "Llm Config"),
                            ("embedding_config", "Embedding Config"),
                            ("string", "String"),
                            ("boolean", "Boolean"),
                            ("any", "Any"),
                        ],
                        default="string",
                        max_length=255,
                    ),
                ),
                ("required", models.BooleanField(default=True)),
                (
                    "tool",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tool_fields",
                        to="tables.tool",
                    ),
                ),
            ],
            options={
                "unique_together": {("tool", "name")},
            },
        ),
    ]
