# Generated by Django 5.1.3 on 2024-12-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0032_rename_configllm_llmconfig_remove_agent_tools_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='embeddingconfig',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='embeddingmodel',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
