# Generated by Django 5.1.3 on 2024-12-04 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0033_embeddingconfig_is_visible_embeddingmodel_is_visible"),
    ]

    operations = [
        migrations.AddField(
            model_name="defaultembeddingconfig",
            name="api_key",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="defaultllmconfig",
            name="api_key",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="embeddingconfig",
            name="api_key",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="llmconfig",
            name="api_key",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="toolconfig",
            name="name",
            field=models.CharField(default="M_tool_config", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="defaultagentconfig",
            name="fcm_llm_config",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_agent_fcm_config",
                to="tables.llmconfig",
            ),
        ),
        migrations.AlterField(
            model_name="defaultagentconfig",
            name="llm_config",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_agent_config",
                to="tables.llmconfig",
            ),
        ),
        migrations.AlterField(
            model_name="defaultcrewconfig",
            name="manager_llm_config",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_crew_config",
                to="tables.llmconfig",
            ),
        ),
        migrations.AlterField(
            model_name="defaultembeddingconfig",
            name="model",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tables.embeddingmodel",
            ),
        ),
        migrations.AlterField(
            model_name="defaultllmconfig",
            name="model",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tables.llmmodel",
            ),
        ),
        migrations.AlterField(
            model_name="embeddingconfig",
            name="model",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tables.embeddingmodel",
            ),
        ),
        migrations.AlterField(
            model_name="llmconfig",
            name="model",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tables.llmmodel",
            ),
        ),
        migrations.AlterField(
            model_name="llmmodel",
            name="llm_provider",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tables.provider",
            ),
        ),
    ]
