# Generated by Django 5.1.3 on 2024-12-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0035_remove_duplicated_tools"),
    ]

    operations = [
        migrations.AlterField(
            model_name="toolconfigfield",
            name="data_type",
            field=models.CharField(
                choices=[
                    ("llm_config", "Llm Config"),
                    ("embedding_config", "Embedding Config"),
                    ("string", "String"),
                    ("boolean", "Boolean"),
                    ("any", "Any"),
                    ("integer", "Integer"),
                    ("float", "Float"),
                ],
                default="string",
                max_length=255,
            ),
        ),
    ]
