# Generated by Django 5.1.3 on 2024-12-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0036_alter_toolconfigfield_data_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="human_input",
            field=models.BooleanField(default=False),
        ),
    ]
