# Generated by Django 5.1.3 on 2024-12-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0037_task_human_input"),
    ]

    operations = [
        migrations.AddField(
            model_name="toolconfigfield",
            name="title",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
