# Generated by Django 5.1.3 on 2025-01-14 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0038_toolconfigfield_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentSessionMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("thought", models.TextField(blank=True, default="")),
                ("tool", models.TextField(blank=True, default="")),
                ("tool_input", models.TextField(blank=True, default="")),
                ("text", models.TextField(blank=True, default="")),
                ("result", models.TextField(blank=True, default="")),
                (
                    "agent",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tables.agent",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tables.session"
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["session", "created_at"],
                        name="tables_agen_session_601778_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TaskSessionMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("description", models.TextField(blank=True, default="")),
                ("name", models.TextField(blank=True, default="")),
                ("expected_output", models.TextField(blank=True, default="")),
                ("raw", models.TextField(blank=True, default="")),
                ("agent", models.TextField(blank=True, default="")),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tables.session"
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tables.task",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["session", "created_at"],
                        name="tables_task_session_b57cd6_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UserSessionMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("text", models.TextField()),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tables.session"
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["session", "created_at"],
                        name="tables_user_session_72b6d5_idx",
                    )
                ],
            },
        ),
    ]
