# Generated by Django 5.1.3 on 2025-01-21 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0039_agentsessionmessage_tasksessionmessage_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PythonCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.TextField()),
                ("entrypoint", models.TextField(default="main")),
                ("libraries", models.TextField(default="")),
            ],
        ),
        migrations.CreateModel(
            name="PythonCodeTool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True)),
                ("description", models.TextField()),
                ("args_schema", models.JSONField()),
                (
                    "python_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tables.pythoncode",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AgentPythonCodeTool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        help_text="The agent using the Python code tool.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="python_code_tools",
                        to="tables.agent",
                    ),
                ),
                (
                    "python_code_tool",
                    models.ForeignKey(
                        help_text="The Python code tool associated with the agent.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_associations",
                        to="tables.pythoncodetool",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent Python Code Tool Association",
                "verbose_name_plural": "Agent Python Code Tool Associations",
                "unique_together": {("agent", "python_code_tool")},
            },
        ),
    ]
