# Generated by Django 5.1.3 on 2025-01-28 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0040_pythoncode_pythoncodetool_agentpythoncodetool"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentpythoncodetool",
            name="agent",
            field=models.ForeignKey(
                help_text="The agent using the Python code tool.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agent_python_code_tools",
                to="tables.agent",
            ),
        ),
        migrations.AlterField(
            model_name="agentsessionmessage",
            name="tool",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="agentsessionmessage",
            name="tool_input",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
