# Generated by Django 5.1.3 on 2025-01-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0041_alter_agentpythoncodetool_agent_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PythonCodeResult",
            fields=[
                (
                    "execution_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("result_data", models.TextField(default=None, null=True)),
                ("stderr", models.TextField(default="")),
                ("stdout", models.TextField(default="")),
                ("returncode", models.IntegerField(default=0)),
            ],
        ),
    ]
