# Generated by Django 5.1.3 on 2025-02-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0042_pythoncoderesult"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="kickoff_inputs",
            field=models.JSONField(default=dict),
        ),
    ]
