# Generated by Django 5.1.3 on 2025-02-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0043_session_kickoff_inputs"),
    ]

    operations = [
        migrations.AddField(
            model_name="pythoncode",
            name="global_kwargs",
            field=models.JSONField(default=dict),
        ),
    ]
