# Generated by Django 5.1.3 on 2025-02-10 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0044_pythoncode_global_kwargs"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConditionalEdge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=255)),
                ("then", models.CharField(default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CrewNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("node_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Edge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_key", models.CharField(max_length=255)),
                ("end_key", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Graph",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("entry_point", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="PythonNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("node_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name="sessionmessage",
            name="session",
        ),
        migrations.RemoveIndex(
            model_name="agentsessionmessage",
            name="tables_agen_session_601778_idx",
        ),
        migrations.RemoveIndex(
            model_name="tasksessionmessage",
            name="tables_task_session_b57cd6_idx",
        ),
        migrations.RemoveIndex(
            model_name="usersessionmessage",
            name="tables_user_session_72b6d5_idx",
        ),
        migrations.RenameField(
            model_name="session",
            old_name="kickoff_inputs",
            new_name="initial_state",
        ),
        migrations.RemoveField(
            model_name="session",
            name="crew",
        ),
        migrations.RemoveField(
            model_name="session",
            name="crew_schema",
        ),
        migrations.AddField(
            model_name="agentsessionmessage",
            name="crew_id",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tables.crew",
            ),
        ),
        migrations.AddField(
            model_name="agentsessionmessage",
            name="execution_order",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="session",
            name="graph_schema",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="tasksessionmessage",
            name="crew_id",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tables.crew",
            ),
        ),
        migrations.AddField(
            model_name="tasksessionmessage",
            name="execution_order",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="usersessionmessage",
            name="crew_id",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tables.crew",
            ),
        ),
        migrations.AddField(
            model_name="usersessionmessage",
            name="execution_order",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="conditionaledge",
            name="python_code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tables.pythoncode"
            ),
        ),
        migrations.AddField(
            model_name="crewnode",
            name="crew",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tables.crew"
            ),
        ),
        migrations.AddField(
            model_name="edge",
            name="graph",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tables.graph"
            ),
        ),
        migrations.AddField(
            model_name="crewnode",
            name="graph",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tables.graph"
            ),
        ),
        migrations.AddField(
            model_name="conditionaledge",
            name="graph",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tables.graph"
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="graph",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tables.graph",
            ),
        ),
        migrations.AddField(
            model_name="pythonnode",
            name="graph",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tables.graph"
            ),
        ),
        migrations.AddField(
            model_name="pythonnode",
            name="python_code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tables.pythoncode"
            ),
        ),
        migrations.DeleteModel(
            name="SessionMessage",
        ),
    ]
