# Generated by Django 5.1.3 on 2025-02-11 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0045_conditionaledge_crewnode_edge_graph_pythonnode_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="agentsessionmessage",
            old_name="crew_id",
            new_name="crew",
        ),
        migrations.RenameField(
            model_name="tasksessionmessage",
            old_name="crew_id",
            new_name="crew",
        ),
        migrations.RenameField(
            model_name="usersessionmessage",
            old_name="crew_id",
            new_name="crew",
        ),
        migrations.AddField(
            model_name="agentsessionmessage",
            name="node_name",
            field=models.CharField(default=""),
        ),
        migrations.AddField(
            model_name="tasksessionmessage",
            name="node_name",
            field=models.CharField(default=""),
        ),
        migrations.AddField(
            model_name="usersessionmessage",
            name="node_name",
            field=models.CharField(default=""),
        ),
        migrations.AlterField(
            model_name="conditionaledge",
            name="graph",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conditional_edges",
                to="tables.graph",
            ),
        ),
        migrations.AlterField(
            model_name="crewnode",
            name="graph",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="crew_nodes",
                to="tables.graph",
            ),
        ),
        migrations.AlterField(
            model_name="edge",
            name="graph",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="edges",
                to="tables.graph",
            ),
        ),
        migrations.AlterField(
            model_name="pythonnode",
            name="graph",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="python_nodes",
                to="tables.graph",
            ),
        ),
    ]
