# Generated by Django 5.1.3 on 2025-02-12 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0046_rename_crew_id_agentsessionmessage_crew_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="status_data",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="conditionaledge",
            name="graph",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conditional_edge_list",
                to="tables.graph",
            ),
        ),
        migrations.AlterField(
            model_name="crewnode",
            name="graph",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="crew_node_list",
                to="tables.graph",
            ),
        ),
        migrations.AlterField(
            model_name="edge",
            name="graph",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="edge_list",
                to="tables.graph",
            ),
        ),
        migrations.AlterField(
            model_name="pythonnode",
            name="graph",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="python_node_list",
                to="tables.graph",
            ),
        ),
    ]
