# Generated by Django 5.1.3 on 2025-02-14 10:40

import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0048_enable_pgvector'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryDatabase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vector', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('payload', models.JSONField(blank=True, null=True)),
            ],
            options={
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['vector'], m=16, name='vector_index', opclasses=['vector_cosine_ops'])],
            },
        ),
    ]
