# Generated by Django 5.1.3 on 2025-02-17 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0049_memorydatabase"),
    ]

    operations = [
        migrations.CreateModel(
            name="GraphSessionMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("node_name", models.CharField(default="")),
                ("execution_order", models.IntegerField(default=0)),
                ("message_data", models.JSONField()),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tables.session"
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["session", "created_at"],
                        name="tables_grap_session_8a3a6b_idx",
                    )
                ],
            },
        ),
    ]
