# Generated by Django 5.1.3 on 2025-02-19 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0051_remove_crew_assignment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskcontext",
            name="context",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="context_task_list",
                to="tables.task",
            ),
        ),
        migrations.CreateModel(
            name="TaskPythonCodeTools",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_python_code_tool_list",
                        to="tables.task",
                    ),
                ),
                (
                    "tool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tables.pythoncodetool",
                    ),
                ),
            ],
            options={
                "unique_together": {("task", "tool")},
            },
        ),
    ]
