# Generated by Django 5.1.3 on 2025-02-19 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0052_alter_taskcontext_context_taskpythoncodetools"),
    ]

    operations = [
        migrations.RenameField(
            model_name="taskpythoncodetools",
            old_name="tool",
            new_name="python_code_tool",
        ),
        migrations.AlterUniqueTogether(
            name="taskpythoncodetools",
            unique_together={("task", "python_code_tool")},
        ),
    ]
