# Generated by Django 5.1.3 on 2025-02-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0053_rename_tool_taskpythoncodetools_python_code_tool_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="graphsessionmessage",
            name="tables_grap_session_8a3a6b_idx",
        ),
        migrations.RenameField(
            model_name="graphsessionmessage",
            old_name="node_name",
            new_name="name",
        ),
        migrations.AlterField(
            model_name="defaultagentconfig",
            name="max_rpm",
            field=models.IntegerField(default=100, null=True),
        ),
        migrations.AlterField(
            model_name="defaultcrewconfig",
            name="max_rpm",
            field=models.IntegerField(default=100, null=True),
        ),
        migrations.AlterField(
            model_name="graph",
            name="entry_point",
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
