# Generated by Django 5.1.3 on 2025-02-26 16:43

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0053_rename_tool_taskpythoncodetools_python_code_tool_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentMetadata',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_type', models.CharField(blank=True, choices=[('pdf', 'Pdf'), ('csv', 'Csv'), ('doc', 'Doc'), ('docx', 'Docx'), ('txt', 'Txt')], max_length=10)),
                ('chunk_strategy', models.CharField(choices=[('token', 'Token'), ('character', 'Char'), ('markdown', 'Markdown'), ('html', 'Html'), ('json', 'Json')], default='token', max_length=20)),
                ('chunk_size', models.PositiveIntegerField(blank=True, default=1000)),
                ('chunk_overlap', models.PositiveIntegerField(blank=True, default=150)),
                ('status', models.CharField(choices=[('new', 'New'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='new', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='defaultagentconfig',
            name='max_rpm',
            field=models.IntegerField(default=100, null=True),
        ),
        migrations.AlterField(
            model_name='defaultcrewconfig',
            name='max_rpm',
            field=models.IntegerField(default=100, null=True),
        ),
        migrations.AlterField(
            model_name='graph',
            name='entry_point',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='DocumentContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.BinaryField(help_text='Binary file content (max 12MB)')),
                ('document_metadata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document_content', to='tables.documentmetadata')),
            ],
        ),
        migrations.CreateModel(
            name='SourceCollection',
            fields=[
                ('collection_id', models.AutoField(primary_key=True, serialize=False)),
                ('collection_name', models.CharField(blank=True, max_length=255)),
                ('user_id', models.CharField(blank=True, default='dummy_user', max_length=120)),
                ('status', models.CharField(choices=[('new', 'New'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('embedder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tables.embeddingmodel')),
            ],
        ),
        migrations.AddField(
            model_name='documentmetadata',
            name='source_collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_metadata', to='tables.sourcecollection'),
        ),
        migrations.CreateModel(
            name='DocumentEmbedding',
            fields=[
                ('embedding_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_text', models.TextField()),
                ('vector', pgvector.django.vector.VectorField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings_doc', to='tables.documentmetadata')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings_coll', to='tables.sourcecollection')),
            ],
        ),
    ]
