# Generated by Django 5.1.3 on 2025-03-06 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0054_documentmetadata_alter_defaultagentconfig_max_rpm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='knowledge_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.sourcecollection'),
        ),
        migrations.AddField(
            model_name='crew',
            name='knowledge_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.sourcecollection'),
        ),
        migrations.AlterField(
            model_name='documentmetadata',
            name='chunk_strategy',
            field=models.CharField(choices=[('token', 'Token'), ('character', 'Char'), ('markdown', 'Markdown'), ('json', 'Json'), ('html', 'Html')], default='token', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentmetadata',
            name='file_type',
            field=models.CharField(blank=True, choices=[('pdf', 'Pdf'), ('csv', 'Csv'), ('docx', 'Docx'), ('txt', 'Txt'), ('json', 'Json'), ('html', 'Html')], max_length=10),
        ),
    ]
