# Generated by Django 5.1.3 on 2025-02-24 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tables",
            "0054_remove_graphsessionmessage_tables_grap_session_8a3a6b_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentpythoncodetool",
            name="agent",
            field=models.ForeignKey(
                help_text="The agent using the Python code tool.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="python_code_tools",
                to="tables.agent",
            ),
        ),
        migrations.AlterField(
            model_name="crewnode",
            name="crew",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="tables.crew"
            ),
        ),
        migrations.AlterField(
            model_name="crewnode",
            name="node_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="llmconfig",
            name="max_tokens",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="llmconfig",
            name="model",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="tables.llmmodel",
            ),
        ),
        migrations.AlterField(
            model_name="pythonnode",
            name="node_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="pythonnode",
            name="python_code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="tables.pythoncode"
            ),
        ),
        migrations.CreateModel(
            name="LLMNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("node_name", models.CharField(blank=True, max_length=255)),
                (
                    "graph",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="llm_node_list",
                        to="tables.graph",
                    ),
                ),
                (
                    "llm_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tables.llmconfig",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
