# Generated by Django 5.1.3 on 2025-02-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0058_remove_crewnode_position_remove_llmnode_position_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="python_code_tools",
            field=models.ManyToManyField(
                blank=True, default=[], to="tables.pythoncodetool"
            ),
        ),
        migrations.DeleteModel(
            name="AgentPythonCodeTool",
        ),
    ]
