# Generated by Django 5.1.3 on 2025-03-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0059_agent_python_code_tools_delete_agentpythoncodetool"),
    ]

    operations = [
        migrations.AddField(
            model_name="conditionaledge",
            name="input_map",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="crewnode",
            name="input_map",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="crewnode",
            name="output_variable_path",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="llmnode",
            name="input_map",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="llmnode",
            name="output_variable_path",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="pythonnode",
            name="input_map",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="pythonnode",
            name="output_variable_path",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
