# Generated by Django 5.1.3 on 2025-03-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0060_conditionaledge_input_map_crewnode_input_map_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="default_temperature",
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="crew",
            name="default_temperature",
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="defaultagentconfig",
            name="default_temperature",
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="defaultcrewconfig",
            name="default_temperature",
            field=models.FloatField(default=0.7),
        ),
    ]
