# Generated by Django 5.1.3 on 2025-03-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0061_alter_agent_default_temperature_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
                ("predifined", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CrewTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
                ("predifined", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GraphTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
                ("predifined", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="agent",
            name="tags",
            field=models.ManyToManyField(blank=True, null=True, to="tables.agenttag"),
        ),
        migrations.AddField(
            model_name="crew",
            name="tags",
            field=models.ManyToManyField(blank=True, null=True, to="tables.crewtag"),
        ),
        migrations.AddField(
            model_name="graph",
            name="tags",
            field=models.ManyToManyField(blank=True, null=True, to="tables.graphtag"),
        ),
    ]
