# Generated by Django 5.1.3 on 2025-03-07 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0055_agent_knowledge_collection_crew_knowledge_collection_and_more'),
        ('tables', '0061_alter_agent_default_temperature_and_more'),
    ]

    operations = [
    ]
