# Generated by Django 5.1.3 on 2025-03-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0062_agenttag_crewtag_graphtag_agent_tags_crew_tags_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="tags",
            field=models.ManyToManyField(blank=True, default=[], to="tables.agenttag"),
        ),
        migrations.AlterField(
            model_name="crew",
            name="tags",
            field=models.ManyToManyField(blank=True, default=[], to="tables.crewtag"),
        ),
        migrations.AlterField(
            model_name="graph",
            name="tags",
            field=models.ManyToManyField(blank=True, default=[], to="tables.graphtag"),
        ),
    ]
