# Generated by Django 5.1.3 on 2025-03-14 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0062_merge_20250307_1455"),
        ("tables", "0063_alter_agent_tags_alter_crew_tags_alter_graph_tags"),
    ]

    operations = []
