# Generated by Django 5.1.3 on 2025-03-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0064_merge_20250314_1123"),
    ]

    operations = [
        migrations.AddField(
            model_name="crew",
            name="metadata",
            field=models.JSONField(default=dict),
        ),
    ]
