# Generated by Django 5.1.3 on 2025-03-18 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0065_crew_metadata"),
    ]

    operations = [
        migrations.CreateModel(
            name="RealtimeAgent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("connection_key", models.TextField()),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tables.agent"
                    ),
                ),
            ],
        ),
    ]
