# Generated by Django 5.1.3 on 2025-03-21 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0067_realtimeagentmodel_realtimeagent_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RealtimeAgentModel',
            new_name='RealtimeModel',
        ),
    ]
