# Generated by Django 5.1.3 on 2025-03-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0068_rename_realtimeagentmodel_realtimemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtimeagent',
            name='distance_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.65, help_text='Float between 0.00 and 1.00 for knowledge', max_digits=3),
        ),
        migrations.AddField(
            model_name='realtimeagent',
            name='search_limit',
            field=models.PositiveIntegerField(blank=True, default=3, help_text='Integer between 0 and 1000 for knowledge'),
        ),
    ]
