# Generated by Django 5.1.3 on 2025-03-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0068_rename_realtimeagentmodel_realtimemodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="defaultagentconfig",
            name="default_temperature",
            field=models.FloatField(default=0.8),
        ),
    ]
