# Generated by Django 5.1.3 on 2025-03-25 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0069_realtimeagent_distance_threshold_and_more'),
        ('tables', '0070_rename_rt_model_name_realtimemodel_name_and_more'),
    ]

    operations = [
    ]
