# Generated by Django 5.1.3 on 2025-03-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0071_merge_20250325_1531"),
    ]

    operations = [
        migrations.CreateModel(
            name="RealtimeSessionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("connection_key", models.TextField()),
                ("data", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "realtime_session_items",
            },
        ),
    ]
