# Generated by Django 5.1.3 on 2025-03-28 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0072_realtimesessionitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcecollection',
            name='embedder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.embeddingconfig'),
        ),
    ]
