# Generated by Django 5.1.3 on 2025-03-29 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0072_realtimesessionitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="realtimeagent",
            name="realtime_config",
        ),
        migrations.AddField(
            model_name="agent",
            name="realtime_config",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tables.realtimeconfig",
            ),
        ),
    ]
