# Generated by Django 5.1.3 on 2025-03-29 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0073_alter_sourcecollection_embedder"),
        ("tables", "0073_remove_realtimeagent_realtime_config_and_more"),
    ]

    operations = []
