# Generated by Django 5.1.3 on 2025-03-29 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0074_merge_20250329_1039"),
    ]

    operations = [
        migrations.AddField(
            model_name="realtimemodel",
            name="provider",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tables.provider",
            ),
        ),
    ]
