# Generated by Django 5.1.3 on 2025-03-29 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0075_realtimemodel_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="realtimeconfig",
            name="custom_name",
            field=models.CharField(default="Realtime configuration", max_length=250),
            preserve_default=False,
        ),
    ]
