# Generated by Django 5.1.3 on 2025-04-11 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0077_remove_realtimeagent_connection_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealtimeTranscriptionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_name', models.CharField(max_length=250)),
                ('api_key', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='agent',
            name='realtime_config',
        ),
        migrations.AddField(
            model_name='realtimeagent',
            name='realtime_config',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.realtimeconfig'),
        ),
        migrations.AddField(
            model_name='realtimeagentchat',
            name='realtime_config',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.realtimeconfig'),
        ),
        migrations.AddField(
            model_name='realtimeagent',
            name='realtime_transcription_config',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.realtimetranscriptionconfig'),
        ),
        migrations.AddField(
            model_name='realtimeagentchat',
            name='realtime_transcription_config',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.realtimetranscriptionconfig'),
        ),
        migrations.CreateModel(
            name='RealtimeTranscriptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='whisper-1', max_length=250)),
                ('provider', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tables.provider')),
            ],
        ),
        migrations.AddField(
            model_name='realtimetranscriptionconfig',
            name='realtime_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.realtimetranscriptionmodel'),
        ),
    ]
