# Generated by Django 5.1.3 on 2025-04-11 09:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0078_realtimetranscriptionconfig_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realtimetranscriptionconfig',
            old_name='realtime_model',
            new_name='realtime_transcription_model',
        ),
        migrations.AddField(
            model_name='realtimeagentchat',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
