# Generated by Django 5.1.3 on 2025-04-22 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tables",
            "0079_rename_realtime_model_realtimetranscriptionconfig_realtime_transcription_model_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="session",
            old_name="initial_state",
            new_name="variables",
        ),
        migrations.RemoveField(
            model_name="graph",
            name="entry_point",
        ),
        migrations.AlterField(
            model_name="realtimeagent",
            name="agent",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="realtime_agent",
                serialize=False,
                to="tables.agent",
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="status",
            field=models.CharField(
                choices=[
                    ("end", "End"),
                    ("run", "Run"),
                    ("wait_for_user", "Wait For User"),
                    ("error", "Error"),
                    ("pending", "Pending"),
                ],
                max_length=255,
            ),
        ),
        migrations.CreateModel(
            name="StartNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("variables", models.JSONField(default=dict)),
                (
                    "graph",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tables.graph"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("graph",), name="unique_startnode_per_graph"
                    )
                ],
            },
        ),
    ]
