# Generated by Django 5.1.3 on 2025-04-17 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0080_auto_20250417_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtimeagent',
            name='agent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='realtime_agent', serialize=False, to='tables.agent'),
        ),
        migrations.AlterField(
            model_name='sourcecollection',
            name='collection_name',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
