# Generated by Django 5.1.3 on 2025-04-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0082_remove_documentcontent_document_metadata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentmetadata',
            name='additional_params',
            field=models.JSONField(default=dict),
        ),
    ]
