# Generated by Django 5.1.3 on 2025-04-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0083_documentmetadata_additional_params'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentmetadata',
            name='chunk_strategy',
            field=models.CharField(choices=[('token', 'Token'), ('character', 'Char'), ('markdown', 'Markdown'), ('json', 'Json'), ('html', 'Html'), ('csv', 'Csv')], default='token', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentmetadata',
            name='file_type',
            field=models.CharField(blank=True, choices=[('pdf', 'Pdf'), ('csv', 'Csv'), ('docx', 'Docx'), ('txt', 'Txt'), ('json', 'Json'), ('html', 'Html'), ('md', 'Md')], max_length=10),
        ),
    ]
