# Generated by Django 5.1.3 on 2025-04-29 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0080_rename_initial_state_session_variables_and_more'),
        ('tables', '0084_alter_documentmetadata_chunk_strategy_and_more'),
    ]

    operations = [
    ]
