# Generated by Django 5.1.3 on 2025-05-14 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0085_merge_20250429_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='time_to_live',
            field=models.IntegerField(default=3600, help_text='Session lifitime duration in seconds.'),
        ),
        migrations.AddField(
            model_name='session',
            name='status_updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='time_to_live',
            field=models.IntegerField(default=3600, help_text='Session lifitime duration in seconds.'),
        ),
        migrations.AlterField(
            model_name='crewnode',
            name='crew',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.crew'),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('run', 'Run'), ('wait_for_user', 'Wait For User'), ('error', 'Error'), ('end', 'End'), ('expired', 'Expired')], max_length=255),
        ),
    ]
