# Generated by Django 5.1.3 on 2025-05-16 11:41

from django.db import migrations, models
from datetime import datetime, timedelta, timezone


def set_status_updated_at(apps, schema_editor):
    Session = apps.get_model("tables", "Session")
    one_hour_ago_utc = datetime.now(timezone.utc) - timedelta(hours=1)
    Session.objects.filter(status_updated_at__isnull=True).update(
        status_updated_at=one_hour_ago_utc
    )


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0086_graph_time_to_live_session_status_updated_at_and_more"),
    ]

    operations = [
        migrations.RunPython(
            code=set_status_updated_at, reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name="session",
            name="status_updated_at",
            field=models.DateTimeField(),
        ),
    ]
