# Generated by Django 5.1.3 on 2025-06-01 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0086_remove_startnode_unique_startnode_per_graph_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConditionGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_name", models.CharField(max_length=255)),
                ("group_type", models.CharField(max_length=255)),
                (
                    "expression",
                    models.CharField(default=None, max_length=255, null=True),
                ),
                (
                    "manipulation",
                    models.CharField(default=None, max_length=255, null=True),
                ),
                (
                    "next_node",
                    models.CharField(default=None, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Condition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("condition", models.CharField(max_length=255)),
                (
                    "condition_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conditions",
                        to="tables.conditiongroup",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DecisionTableNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("node_name", models.CharField(blank=True, max_length=255)),
                ("input_map", models.JSONField(default=dict)),
                (
                    "output_variable_path",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "default_next_node",
                    models.CharField(default=None, max_length=255, null=True),
                ),
                (
                    "graph",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decision_table_node_list",
                        to="tables.graph",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="conditiongroup",
            name="decision_table_node",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="condition_groups",
                to="tables.decisiontablenode",
            ),
        ),
        migrations.AddConstraint(
            model_name="decisiontablenode",
            constraint=models.UniqueConstraint(
                fields=("graph", "node_name"),
                name="unique_graph_node_name_for_decision_table_node",
            ),
        ),
        migrations.AddConstraint(
            model_name="conditiongroup",
            constraint=models.UniqueConstraint(
                fields=("decision_table_node", "group_name"),
                name="unique_decision_table_node_group_name",
            ),
        ),
    ]
