# Generated by Django 5.1.3 on 2025-06-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0087_conditiongroup_condition_decisiontablenode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="condition",
            name="condition_name",
            field=models.CharField(max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="condition",
            name="condition",
            field=models.CharField(max_length=5000),
        ),
        migrations.AddConstraint(
            model_name="condition",
            constraint=models.UniqueConstraint(
                fields=("condition_group", "condition_name"),
                name="unique_condition_group_condition_name",
            ),
        ),
    ]
