# Generated by Django 5.1.3 on 2025-05-26 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0086_remove_startnode_unique_startnode_per_graph_and_more'),
        ('tables', '0087_alter_session_status_updated_at'),
    ]

    operations = [
    ]
