# Generated by Django 5.1.3 on 2025-05-28 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0088_merge_20250526_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='graph',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.graph'),
        ),
    ]
