# Generated by Django 5.1.3 on 2025-05-30 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0089_alter_session_graph"),
    ]

    operations = [
        migrations.AlterField(
            model_name="llmconfig",
            name="model",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tables.llmmodel",
            ),
        ),
        migrations.AlterField(
            model_name="llmnode",
            name="llm_config",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tables.llmconfig"
            ),
        ),
        migrations.AlterField(
            model_name="pythoncodetool",
            name="python_code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tables.pythoncode"
            ),
        ),
        migrations.AlterField(
            model_name="pythonnode",
            name="python_code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tables.pythoncode"
            ),
        ),
    ]
