# Generated by Django 5.1.3 on 2025-06-02 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0088_condition_condition_name_alter_condition_condition_and_more"),
        ("tables", "0090_alter_llmconfig_model_alter_llmnode_llm_config_and_more"),
    ]

    operations = []
