# Generated by Django 5.1.3 on 2025-06-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0091_merge_20250602_1048"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="condition",
            options={"ordering": ["order"]},
        ),
        migrations.AlterModelOptions(
            name="conditiongroup",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="condition",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="conditiongroup",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
