# Generated by Django 5.1.3 on 2025-06-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0091_merge_20250602_1048"),
    ]

    operations = [
        migrations.AddField(
            model_name="graphsessionmessage",
            name="uuid",
            field=models.UUIDField(editable=False, null=True),
        ),
    ]
