# Generated by Django 5.1.3 on 2025-06-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tables",
            "0092_alter_condition_options_alter_conditiongroup_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="decisiontablenode",
            name="next_error_node",
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
