# Generated by Django 5.1.3 on 2025-06-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0093_auto_20250604_1050"),
    ]

    operations = [
        migrations.AlterField(
            model_name="graphsessionmessage",
            name="uuid",
            field=models.UUIDField(editable=False, unique=True),
        ),
    ]
