# Generated by Django 5.1.3 on 2025-06-16 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0093_decisiontablenode_next_error_node"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="defaultcrewconfig",
            name="planning_llm_config",
        ),
        migrations.AddField(
            model_name="defaultcrewconfig",
            name="process",
            field=models.CharField(
                choices=[
                    ("sequential", "Sequential"),
                    ("hierarchical", "Hierarchical"),
                ],
                default="sequential",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="pythoncodetool",
            name="favorite",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tool",
            name="favorite",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="DefaultRealtimeAgentConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "search_limit",
                    models.PositiveIntegerField(
                        blank=True,
                        default=3,
                        help_text="Integer between 0 and 1000 for knowledge",
                    ),
                ),
                (
                    "distance_threshold",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.65,
                        help_text="Float between 0.00 and 1.00 for knowledge",
                        max_digits=3,
                    ),
                ),
                ("wake_word", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "stop_prompt",
                    models.CharField(
                        blank=True, default="stop", max_length=255, null=True
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        help_text="ISO-639-1 format",
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "voice_recognition_prompt",
                    models.TextField(
                        blank=True,
                        help_text="The prompt to use for the transcription, to guide the model (e.g. 'Expect words related to technology')",
                        null=True,
                    ),
                ),
                (
                    "voice",
                    models.CharField(
                        choices=[
                            ("alloy", "Alloy"),
                            ("ash", "Ash"),
                            ("ballad", "Ballad"),
                            ("coral", "Coral"),
                            ("echo", "Echo"),
                            ("fable", "Fable"),
                            ("onyx", "Onyx"),
                            ("nova", "Nova"),
                            ("sage", "Sage"),
                            ("shimmer", "Shimmer"),
                            ("verse", "Verse"),
                        ],
                        default="alloy",
                        max_length=20,
                    ),
                ),
                (
                    "realtime_config",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tables.realtimeconfig",
                    ),
                ),
                (
                    "realtime_transcription_config",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tables.realtimetranscriptionconfig",
                    ),
                ),
            ],
            options={
                "db_table": "default_realtime_agent_config",
            },
        ),
        migrations.CreateModel(
            name="DefaultToolConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "embedding_config",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_tool_embedding_config",
                        to="tables.defaultembeddingconfig",
                    ),
                ),
                (
                    "llm_config",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_tool_llm_config",
                        to="tables.defaultllmconfig",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
