# Generated by Django 5.1.3 on 2025-06-18 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0094_remove_defaultcrewconfig_planning_llm_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='memory_llm_config',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memory_llm_config', to='tables.llmconfig'),
        ),
        migrations.AlterField(
            model_name='crew',
            name='planning_llm_config',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planning_llm_config', to='tables.llmconfig'),
        ),
    ]
