# Generated by Django 5.1.3 on 2025-06-06 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0093_decisiontablenode_next_error_node"),
        ("tables", "0094_alter_graphsessionmessage_uuid"),
    ]

    operations = []
