# Generated by Django 5.1.3 on 2025-06-25 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0095_crew_memory_llm_config_and_more"),
    ]

    operations = [
        migrations.RunSQL("DROP TABLE IF EXISTS silk_request CASCADE;"),
        migrations.RunSQL("DROP TABLE IF EXISTS silk_response CASCADE;"),
        migrations.RunSQL("DROP TABLE IF EXISTS silk_profile CASCADE;"),
        migrations.RunSQL("DROP TABLE IF EXISTS silk_profile_queries CASCADE;"),
        migrations.RunSQL("DROP TABLE IF EXISTS silk_sqlquery CASCADE;"),
    ]
