# Generated by Django 5.1.3 on 2025-06-19 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0095_crew_memory_llm_config_and_more"),
        ("tables", "0095_merge_20250606_0907"),
    ]

    operations = []
