# Generated by Django 5.1.3 on 2025-06-24 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0095_crew_memory_llm_config_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="defaulttoolconfig",
            name="embedding_config",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_tool_embedding_config",
                to="tables.embeddingconfig",
            ),
        ),
        migrations.AlterField(
            model_name="defaulttoolconfig",
            name="llm_config",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_tool_llm_config",
                to="tables.llmconfig",
            ),
        ),
    ]
