# Generated by Django 5.1.3 on 2025-06-27 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0096_alter_defaulttoolconfig_embedding_config_and_more'),
        ('tables', '0096_auto_20250625_1508'),
    ]

    operations = [
    ]
