# Generated by Django 5.1.3 on 2025-06-30 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0096_merge_20250619_1258"),
        ("tables", "0097_merge_20250627_1333"),
    ]

    operations = []
