# Generated by Django 5.1.3 on 2025-07-02 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0097_merge_20250627_1333"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskConfiguredTools",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_configured_tool_list",
                        to="tables.task",
                    ),
                ),
                (
                    "tool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tables.toolconfig",
                    ),
                ),
            ],
            options={
                "unique_together": {("task", "tool")},
            },
        ),
        migrations.DeleteModel(
            name="TaskTools",
        ),
    ]
