# Generated by Django 5.1.3 on 2025-07-02 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0097_graph_persistent_variables"),
        ("tables", "0098_merge_20250630_0911"),
    ]

    operations = []
