# Generated by Django 5.1.3 on 2025-07-07 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0098_taskconfiguredtools_delete_tasktools"),
    ]

    operations = [
        migrations.RenameField(
            model_name="taskpythoncodetools",
            old_name="python_code_tool",
            new_name="tool",
        ),
        migrations.AlterUniqueTogether(
            name="taskpythoncodetools",
            unique_together={("task", "tool")},
        ),
    ]
