# Generated by Django 5.1.3 on 2025-07-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0099_merge_20250702_1326"),
    ]

    operations = [
        migrations.AlterField(
            model_name="graph",
            name="persistent_variables",
            field=models.BooleanField(
                default=False, help_text="If 'True' -> use variables from last session."
            ),
        ),
    ]
