# Generated by Django 5.1.3 on 2025-07-07 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0099_rename_python_code_tool_taskpythoncodetools_tool_and_more"),
        ("tables", "0100_alter_graph_persistent_variables"),
    ]

    operations = []
