# Generated by Django 5.1.3 on 2025-07-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0101_merge_20250707_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphsessionmessage',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
