# Generated by Django 5.1.3 on 2025-08-12 08:40

import django.db.models.deletion
from django.db import migrations, models


def create_venvs_for_pythoncode(apps, schema_editor):
    PythonCode = apps.get_model("tables", "PythonCode")
    Venv = apps.get_model("tables", "Venv")

    for code in PythonCode.objects.all():
        libraries = code.libraries or ""
        venv_name = f"venv_{code.pk}"  # deterministic unique name

        venv, created = Venv.objects.get_or_create(
            venv_name=venv_name,
            defaults={"libraries": libraries, "actual_data": {}},
        )
        code.venv = venv
        code.save(update_fields=["venv"])


def reverse_create_venvs_for_pythoncode(apps, schema_editor):
    PythonCode = apps.get_model("tables", "PythonCode")
    for code in PythonCode.objects.all():
        if code.venv:
            code.libraries = code.venv.libraries
            code.save(update_fields=["libraries"])
    # Note: we do not delete Venv records here to avoid data loss


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0102_alter_graphsessionmessage_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="DomainTask",
            fields=[
                ("id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("payload", models.JSONField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("create_venv", "Create Venv"),
                            ("install_libraries", "Install Libraries"),
                            ("get_libraries", "Get Libraries"),
                            ("get_venv_exists", "Get Venv Exists"),
                            ("remove_venv", "Remove Venv"),
                            ("execute_code", "Execute Code"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("success", "Success"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(blank=True, null=True)),
                ("data", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Venv",
            fields=[
                ("venv_name", models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ("libraries", models.TextField(default="")),
                ("actual_data", models.JSONField(default=dict)),
            ],
        ),
        migrations.AlterField(
            model_name="defaultagentconfig",
            name="cache",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="defaultcrewconfig",
            name="cache",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pythoncode",
            name="venv",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tables.venv",
            ),
        ),
        migrations.RunPython(create_venvs_for_pythoncode, reverse_create_venvs_for_pythoncode),
    ]
