# Generated by Django 5.1.3 on 2025-08-11 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0102_alter_graphsessionmessage_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentmetadata",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("warning", "Warning"),
                    ("failed", "Failed"),
                ],
                default="new",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="sourcecollection",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("warning", "Warning"),
                    ("failed", "Failed"),
                ],
                default="new",
                max_length=20,
            ),
        ),
    ]
