# Generated by Django 5.1.3 on 2025-08-11 08:14

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0103_alter_documentmetadata_and_sourcecollection_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="distance_threshold",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0.7,
                help_text="Float between 0.00 and 1.00 for knowledge",
                max_digits=3,
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="search_limit",
            field=models.PositiveIntegerField(
                blank=True,
                default=3,
                help_text="Integer between 0 and 1000 for knowledge",
            ),
        ),
        migrations.AddField(
            model_name="crew",
            name="distance_threshold",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0.7,
                help_text="Float between 0.00 and 1.00 for knowledge",
                max_digits=3,
            ),
        ),
        migrations.AddField(
            model_name="crew",
            name="search_limit",
            field=models.PositiveIntegerField(
                blank=True,
                default=3,
                help_text="Integer between 0 and 1000 for knowledge",
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="graph_schema",
            field=models.JSONField(
                default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder
            ),
        ),
    ]
