# Generated by Django 5.1.3 on 2025-08-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0104_agent_distance_threshold_agent_search_limit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sourcecollection",
            name="collection_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddConstraint(
            model_name="sourcecollection",
            constraint=models.UniqueConstraint(
                fields=("user_id", "collection_name"),
                name="unique_collection_name_per_user",
            ),
        ),
    ]
