# Generated by Django 5.1.3 on 2025-08-18 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0105_add_sourcecollection_unique_name_per_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentmetadata",
            name="document_hash",
            field=models.CharField(default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="defaultagentconfig",
            name="cache",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="defaultcrewconfig",
            name="cache",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="documentmetadata",
            name="source_collection",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="document_metadata",
                to="tables.sourcecollection",
            ),
        ),
        migrations.AlterField(
            model_name="documentmetadata",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("chunked", "Chunked"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("warning", "Warning"),
                    ("failed", "Failed"),
                ],
                default="new",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Chunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tables.documentmetadata",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="documentembedding",
            name="chunk_text",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="embeddings_chunk",
                to="tables.chunk",
            ),
        ),
    ]
