# Generated by Django 5.1.3 on 2025-08-21 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0105_add_sourcecollection_unique_name_per_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultagentconfig',
            name='cache',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='defaultcrewconfig',
            name='cache',
            field=models.BooleanField(default=False),
        ),
    ]
