# Generated by Django 5.1.3 on 2025-08-12 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0104_remove_libraries_field"),
        ("tables", "0105_add_sourcecollection_unique_name_per_user"),
    ]

    operations = []
