# Generated by Django 5.1.3 on 2025-08-19 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0106_documentmetadata_document_hash_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="documentembedding",
            old_name="chunk_text",
            new_name="chunk",
        ),
    ]
