# Generated by Django 5.1.3 on 2025-08-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0106_alter_defaultagentconfig_cache_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='distance_threshold',
        ),
        migrations.RemoveField(
            model_name='crew',
            name='distance_threshold',
        ),
        migrations.RemoveField(
            model_name='defaultrealtimeagentconfig',
            name='distance_threshold',
        ),
        migrations.RemoveField(
            model_name='realtimeagent',
            name='distance_threshold',
        ),
        migrations.RemoveField(
            model_name='realtimeagentchat',
            name='distance_threshold',
        ),
        migrations.AddField(
            model_name='agent',
            name='similarity_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.2, help_text='Float between 0.00 and 1.00 for knowledge', max_digits=3),
        ),
        migrations.AddField(
            model_name='crew',
            name='similarity_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.2, help_text='Float between 0.00 and 1.00 for knowledge', max_digits=3),
        ),
        migrations.AddField(
            model_name='defaultrealtimeagentconfig',
            name='similarity_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.2, help_text='Float between 0.00 and 1.00 for knowledge', max_digits=3),
        ),
        migrations.AddField(
            model_name='realtimeagent',
            name='similarity_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.2, help_text='Float between 0.00 and 1.00 for knowledge', max_digits=3),
        ),
        migrations.AddField(
            model_name='realtimeagentchat',
            name='similarity_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.2, help_text='Float between 0.00 and 1.00 for knowledge', max_digits=3),
        ),
    ]
