# Generated by Django 5.1.3 on 2025-09-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0107_remove_agent_distance_threshold_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="realtimeconfig",
            name="api_key",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="realtimetranscriptionconfig",
            name="api_key",
            field=models.TextField(blank=True, null=True),
        ),
    ]
