# Generated by Django 5.1.3 on 2025-09-02 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0107_remove_agent_distance_threshold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='graph',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tables.graph'),
        ),
    ]
