# Generated by Django 5.1.3 on 2025-08-27 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0107_remove_agent_distance_threshold_and_more"),
        ("tables", "0108_set_chunk_fk_on_delete_set_null"),
    ]

    operations = []
