# Generated by Django 5.1.3 on 2025-09-09 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0108_alter_session_graph'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_map', models.JSONField()),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_node', to='tables.graph')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('graph',), name='unique_graph_end_node')],
            },
        ),
    ]
