# Generated by Django 5.1.3 on 2025-09-12 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0108_alter_session_graph"),
    ]

    operations = [
        # Используем существующую таблицу, не управляем Django
        migrations.CreateModel(
            name="AgentConfiguredTools",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "tables_agent_configured_tools",
                "managed": False,  # Не создавать/не менять таблицу
            },
        ),
        migrations.CreateModel(
            name="AgentPythonCodeTools",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tables.agent"
                    ),
                ),
                (
                    "pythoncodetool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tables.pythoncodetool",
                    ),
                ),
            ],
            options={
                "db_table": "tables_agent_python_code_tools",
                "unique_together": {("agent", "pythoncodetool")},
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="McpTool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transport",
                    models.URLField(
                        help_text="URL of the remote MCP server (SSE). Required.",
                        max_length=2048,
                    ),
                ),
                (
                    "tool_name",
                    models.CharField(help_text="Name of the MCP tool.", max_length=255),
                ),
                (
                    "timeout",
                    models.FloatField(
                        default=30,
                        help_text="Request timeout in seconds. Recommended to set.",
                    ),
                ),
                (
                    "auth",
                    models.TextField(
                        blank=True,
                        help_text="Authorization token or OAuth string, if the server requires it.",
                        null=True,
                    ),
                ),
                (
                    "init_timeout",
                    models.FloatField(
                        default=10,
                        help_text="Timeout for session initialization. Optional, default is 10 seconds.",
                    ),
                ),
            ],
            options={
                "verbose_name": "MCP Tool Data",
                "verbose_name_plural": "MCP Tool Data",
            },
        ),
        migrations.CreateModel(
            name="AgentMcpTools",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tables.agent"
                    ),
                ),
                (
                    "mcptool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tables.mcptool"
                    ),
                ),
            ],
            options={
                "db_table": "tables_agent_mcp_tools",
                "unique_together": {("agent", "mcptool")},
            },
        ),
        migrations.AddField(
            model_name="agent",
            name="mcp_tools",
            field=models.ManyToManyField(
                blank=True,
                related_name="agents",
                through="tables.AgentMcpTools",
                to="tables.mcptool",
            ),
        ),
        migrations.CreateModel(
            name="TaskMcpTools",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tables.task"
                    ),
                ),
                (
                    "tool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tables.mcptool"
                    ),
                ),
            ],
            options={
                "db_table": "tables_task_mcp_tools",
                "unique_together": {("task", "tool")},
            },
        ),
        migrations.AlterModelOptions(
            name="agentmcptools",
            options={"managed": False},
        ),
        migrations.AlterField(
            model_name="agent",
            name="configured_tools",
            field=models.ManyToManyField(
                blank=True,
                related_name="agents",
                through="tables.AgentConfiguredTools",
                to="tables.toolconfig",
            ),
        ),
        migrations.AlterField(
            model_name="agent",
            name="python_code_tools",
            field=models.ManyToManyField(
                blank=True,
                related_name="agents",
                through="tables.AgentPythonCodeTools",
                to="tables.pythoncodetool",
            ),
        ),
    ]
