# Generated by Django 5.1.3 on 2025-09-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0109_agentconfiguredtools_agentmcptools_mcptool_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mcptool",
            name="transport",
            field=models.CharField(
                help_text="URL of the remote MCP server (SSE). Required.",
                max_length=2048,
            ),
        ),
    ]
