# Generated by Django 5.1.3 on 2025-09-16 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0110_alter_mcptool_transport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskmcptools",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_mcp_tool_list",
                to="tables.task",
            ),
        ),
    ]
