# Generated by Django 5.1.3 on 2025-09-19 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0108_alter_realtimeconfig_api_key_and_more"),
        ("tables", "0110_fileextractornode"),
    ]

    operations = []
