# Generated by Django 5.1.3 on 2025-09-19 10:49

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0110_fileextractornode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tool",
            name="enabled",
            field=models.BooleanField(default=False),
        )
    ]
