# Generated by Django 5.1.3 on 2025-09-22 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0111_alter_tool_enabled"),
        ("tables", "0111_merge_20250919_1036"),
    ]

    operations = []
