# Generated by Django 5.1.3 on 2025-09-24 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0109_mcptool_remove_agent_configured_tools_and_more"),
        ("tables", "0112_merge_20250922_1355"),
    ]

    operations = []
