# Generated by Django 5.1.3 on 2025-09-25 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0113_merge_20250924_1501"),
    ]

    operations = [
        migrations.AddField(
            model_name="mcptool",
            name="name",
            field=models.CharField(
                default="Test",
                help_text="Unique name for mcp configuration",
                max_length=255,
                unique=True,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="agentconfiguredtools",
            name="agent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="configured_tools",
                to="tables.agent",
            ),
        ),
        migrations.AlterField(
            model_name="agentpythoncodetools",
            name="agent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="python_code_tools",
                to="tables.agent",
            ),
        ),
    ]
