# Generated by Django 5.1.3 on 2025-10-14 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0114_mcptool_name_alter_agentconfiguredtools_agent_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, unique=True)),
                (
                    "secret_key",
                    models.CharField(
                        help_text="A hashed unique key for organization",
                        max_length=512,
                        unique=True,
                    ),
                ),
                (
                    "variables",
                    models.JSONField(
                        default=dict, help_text="Organization global variables"
                    ),
                ),
            ],
            bases=(models.Model,),
        ),
        migrations.AddField(
            model_name="session",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tables.organization",
            ),
        ),
        migrations.CreateModel(
            name="OrganizationUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=256, unique=True)),
                (
                    "secret_key",
                    models.CharField(
                        help_text="A hashed unique key for user inside an organization",
                        max_length=512,
                        unique=True,
                    ),
                ),
                (
                    "variables",
                    models.JSONField(default=dict, help_text="User scope variables"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tables.organization",
                    ),
                ),
            ],
            bases=(models.Model,),
        ),
        migrations.AddField(
            model_name="session",
            name="organization_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tables.organizationuser",
            ),
        ),
        migrations.AddConstraint(
            model_name="organizationuser",
            constraint=models.UniqueConstraint(
                fields=("username", "organization"),
                name="unique_flow_user_for_organization",
            ),
        ),
    ]
