# Generated by Django 5.1.3 on 2025-10-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0114_mcptool_name_alter_agentconfiguredtools_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='knowledge_query',
            field=models.TextField(blank=True, null=True),
        ),
    ]
