# Generated by Django 5.1.3 on 2025-10-08 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0114_mcptool_name_alter_agentconfiguredtools_agent_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GraphFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain_key",
                    models.CharField(
                        help_text="Key to access file from domain", max_length=100
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Original filename", max_length=255),
                ),
                (
                    "content_type",
                    models.CharField(help_text="MIME type", max_length=100),
                ),
                ("size", models.PositiveIntegerField(help_text="File size in bytes")),
                ("file", models.FileField(upload_to="uploads/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "graph",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_files",
                        to="tables.graph",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("graph", "domain_key"), name="unique_file_key_per_graph"
                    )
                ],
            },
        ),
    ]
