# Generated by Django 5.1.3 on 2025-10-22 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0114_mcptool_name_alter_agentconfiguredtools_agent_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="decisiontablenode",
            name="input_map",
        ),
        migrations.RemoveField(
            model_name="decisiontablenode",
            name="output_variable_path",
        ),
    ]
