# Generated by Django 5.1.3 on 2025-10-21 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0115_remove_documentembedding_chunk_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentembedding",
            name="chunk",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="embeddings_chunk",
                to="tables.chunk",
            ),
        ),
        migrations.AddField(
            model_name="sourcecollection",
            name="is_draft",
            field=models.BooleanField(default=False),
        ),
    ]
