# Generated by Django 5.1.3 on 2025-10-20 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0115_remove_documentembedding_chunk_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentembedding",
            name="chunk",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="embeddings_chunk",
                to="tables.chunk",
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("run", "Run"),
                    ("wait_for_user", "Wait For User"),
                    ("error", "Error"),
                    ("end", "End"),
                    ("stop", "Stop"),
                    ("expired", "Expired"),
                ],
                max_length=255,
            ),
        ),
    ]
