# Generated by Django 5.1.3 on 2025-10-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0115_organization_session_organization_organizationuser_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="persistent_variables",
            field=models.BooleanField(
                default=False,
                help_text="If 'True' -> variables will be updated after each session.",
            ),
        ),
        migrations.AddField(
            model_name="organizationuser",
            name="persistent_variables",
            field=models.BooleanField(
                default=False,
                help_text="If 'True' -> variables will be updated after each session.",
            ),
        ),
    ]
