# Generated by Django 5.1.3 on 2025-10-22 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0115_task_knowledge_query'),
        ('tables', '0116_organization_persistent_variables_and_more'),
    ]

    operations = [
    ]
