# Generated by Django 5.1.3 on 2025-10-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0116_organization_persistent_variables_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pythoncodetool",
            name="built_in",
            field=models.BooleanField(default=False),
        ),
    ]
