# Generated by Django 5.1.3 on 2025-10-27 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0116_organization_persistent_variables_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="embeddingmodel",
            name="is_custom",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="llmmodel",
            name="is_custom",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="realtimemodel",
            name="is_custom",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="realtimetranscriptionmodel",
            name="is_custom",
            field=models.BooleanField(default=False),
        ),
    ]
