# Generated by Django 5.1.3 on 2025-10-21 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0116_organization_persistent_variables_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GraphOrganization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "persistent_variables",
                    models.JSONField(
                        default=dict,
                        help_text="Variables that persistent for specific entity for specific flow",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GraphOrganizationUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "persistent_variables",
                    models.JSONField(
                        default=dict,
                        help_text="Variables that persistent for specific entity for specific flow",
                    ),
                ),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="organizationuser",
            name="unique_flow_user_for_organization",
        ),
        migrations.RenameField(
            model_name="organizationuser",
            old_name="username",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="persistent_variables",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="secret_key",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="variables",
        ),
        migrations.RemoveField(
            model_name="organizationuser",
            name="persistent_variables",
        ),
        migrations.RemoveField(
            model_name="organizationuser",
            name="secret_key",
        ),
        migrations.RemoveField(
            model_name="organizationuser",
            name="variables",
        ),
        migrations.RemoveField(
            model_name="session",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="session",
            name="organization_user",
        ),
        migrations.AddConstraint(
            model_name="organizationuser",
            constraint=models.UniqueConstraint(
                fields=("name", "organization"),
                name="unique_flow_user_for_organization",
            ),
        ),
        migrations.AddField(
            model_name="graphorganization",
            name="graph",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tables.graph"
            ),
        ),
        migrations.AddField(
            model_name="graphorganization",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="graph",
                to="tables.organization",
            ),
        ),
        migrations.AddField(
            model_name="graphorganizationuser",
            name="graph",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tables.graph"
            ),
        ),
        migrations.AddField(
            model_name="graphorganizationuser",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="graph",
                to="tables.organizationuser",
            ),
        ),
        migrations.AddConstraint(
            model_name="graphorganization",
            constraint=models.UniqueConstraint(
                fields=("graph", "organization"), name="unique_organization_per_flow"
            ),
        ),
        migrations.AddConstraint(
            model_name="graphorganizationuser",
            constraint=models.UniqueConstraint(
                fields=("graph", "user"), name="unique_user_per_flow"
            ),
        ),
    ]
