# Generated by Django 5.1.3 on 2025-10-21 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0117_graphorganization_graphorganizationuser_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="graphorganization",
            name="user_variables",
            field=models.JSONField(
                default=dict,
                help_text="Variables that persistent for all users for specific flow",
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="graph_user",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tables.graphorganizationuser",
            ),
        ),
    ]
