# Generated by Django 5.1.3 on 2025-10-27 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0116_documentembedding_chunk_alter_session_status"),
        ("tables", "0117_merge_20251022_1310"),
    ]

    operations = []
