# Generated by Django 5.1.3 on 2025-10-28 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0117_embeddingmodel_is_custom_llmmodel_is_custom_and_more"),
        ("tables", "0118_merge_20251027_1034"),
    ]

    operations = []
