# Generated by Django 5.1.3 on 2025-11-06 19:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0119_merge_20251028_1126"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookTrigger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Path may only contain letters, numbers, hyphens, and underscores, and must start with a letter or number.",
                                regex="^[a-zA-Z0-9]{1}[a-zA-Z0-9-_]*$",
                            )
                        ],
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="session",
            name="entrypoint",
            field=models.CharField(default=None, null=True),
        ),
        migrations.CreateModel(
            name="WebhookTriggerNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("node_name", models.CharField(max_length=255, unique=True)),
                (
                    "graph",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tables.graph"
                    ),
                ),
                (
                    "python_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tables.pythoncode",
                    ),
                ),
                (
                    "webhook_trigger",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="webhook_trigger_nodes",
                        to="tables.webhooktrigger",
                    ),
                ),
            ],
        ),
    ]
