# Generated by Django 5.1.3 on 2025-10-29 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0117_pythoncodetool_built_in"),
        ("tables", "0119_merge_20251028_1126"),
    ]

    operations = []
