# Generated by Django 5.1.3 on 2025-10-29 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0118_graphorganization_user_variables_session_graph_user"),
        ("tables", "0120_merge_20251029_1254"),
    ]

    operations = []
