# Generated by Django 5.1.3 on 2025-10-29 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0116_audiotranscriptionnode"),
        ("tables", "0120_merge_20251029_1254"),
    ]

    operations = []
