# Generated by Django 5.1.3 on 2025-10-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0121_merge_20251029_1556"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationuser",
            name="name",
            field=models.CharField(max_length=256),
        ),
    ]
