# Generated by Django 5.1.3 on 2025-11-05 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0115_remove_decisiontablenode_input_map_and_more"),
        ("tables", "0122_alter_organizationuser_name"),
    ]

    operations = []
