# Generated by Django 5.1.3 on 2025-10-30 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0121_subgraphnode"),
        ("tables", "0122_alter_organizationuser_name"),
    ]

    operations = []
