# Generated by Django 5.1.3 on 2025-10-31 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0121_merge_20251029_1725"),
        ("tables", "0122_alter_organizationuser_name"),
    ]

    operations = []
