# Generated by Django 5.1.3 on 2025-11-11 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0120_webhooktrigger_session_entrypoint_webhooktriggernode"),
        ("tables", "0123_merge_20251105_1126"),
    ]

    operations = []
