# Generated by Django 5.1.3 on 2025-11-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0123_merge_20251105_1126"),
    ]

    operations = [
        migrations.AddField(
            model_name="crew",
            name="is_template",
            field=models.BooleanField(default=False),
        ),
    ]
