# Generated by Django 5.1.3 on 2025-11-09 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0123_merge_20251105_1126"),
    ]

    operations = [
        migrations.CreateModel(
            name="BM25Index",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index_data", models.BinaryField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "collection",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bm25_index",
                        to="tables.sourcecollection",
                    ),
                ),
            ],
        ),
    ]
