# Generated by Django 5.1.3 on 2025-11-10 12:42
from django.db import migrations, models
from django.db import transaction
from tables.utils.helpers import generate_new_unique_name


def create_crew_copy(apps, crew, crew_names):
    """Create a copy of the given crew along with its tasks and task contexts."""
    TaskContext = apps.get_model("tables", "TaskContext")
    Task = apps.get_model("tables", "Task")
    Crew = apps.get_model("tables", "Crew")
    TaskConfiguredTools = apps.get_model("tables", "TaskConfiguredTools")
    TaskPythonCodeTools = apps.get_model("tables", "TaskPythonCodeTools")
    TaskMcpTools = apps.get_model("tables", "TaskMcpTools")

    agent_ids = list(crew.agents.values_list("id", flat=True))
    tag_ids = list(crew.tags.values_list("id", flat=True))
    original_tasks = list(crew.task_set.all())

    new_crew = Crew(
        metadata=crew.metadata,
        description=crew.description,
        name=generate_new_unique_name(crew.name, crew_names),
        process=crew.process,
        memory=crew.memory,
        memory_llm_config=crew.memory_llm_config,
        embedding_config=crew.embedding_config,
        manager_llm_config=crew.manager_llm_config,
        config=crew.config,
        max_rpm=crew.max_rpm,
        cache=crew.cache,
        full_output=crew.full_output,
        planning=crew.planning,
        planning_llm_config=crew.planning_llm_config,
        default_temperature=crew.default_temperature,
        knowledge_collection=crew.knowledge_collection,
        search_limit=crew.search_limit,
        similarity_threshold=crew.similarity_threshold,
        is_template=False,
    )
    new_crew.save()

    if agent_ids:
        new_crew.agents.set(agent_ids)
    if tag_ids:
        new_crew.tags.set(tag_ids)

    task_mapping = {}
    for task in original_tasks:
        configured_tool_ids = list(
            task.task_configured_tool_list.values_list("tool_id", flat=True)
        )
        python_code_tool_ids = list(
            task.task_python_code_tool_list.values_list("tool_id", flat=True)
        )
        mcp_tool_ids = list(task.task_mcp_tool_list.values_list("tool_id", flat=True))

        original_task_id = task.id

        new_task = Task(
            crew=new_crew,
            name=task.name,
            agent=task.agent,
            instructions=task.instructions,
            knowledge_query=task.knowledge_query,
            expected_output=task.expected_output,
            order=task.order,
            human_input=task.human_input,
            async_execution=task.async_execution,
            config=task.config,
            output_model=task.output_model,
        )
        new_task.save()

        for tool_id in configured_tool_ids:
            TaskConfiguredTools.objects.create(task=new_task, tool_id=tool_id)

        for tool_id in python_code_tool_ids:
            TaskPythonCodeTools.objects.create(task=new_task, tool_id=tool_id)

        for tool_id in mcp_tool_ids:
            TaskMcpTools.objects.create(task=new_task, tool_id=tool_id)

        task_mapping[original_task_id] = new_task.id

    for old_task in original_tasks:
        for old_context in old_task.task_context_list.all():
            new_task_id = task_mapping.get(old_context.task_id)
            new_context_id = task_mapping.get(old_context.context_id)

            if not new_task_id or not new_context_id:
                continue

            TaskContext.objects.create(
                task_id=new_task_id,
                context_id=new_context_id,
            )

    return new_crew


def update_node_metadata(new_crew, old_crew, graph_id, Graph):
    """Update the metadata of the graph to reflect the new crew ID and name."""
    graph = Graph.objects.get(id=graph_id)
    metadata = graph.metadata
    updated = False

    for node in metadata.get("nodes", []):
        if (
            node.get("type") == "project"
            and node.get("data", {}).get("id") == old_crew.id
        ):
            node["data"]["id"] = new_crew.id
            node["data"]["name"] = new_crew.name
            node["data"]["tasks"] = list(new_crew.task_set.values_list("id", flat=True))
            updated = True

    if updated:
        graph.metadata = metadata
        graph.save()


def make_all_crews_as_templates(apps, schema_editor):
    """Set is_template=True for all existing crews and update related CrewNodes."""
    with transaction.atomic():
        Crew = apps.get_model("tables", "Crew")
        Crew.objects.all().update(is_template=True)

        CrewNode = apps.get_model("tables", "CrewNode")
        Graph = apps.get_model("tables", "Graph")

        nodes = CrewNode.objects.all().select_related("crew")
        crew_names = set(Crew.objects.values_list("name", flat=True))

        for node in nodes:
            old_crew = node.crew
            new_crew = create_crew_copy(apps, old_crew, crew_names)
            node.crew_id = new_crew.id
            node.save()

            update_node_metadata(new_crew, old_crew, node.graph_id, Graph)


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0123_merge_20251105_1126"),
    ]

    operations = [
        migrations.AddField(
            model_name="crew",
            name="is_template",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            make_all_crews_as_templates, reverse_code=migrations.RunPython.noop
        ),
    ]
