# Generated by Django 5.1.3 on 2025-11-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0124_merge_20251111_1234"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webhooktriggernode",
            name="node_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name="webhooktriggernode",
            constraint=models.UniqueConstraint(
                fields=("graph", "node_name"),
                name="unique_graph_node_name_for_webhook_nodes",
            ),
        ),
    ]
