# Generated by Django 5.1.3 on 2025-11-13 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0124_crew_is_template"),
        ("tables", "0125_alter_webhooktriggernode_node_name_and_more"),
    ]

    operations = []
