# Generated by Django 5.1.3 on 2025-11-19 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0125_alter_webhooktriggernode_node_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webhooktriggernode",
            name="graph",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="webhook_trigger_node_list",
                to="tables.graph",
            ),
        ),
    ]
