# Generated by Django 5.1.3 on 2025-11-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0126_alter_webhooktriggernode_graph"),
    ]

    operations = [
        migrations.AddField(
            model_name="sourcecollection",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
