# Generated by Django 5.1.3 on 2025-11-28 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0126_alter_webhooktriggernode_graph"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            ALTER TABLE tables_graphsessionmessage 
            DROP CONSTRAINT IF EXISTS tables_graphsessionm_session_id_f9dff386_fk_tables_se;

            -- Create a new constraint with native ON DELETE CASCADE
            ALTER TABLE tables_graphsessionmessage 
            ADD CONSTRAINT tables_graphsessionm_session_id_f9dff386_fk_tables_se 
            FOREIGN KEY (session_id) 
            REFERENCES tables_session(id) 
            ON DELETE CASCADE;
            """,
            reverse_sql="""
            -- Revert to the standard constraint (NO ACTION/RESTRICT) if migration is unapplied
            ALTER TABLE tables_graphsessionmessage 
            DROP CONSTRAINT IF EXISTS tables_graphsessionm_session_id_f9dff386_fk_tables_se;

            ALTER TABLE tables_graphsessionmessage 
            ADD CONSTRAINT tables_graphsessionm_session_id_f9dff386_fk_tables_se 
            FOREIGN KEY (session_id) 
            REFERENCES tables_session(id) 
            DEFERRABLE INITIALLY DEFERRED;
            """
        )
    ]
