# Generated by Django 5.1.3 on 2025-12-12 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("tables", "0128_webscraperknowledgenode"),
        ("tables", "0129_webscraperknowledgenode_collection_name_and_more"),
    ]

    dependencies = [
        ("tables", "0127_sourcecollection_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebScraperKnowledgeNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("node_name", models.CharField(blank=True, max_length=255)),
                ("input_map", models.JSONField(default=dict)),
                (
                    "output_variable_path",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "graph",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="web_scraper_knowledge_node_list",
                        to="tables.graph",
                    ),
                ),
                (
                    "collection_name",
                    models.CharField(default="default_collection", max_length=255),
                ),
                ("embedder", models.IntegerField(default=1)),
                ("time_to_expired", models.IntegerField(default=-1)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("graph", "node_name"),
                        name="unique_graph_node_name_for_web_scraper_knowledge_node",
                    )
                ],
            },
        ),
    ]
