# Generated by Django 5.1.3 on 2025-12-04 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0126_merge_20251113_1040"),
        ("tables", "0127_fix_graphsessionmessage_cascade"),
    ]

    operations = []
