# Generated by Django 5.1.3 on 2025-12-15 18:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0127_fix_graphsessionmessage_cascade"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramTriggerNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("node_name", models.CharField(max_length=255)),
                (
                    "telegram_bot_api_key",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "url_path",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "graph",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telegram_trigger_node_list",
                        to="tables.graph",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TelegramTriggerNodeField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parent", models.CharField(max_length=50)),
                ("field_name", models.CharField(max_length=255)),
                ("variable_path", models.CharField(max_length=255)),
                (
                    "telegram_trigger_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="tables.telegramtriggernode",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="telegramtriggernode",
            constraint=models.UniqueConstraint(
                fields=("graph", "node_name"),
                name="unique_graph_node_name_for_telegram_trigger_nodes",
            ),
        ),
        migrations.AddConstraint(
            model_name="telegramtriggernodefield",
            constraint=models.UniqueConstraint(
                fields=("telegram_trigger_node", "field_name", "parent"),
                name="unique_telegram_trigger_node_field_name_parent",
            ),
        ),
    ]
