# Generated by Django 5.1.3 on 2025-12-29 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0123_merge_20251031_1745"),
        ("tables", "0128_pythoncodetoolconfig_agentpythoncodetoolconfigs_and_more"),
    ]

    operations = []
