# Generated by Django 5.1.3 on 2026-01-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0129_merge_20251229_1542"),
    ]

    operations = [
        migrations.AddField(
            model_name="realtimeagentchat",
            name="input_audio_format",
            field=models.CharField(
                choices=[
                    ("pcm16", "PCM 16-bit"),
                    ("g711_ulaw", "G.711 u-law"),
                    ("g711_alaw", "G.711 a-law"),
                ],
                default="pcm16",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="realtimeagentchat",
            name="output_audio_format",
            field=models.CharField(
                choices=[
                    ("pcm16", "PCM 16-bit"),
                    ("g711_ulaw", "G.711 u-law"),
                    ("g711_alaw", "G.711 a-law"),
                ],
                default="pcm16",
                max_length=20,
            ),
        ),
    ]
