# Generated by Django 5.1.3 on 2026-01-06 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0126_merge_20251113_1040"),
        ("tables", "0129_merge_20251229_1542"),
    ]

    operations = []
