# Generated by Django 5.1.3 on 2026-01-08 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0129_merge_20251229_1542"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="defaultllmconfig",
            name="api_version",
        ),
        migrations.RemoveField(
            model_name="defaultllmconfig",
            name="base_url",
        ),
        migrations.RemoveField(
            model_name="defaultllmconfig",
            name="logprobs",
        ),
        migrations.RemoveField(
            model_name="defaultllmconfig",
            name="top_logprobs",
        ),
        migrations.RemoveField(
            model_name="llmconfig",
            name="api_version",
        ),
        migrations.RemoveField(
            model_name="llmconfig",
            name="base_url",
        ),
        migrations.RemoveField(
            model_name="llmconfig",
            name="logprobs",
        ),
        migrations.RemoveField(
            model_name="llmconfig",
            name="top_logprobs",
        ),
        migrations.RemoveField(
            model_name="llmmodel",
            name="deployment",
        ),
        migrations.AddField(
            model_name="defaultllmconfig",
            name="extra_headers",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="defaultllmconfig",
            name="headers",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="llmconfig",
            name="extra_headers",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="llmconfig",
            name="headers",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="llmmodel",
            name="api_version",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="llmmodel",
            name="deployment_id",
            field=models.TextField(
                blank=True, help_text="Azure Deployment Name или Watsonx ID", null=True
            ),
        ),
    ]
