# Generated by Django 5.1.3 on 2025-12-05 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0127_fix_graphsessionmessage_cascade"),
        ("tables", "0129_webscraperknowledgenode_collection_name_and_more"),
    ]

    operations = []
