# Generated by Django 5.1.3 on 2025-12-04 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0129_remove_documentcontent_document_metadata_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agent",
            name="search_limit",
        ),
        migrations.RemoveField(
            model_name="agent",
            name="similarity_threshold",
        ),
        migrations.RemoveField(
            model_name="baseragtype",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="baseragtype",
            name="error_message",
        ),
        migrations.RemoveField(
            model_name="baseragtype",
            name="processed_at",
        ),
        migrations.RemoveField(
            model_name="baseragtype",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="crew",
            name="knowledge_collection",
        ),
        migrations.RemoveField(
            model_name="crew",
            name="search_limit",
        ),
        migrations.RemoveField(
            model_name="crew",
            name="similarity_threshold",
        ),
        migrations.AddField(
            model_name="naiverag",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="naiverag",
            name="indexed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="AgentNaiveRag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_naive_rags",
                        to="tables.agent",
                        unique=True,
                    ),
                ),
                (
                    "naive_rag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_links",
                        to="tables.naiverag",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="naiverag",
            name="agents",
            field=models.ManyToManyField(
                blank=True,
                help_text="Agents that have access to this NaiveRag",
                related_name="naive_rags",
                through="tables.AgentNaiveRag",
                to="tables.agent",
            ),
        ),
        migrations.CreateModel(
            name="NaiveRagSearchConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "search_limit",
                    models.PositiveIntegerField(
                        blank=True,
                        default=3,
                        help_text="Integer between 0 and 1000 for knowledge",
                    ),
                ),
                (
                    "similarity_threshold",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.2,
                        help_text="Float between 0.00 and 1.00 for knowledge",
                        max_digits=3,
                    ),
                ),
                (
                    "agent",
                    models.OneToOneField(
                        help_text="Agent this search configuration belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="naive_search_config",
                        to="tables.agent",
                    ),
                ),
            ],
        ),
    ]
