# Generated by Django 5.1.3 on 2026-01-05 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0128_telegramtriggernode_telegramtriggernodefield_and_more"),
        ("tables", "0129_merge_20251229_1542"),
    ]

    operations = []
