# Generated by Django 5.1.3 on 2025-12-04 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0130_remove_agent_search_limit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="crew",
            name="knowledge_collection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tables.sourcecollection",
            ),
        ),
        migrations.AddField(
            model_name="crew",
            name="search_limit",
            field=models.PositiveIntegerField(
                blank=True,
                default=3,
                help_text="Integer between 0 and 1000 for knowledge",
            ),
        ),
        migrations.AddField(
            model_name="crew",
            name="similarity_threshold",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0.2,
                help_text="Float between 0.00 and 1.00 for knowledge",
                max_digits=3,
            ),
        ),
    ]
