# Generated by Django 5.1.3 on 2025-12-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("tables", "0131_alter_webscraperknowledgenode_time_to_expired"),
        ("tables", "0132_alter_webscraperknowledgenode_time_to_expired"),
    ]

    dependencies = [
        ("tables", "0130_merge_20251205_1318"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webscraperknowledgenode",
            name="time_to_expired",
            field=models.IntegerField(blank=True, default=-1),
        ),
    ]
