# Generated by Django 5.1.3 on 2025-12-17 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0131_crew_knowledge_collection_crew_search_limit_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="crew",
            name="knowledge_collection",
        ),
        migrations.RemoveField(
            model_name="crew",
            name="search_limit",
        ),
        migrations.RemoveField(
            model_name="crew",
            name="similarity_threshold",
        ),
        migrations.RemoveField(
            model_name="defaultrealtimeagentconfig",
            name="search_limit",
        ),
        migrations.RemoveField(
            model_name="defaultrealtimeagentconfig",
            name="similarity_threshold",
        ),
        migrations.RemoveField(
            model_name="realtimeagent",
            name="search_limit",
        ),
        migrations.RemoveField(
            model_name="realtimeagent",
            name="similarity_threshold",
        ),
        migrations.RemoveField(
            model_name="realtimeagentchat",
            name="search_limit",
        ),
        migrations.RemoveField(
            model_name="realtimeagentchat",
            name="similarity_threshold",
        ),
    ]
