# Generated by Django 5.1.3 on 2026-01-19 16:03

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0131_prepare_knowledge_refactor"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseRagType",
            fields=[
                ("rag_type_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "rag_type",
                    models.CharField(
                        choices=[("naive", "Naive"), ("graph", "Graph")], max_length=30
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DocumentContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.BinaryField(help_text="Binary file content (max 12MB)"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AgentNaiveRag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_naive_rags",
                        to="tables.agent",
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DocumentMetadata",
            fields=[
                ("document_id", models.AutoField(primary_key=True, serialize=False)),
                ("file_name", models.CharField(blank=True, max_length=255)),
                (
                    "file_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pdf", "Pdf"),
                            ("csv", "Csv"),
                            ("docx", "Docx"),
                            ("txt", "Txt"),
                            ("json", "Json"),
                            ("html", "Html"),
                            ("md", "Md"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(help_text="Size in bytes", null=True),
                ),
                (
                    "document_content",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metadata_records",
                        to="tables.documentcontent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NaiveRag",
            fields=[
                ("naive_rag_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "rag_status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("warning", "Warning"),
                            ("failed", "Failed"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("indexed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "agents",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Agents that have access to this NaiveRag",
                        related_name="naive_rags",
                        through="tables.AgentNaiveRag",
                        to="tables.agent",
                    ),
                ),
                (
                    "base_rag_type",
                    models.ForeignKey(
                        limit_choices_to={"rag_type": "naive"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="naive_rags",
                        to="tables.baseragtype",
                    ),
                ),
                (
                    "embedder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tables.embeddingconfig",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="agentnaiverag",
            name="naive_rag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agent_links",
                to="tables.naiverag",
            ),
        ),
        migrations.CreateModel(
            name="NaiveRagDocumentConfig",
            fields=[
                (
                    "naive_rag_document_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "chunk_strategy",
                    models.CharField(
                        choices=[
                            ("token", "Token"),
                            ("character", "Character"),
                            ("markdown", "Markdown"),
                            ("json", "Json"),
                            ("html", "Html"),
                            ("csv", "Csv"),
                        ],
                        default="token",
                        max_length=20,
                    ),
                ),
                (
                    "chunk_size",
                    models.PositiveIntegerField(
                        default=1000,
                        help_text="Size of each chunk (tokens or characters)",
                    ),
                ),
                (
                    "chunk_overlap",
                    models.PositiveIntegerField(
                        default=150, help_text="Overlap between consecutive chunks"
                    ),
                ),
                (
                    "additional_params",
                    models.JSONField(
                        default=dict,
                        help_text="Strategy-specific params (e.g., separators, headers)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("chunked", "Chunked"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("warning", "Warning"),
                            ("failed", "Failed"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="naive_rag_document_config",
                        to="tables.documentmetadata",
                    ),
                ),
                (
                    "naive_rag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="naive_rag_configs",
                        to="tables.naiverag",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NaiveRagChunk",
            fields=[
                ("chunk_id", models.AutoField(primary_key=True, serialize=False)),
                ("text", models.TextField()),
                (
                    "chunk_index",
                    models.PositiveIntegerField(
                        help_text="Order of this chunk in the document"
                    ),
                ),
                ("token_count", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "metadata",
                    models.JSONField(
                        default=dict,
                        help_text="Chunk-specific metadata (page numbers, sections, etc.)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "naive_rag_document_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="tables.naiveragdocumentconfig",
                    ),
                ),
            ],
            options={
                "ordering": ["chunk_index"],
            },
        ),
        migrations.CreateModel(
            name="NaiveRagEmbedding",
            fields=[
                (
                    "embedding_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("vector", pgvector.django.vector.VectorField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chunk",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embedding",
                        to="tables.naiveragchunk",
                    ),
                ),
                (
                    "naive_rag_document_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embeddings",
                        to="tables.naiveragdocumentconfig",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NaiveRagSearchConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "search_limit",
                    models.PositiveIntegerField(
                        blank=True,
                        default=3,
                        help_text="Integer between 0 and 1000 for knowledge",
                    ),
                ),
                (
                    "similarity_threshold",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.2,
                        help_text="Float between 0.00 and 1.00 for knowledge",
                        max_digits=3,
                    ),
                ),
                (
                    "agent",
                    models.OneToOneField(
                        help_text="Agent this search configuration belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="naive_search_config",
                        to="tables.agent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SourceCollection",
            fields=[
                ("collection_id", models.AutoField(primary_key=True, serialize=False)),
                ("collection_name", models.CharField(blank=True, max_length=255)),
                (
                    "collection_origin",
                    models.CharField(
                        choices=[("user", "User"), ("node", "Node"), ("tool", "Tool")],
                        default="user",
                        max_length=20,
                    ),
                ),
                (
                    "user_id",
                    models.CharField(blank=True, default="dummy_user", max_length=120),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("empty", "Empty"),
                            ("uploading", "Uploading"),
                            ("completed", "Completed"),
                            ("warning", "Warning"),
                        ],
                        default="empty",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user_id", "collection_name"),
                        name="unique_collection_name_per_user",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="documentmetadata",
            name="source_collection",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="tables.sourcecollection",
            ),
        ),
        migrations.AddField(
            model_name="baseragtype",
            name="source_collection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rag_types",
                to="tables.sourcecollection",
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="knowledge_collection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tables.sourcecollection",
            ),
        ),
        migrations.AddIndex(
            model_name="naiveragdocumentconfig",
            index=models.Index(
                fields=["naive_rag", "status"], name="tables_naiv_naive_r_f3bcf6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="naiveragdocumentconfig",
            index=models.Index(
                fields=["document"], name="tables_naiv_documen_254ff9_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="naiveragdocumentconfig",
            constraint=models.UniqueConstraint(
                fields=("naive_rag", "document"), name="unique_document_per_naive_rag"
            ),
        ),
        migrations.AddIndex(
            model_name="naiveragchunk",
            index=models.Index(
                fields=["naive_rag_document_config", "chunk_index"],
                name="tables_naiv_naive_r_343843_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="naiveragchunk",
            constraint=models.UniqueConstraint(
                fields=("naive_rag_document_config", "chunk_index"),
                name="unique_chunk_index_per_naive_rag_document_config",
            ),
        ),
        migrations.AddIndex(
            model_name="naiveragembedding",
            index=models.Index(
                fields=["naive_rag_document_config"],
                name="tables_naiv_naive_r_e7ad19_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="documentmetadata",
            index=models.Index(
                fields=["source_collection"], name="tables_docu_source__eec4f1_idx"
            ),
        ),
    ]
