# Generated by Django 5.1.3 on 2025-12-08 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0128_pythoncodetoolconfig_agentpythoncodetoolconfigs_and_more"),
        ("tables", "0132_alter_webscraperknowledgenode_time_to_expired"),
    ]

    operations = []
