# Generated by Django 5.1.3 on 2026-01-22 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0130_merge_20260105_1819"),
        ("tables", "0133_restore_knowledge_data"),
    ]

    operations = []
