# Generated by Django 5.1.3 on 2025-12-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0133_merge_20251208_1331"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webscraperknowledgenode",
            name="collection_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="webscraperknowledgenode",
            name="embedder",
            field=models.IntegerField(),
        ),
    ]
