# Generated by Django 5.1.3 on 2026-02-13 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0134_merge_20260122_1025"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="llmconfig",
            name="n",
        ),
    ]
