# Generated by Django 5.1.3 on 2026-01-23 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0129_merge_20251211_1413"),
        ("tables", "0134_merge_20260122_1025"),
    ]

    operations = []
