# Generated by Django 5.1.3 on 2026-01-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0134_merge_20260122_1025"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="token_usage",
            field=models.JSONField(default=dict),
        ),
    ]
