# Generated by Django 5.1.3 on 2026-02-13 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0135_remove_llmconfig_n"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="defaultllmconfig",
            name="max_completion_tokens",
        ),
        migrations.RemoveField(
            model_name="defaultllmconfig",
            name="n",
        ),
        migrations.RemoveField(
            model_name="llmconfig",
            name="max_completion_tokens",
        ),
    ]
