# Generated by Django 5.1.3 on 2026-01-26 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0130_realtimeagentchat_input_audio_format_and_more"),
        ("tables", "0135_session_token_usage"),
    ]

    operations = []
