# Generated by Django 5.1.3 on 2026-02-03 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0136_merge_20260126_1313"),
    ]

    operations = [
        migrations.CreateModel(
            name="NgrokWebhookConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "authtoken",
                    models.CharField(
                        help_text="Token from dashboard.ngrok.com", max_length=255
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        blank=True, help_text="Your domain", max_length=255, null=True
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        choices=[("us", "Us"), ("eu", "Eu"), ("ap", "Ap")],
                        default="eu",
                        max_length=2,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="telegramtriggernode",
            name="webhook_trigger",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="telegram_trigger_nodes",
                to="tables.webhooktrigger",
            ),
        ),
        migrations.AddField(
            model_name="webhooktrigger",
            name="ngrok_webhook_config",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="tables.ngrokwebhookconfig",
            ),
        ),
    ]
