# Generated by Django 5.1.3 on 2026-02-04 15:32

import django.db.models.deletion
import tables.models.knowledge_models.graphrag_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0136_merge_20260126_1313"),
    ]

    operations = [
        migrations.CreateModel(
            name="GraphRagIndexConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[("csv", "CSV"), ("text", "Text"), ("json", "JSON")],
                        default="text",
                        help_text="Input file type to use (csv, text, json).",
                        max_length=10,
                    ),
                ),
                (
                    "chunk_size",
                    models.PositiveIntegerField(
                        default=1200, help_text="The chunk size to use."
                    ),
                ),
                (
                    "chunk_overlap",
                    models.PositiveIntegerField(
                        default=100, help_text="The chunk overlap to use."
                    ),
                ),
                (
                    "chunk_strategy",
                    models.CharField(
                        choices=[("tokens", "Tokens"), ("sentence", "Sentence")],
                        default="tokens",
                        help_text="The chunking strategy to use (tokens or sentence).",
                        max_length=20,
                    ),
                ),
                (
                    "entity_types",
                    models.JSONField(
                        default=tables.models.knowledge_models.graphrag_models.GraphRagIndexConfig.default_entity_types,
                        help_text="The entity extraction types to use. Defaults to ['organization', 'person', 'geo', 'event']",
                    ),
                ),
                (
                    "max_gleanings",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="The maximum number of entity gleanings to use.",
                    ),
                ),
                (
                    "max_cluster_size",
                    models.PositiveIntegerField(
                        default=10, help_text="The maximum cluster size to use."
                    ),
                ),
            ],
            options={
                "db_table": "graph_rag_index_config",
            },
        ),
        migrations.CreateModel(
            name="AgentGraphRag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_graph_rags",
                        to="tables.agent",
                        unique=True,
                    ),
                ),
            ],
            options={
                "db_table": "agent_graph_rag",
            },
        ),
        migrations.CreateModel(
            name="GraphRag",
            fields=[
                ("graph_rag_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "rag_status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("warning", "Warning"),
                            ("failed", "Failed"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("indexed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "agents",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Agents that have access to this GraphRag",
                        related_name="graph_rags",
                        through="tables.AgentGraphRag",
                        to="tables.agent",
                    ),
                ),
                (
                    "base_rag_type",
                    models.ForeignKey(
                        limit_choices_to={"rag_type": "graph"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="graph_rags",
                        to="tables.baseragtype",
                    ),
                ),
                (
                    "embedder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tables.embeddingconfig",
                    ),
                ),
                (
                    "llm",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tables.llmconfig",
                    ),
                ),
                (
                    "index_config",
                    models.OneToOneField(
                        blank=True,
                        help_text="Index configuration for this GraphRag",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="graph_rag",
                        to="tables.graphragindexconfig",
                    ),
                ),
            ],
            options={
                "db_table": "graph_rag",
            },
        ),
        migrations.AddField(
            model_name="agentgraphrag",
            name="graph_rag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agent_links",
                to="tables.graphrag",
            ),
        ),
        migrations.CreateModel(
            name="GraphRagDocument",
            fields=[
                (
                    "graph_rag_document_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="graph_rag_links",
                        to="tables.documentmetadata",
                    ),
                ),
                (
                    "graph_rag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="graph_rag_documents",
                        to="tables.graphrag",
                    ),
                ),
            ],
            options={
                "db_table": "graph_rag_document",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("graph_rag", "document"),
                        name="unique_graph_rag_document",
                    )
                ],
            },
        ),
    ]
