# Generated by Django 5.1.3 on 2026-01-27 10:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0136_merge_20260126_1313"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionWarningMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("messages", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warnings",
                        to="tables.session",
                    ),
                ),
            ],
        ),
    ]
