# Generated by Django 5.1.3 on 2026-01-28 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0130_remove_defaultllmconfig_api_version_and_more"),
        ("tables", "0136_merge_20260126_1313"),
    ]

    operations = []
