# Generated by Django 5.1.3 on 2026-02-13 15:28

import django.core.validators
from django.db import migrations, models

def fix_low_max_tokens(apps, schema_editor):
    DefaultLLMConfig = apps.get_model("tables", "DefaultLLMConfig")
    
    DefaultLLMConfig.objects.filter(
        max_tokens__isnull=False, 
        max_tokens__lt=500
    ).update(max_tokens=500)

class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0136_remove_defaultllmconfig_max_completion_tokens_and_more"),
    ]

    operations = [
        migrations.RunPython(fix_low_max_tokens, reverse_code=migrations.RunPython.noop),
        
        migrations.AlterField(
            model_name="defaultllmconfig",
            name="max_tokens",
            field=models.IntegerField(
                blank=True,
                default=4096,
                null=True,
                validators=[django.core.validators.MinValueValidator(500)],
            ),
        ),
    ]