# Generated by Django 5.1.3 on 2026-02-02 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0129_merge_20251211_1413"),
        ("tables", "0136_merge_20260126_1313"),
    ]

    operations = []
