# Generated by Django 5.1.3 on 2026-02-09 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0137_graphragindexconfig_agentgraphrag_graphrag_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentgraphrag",
            name="search_method",
            field=models.CharField(
                choices=[("basic", "Basic Search"), ("local", "Local Search")],
                default="basic",
                help_text="Active search method: basic or local",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="GraphRagBasicSearchConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prompt",
                    models.TextField(
                        blank=True,
                        default=None,
                        help_text="The basic search prompt to use.",
                        null=True,
                    ),
                ),
                (
                    "k",
                    models.IntegerField(
                        default=10,
                        help_text="The number of text units to include in search context.",
                    ),
                ),
                (
                    "max_context_tokens",
                    models.IntegerField(default=12000, help_text="The maximum tokens."),
                ),
                (
                    "agent",
                    models.OneToOneField(
                        help_text="Agent this basic search configuration belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="graph_basic_search_config",
                        to="tables.agent",
                    ),
                ),
            ],
            options={
                "db_table": "graph_rag_basic_search_config",
            },
        ),
        migrations.CreateModel(
            name="GraphRagLocalSearchConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prompt",
                    models.TextField(
                        blank=True,
                        default=None,
                        help_text="The local search prompt to use.",
                        null=True,
                    ),
                ),
                (
                    "text_unit_prop",
                    models.FloatField(
                        default=0.5, help_text="The text unit proportion."
                    ),
                ),
                (
                    "community_prop",
                    models.FloatField(
                        default=0.15, help_text="The community proportion."
                    ),
                ),
                (
                    "conversation_history_max_turns",
                    models.IntegerField(
                        default=5, help_text="The conversation history maximum turns."
                    ),
                ),
                (
                    "top_k_entities",
                    models.IntegerField(
                        default=10, help_text="The top k mapped entities."
                    ),
                ),
                (
                    "top_k_relationships",
                    models.IntegerField(
                        default=10, help_text="The top k mapped relations."
                    ),
                ),
                (
                    "max_context_tokens",
                    models.IntegerField(default=12000, help_text="The maximum tokens."),
                ),
                (
                    "agent",
                    models.OneToOneField(
                        help_text="Agent this local search configuration belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="graph_local_search_config",
                        to="tables.agent",
                    ),
                ),
            ],
            options={
                "db_table": "graph_rag_local_search_config",
            },
        ),
    ]
