# Generated by Django 5.1.3 on 2026-01-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0137_add_preview_chunk"),
    ]

    operations = [
        migrations.AddField(
            model_name="naiveragchunk",
            name="overlap_end_index",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="naiveragchunk",
            name="overlap_start_index",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="naiveragpreviewchunk",
            name="overlap_end_index",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="naiveragpreviewchunk",
            name="overlap_start_index",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
