# Generated by Django 5.1.3 on 2026-02-10 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0137_ngrokwebhookconfig_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ngrokwebhookconfig",
            old_name="authtoken",
            new_name="auth_token",
        ),
    ]
