# Generated by Django 5.1.3 on 2026-02-04 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0137_apikey"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="apikey",
            new_name="tables_apik_prefix_fbdead_idx",
            old_name="tables_apik_prefix_3f7e47_idx",
        ),
    ]
