# Generated by Django 5.1.3 on 2026-01-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0137_merge_20260128_1859"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmbeddingModelTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
                ("predefined", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LLMConfigTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
                ("predefined", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LLMModelTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
                ("predefined", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RenameField(
            model_name="agenttag",
            old_name="predifined",
            new_name="predefined",
        ),
        migrations.RenameField(
            model_name="crewtag",
            old_name="predifined",
            new_name="predefined",
        ),
        migrations.RenameField(
            model_name="graphtag",
            old_name="predifined",
            new_name="predefined",
        ),
        migrations.AlterField(
            model_name="llmmodel",
            name="deployment_id",
            field=models.TextField(
                blank=True, help_text="Azure Deployment Name or Watsonx ID", null=True
            ),
        ),
        migrations.AddField(
            model_name="embeddingmodel",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="embedding_models",
                to="tables.embeddingmodeltag",
            ),
        ),
        migrations.AddField(
            model_name="llmmodel",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="llm_models", to="tables.llmmodeltag"
            ),
        ),
    ]
