# Generated by Django 5.1.3 on 2026-02-16 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0137_merge_20260202_1622"),
        ("tables", "0137_sessionwarningmessage"),
    ]

    operations = []
