# Generated by Django 5.1.3 on 2026-02-12 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0137_sessionwarningmessage"),
        ("tables", "0138_add_chunk_overlap_start_end_index"),
    ]

    operations = []
