# Generated by Django 5.1.3 on 2026-02-11 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0138_rename_authtoken_ngrokwebhookconfig_auth_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="telegramtriggernode",
            name="url_path",
        ),
    ]
