# Generated by Django 5.1.3 on 2026-02-20 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0137_sessionwarningmessage"),
        ("tables", "0138_graph_rag_search_methods"),
    ]

    operations = []
