# Generated by Django 5.1.3 on 2026-02-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0139_remove_telegramtriggernode_url_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ngrokwebhookconfig",
            name="auth_token",
            field=models.CharField(
                help_text="Token from dashboard.ngrok.com", max_length=255, unique=True
            ),
        ),
    ]
