# Generated by Django 5.1.3 on 2026-02-13 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0137_alter_defaultllmconfig_max_tokens"),
        ("tables", "0139_alter_embeddingmodel_unique_together_and_more"),
    ]

    operations = []
