# Generated by Django 5.1.3 on 2026-02-11 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0137_sessionwarningmessage"),
        ("tables", "0140_alter_ngrokwebhookconfig_auth_token"),
    ]

    operations = []
