# Generated by Django 5.1.3 on 2026-02-13 16:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0140_merge_20260213_1637"),
    ]

    operations = [
        migrations.AlterField(
            model_name="llmconfig",
            name="frequency_penalty",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name="llmconfig",
            name="max_tokens",
            field=models.IntegerField(
                blank=True,
                default=4096,
                null=True,
                validators=[django.core.validators.MinValueValidator(500)],
            ),
        ),
        migrations.AlterField(
            model_name="llmconfig",
            name="presence_penalty",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name="llmconfig",
            name="seed",
            field=models.IntegerField(blank=True, default=42, null=True),
        ),
        migrations.AlterField(
            model_name="llmconfig",
            name="temperature",
            field=models.FloatField(
                blank=True,
                default=0.5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(2.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="llmconfig",
            name="timeout",
            field=models.FloatField(blank=True, default=120.0, null=True),
        ),
        migrations.AlterField(
            model_name="llmconfig",
            name="top_p",
            field=models.FloatField(blank=True, default=1.0, null=True),
        ),
    ]
