# Generated by Django 5.1.3 on 2026-02-13 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0137_sessionwarningmessage"),
        ("tables", "0141_alter_llmconfig_frequency_penalty_and_more"),
    ]

    operations = []
