# Generated by Django 5.1.3 on 2026-02-17 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0138_merge_20260216_1249"),
        ("tables", "0141_merge_20260211_1305"),
    ]

    operations = []
