# Generated by Django 5.1.3 on 2026-02-17 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0139_metadata_hash_created_at_updated_at_fields"),
        ("tables", "0143_merge_20260217_1353"),
    ]

    operations = []
