# Generated by Django 5.1.3 on 2026-02-19 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0139_merge_chunk_preview_migrations"),
        ("tables", "0146_alter_audiotranscriptionnode_id_alter_crewnode_id_and_more"),
    ]

    operations = []
