# Generated by Django 5.1.3 on 2026-02-24 21:10

import django.db.models.deletion
import tables.models.base_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0146_alter_audiotranscriptionnode_id_alter_crewnode_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NoteNode",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "content_hash",
                    models.CharField(editable=False, max_length=64, null=True),
                ),
                (
                    "id",
                    models.BigIntegerField(
                        db_default=tables.models.base_models.NextVal(
                            models.Value("tables_global_node_seq")
                        ),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "graph",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="note_node_list",
                        to="tables.graph",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
