# Generated by Django 5.1.3 on 2026-02-19 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0142_merge_20260217_1250"),
        ("tables", "0146_alter_audiotranscriptionnode_id_alter_crewnode_id_and_more"),
    ]

    operations = []
