# 0148_cleanup_old_keys.py
# Generated by Django 5.1.3 on 2026-02-18 11:26

from django.db import migrations, models


def repair_unresolved_edges(apps, schema_editor):
    """
    Re-attempt resolution for edges left with start_node_id=0 or end_node_id=0
    by 0147_edge_keys_and_decision_data. The original start_key/end_key columns
    are still present at this point, so we can re-read them.
    After re-resolution, delete truly unresolvable edges and deduplicate.
    """
    from django.db.models import Min, Count

    Graph = apps.get_model('tables', 'Graph')
    Edge = apps.get_model('tables', 'Edge')

    node_model_names = [
        'CrewNode', 'PythonNode', 'FileExtractorNode', 'AudioTranscriptionNode',
        'LLMNode', 'EndNode', 'SubGraphNode', 'StartNode', 'DecisionTableNode',
        'WebhookTriggerNode', 'TelegramTriggerNode',
    ]

    node_models = []
    for name in node_model_names:
        try:
            node_models.append(apps.get_model('tables', name))
        except LookupError:
            pass

    try:
        node_models.append(apps.get_model('tables', 'NoteNode'))
    except LookupError:
        pass

    for graph in Graph.objects.all():
        unresolved_qs = Edge.objects.filter(graph_id=graph.id).filter(
            models.Q(start_node_id=0) | models.Q(end_node_id=0)
        )
        if not unresolved_qs.exists():
            continue

        # Build name-to-id map (same logic as 0147, with __end__ alias added)
        name_to_id_map = {}
        for model in node_models:
            has_node_name = any(f.name == 'node_name' for f in model._meta.fields)
            if has_node_name:
                nodes = model.objects.filter(graph_id=graph.id).values('id', 'node_name')
            else:
                nodes = model.objects.filter(graph_id=graph.id).values('id')
            for node in nodes:
                node_id = node['id']
                name_to_id_map[str(node_id)] = node_id
                if 'node_name' in node and node['node_name']:
                    name_to_id_map[node['node_name']] = node_id

        StartNodeModel = apps.get_model('tables', 'StartNode')
        start_node = StartNodeModel.objects.filter(graph_id=graph.id).first()
        if start_node:
            name_to_id_map['__start__'] = start_node.id

        EndNodeModel = apps.get_model('tables', 'EndNode')
        end_node = EndNodeModel.objects.filter(graph_id=graph.id).first()
        if end_node:
            name_to_id_map['__end_node__'] = end_node.id
            name_to_id_map['__end__'] = end_node.id

        # Re-attempt resolution using still-existing start_key/end_key columns
        edges_to_update = []
        edges_to_delete_pks = []
        for edge in unresolved_qs:
            start_id = edge.start_node_id
            end_id = edge.end_node_id

            if start_id == 0 and edge.start_key:
                resolved = name_to_id_map.get(edge.start_key)
                if resolved:
                    start_id = resolved

            if end_id == 0 and edge.end_key:
                resolved = name_to_id_map.get(edge.end_key)
                if resolved:
                    end_id = resolved

            if start_id != 0 and end_id != 0:
                edge.start_node_id = start_id
                edge.end_node_id = end_id
                edges_to_update.append(edge)
            else:
                edges_to_delete_pks.append(edge.pk)

        if edges_to_update:
            Edge.objects.bulk_update(edges_to_update, ['start_node_id', 'end_node_id'])
        if edges_to_delete_pks:
            Edge.objects.filter(pk__in=edges_to_delete_pks).delete()

    # Deduplicate remaining edges across all graphs (keep lowest pk per combo)
    duplicates = (
        Edge.objects.values('graph_id', 'start_node_id', 'end_node_id')
        .annotate(min_id=Min('id'), count=Count('id'))
        .filter(count__gt=1)
    )
    for dup in duplicates:
        Edge.objects.filter(
            graph_id=dup['graph_id'],
            start_node_id=dup['start_node_id'],
            end_node_id=dup['end_node_id'],
        ).exclude(id=dup['min_id']).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("tables", "0147_edge_keys_and_decision_data"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="conditionaledge",
            name="unique_graph_conditional_edge_source",
        ),
        migrations.RemoveConstraint(
            model_name="edge",
            name="unique_graph_edge",
        ),

        migrations.RunPython(repair_unresolved_edges, migrations.RunPython.noop),

        migrations.RemoveField(
            model_name="conditionaledge",
            name="source",
        ),
        migrations.RemoveField(
            model_name="edge",
            name="end_key",
        ),
        migrations.RemoveField(
            model_name="edge",
            name="start_key",
        ),
        migrations.RemoveField(
            model_name="decisiontablenode",
            name="default_next_node",
        ),
        migrations.RemoveField(
            model_name="decisiontablenode",
            name="next_error_node",
        ),
        migrations.RemoveField(
            model_name="conditiongroup",
            name="next_node",
        ),

        migrations.AddConstraint(
            model_name="conditionaledge",
            constraint=models.UniqueConstraint(
                fields=("graph", "source_node_id"),
                name="unique_graph_conditional_edge_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="edge",
            constraint=models.UniqueConstraint(
                fields=("graph", "start_node_id", "end_node_id"),
                name="unique_graph_edge",
            ),
        ),
    ]