# Generated by Django 5.1.3 on 2026-02-23 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0139_merge_graph_rag_migrations"),
        ("tables", "0147_merge_chunk_preview_migrations_2"),
    ]

    operations = []
