# Generated by Django 5.1.3 on 2026-03-06 10:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0147_merge_chunk_preview_migrations_2"),
    ]

    operations = [
        migrations.AddField(
            model_name="graph",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="graph",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
