# Generated by Django 5.1.3 on 2026-03-05 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0147_merge_chunk_preview_migrations_2"),
        ("tables", "0147_notenode"),
    ]

    operations = []
