# Generated by Django 5.1.3 on 2026-02-23 10:59

import django.db.models.deletion
import tables.models.base_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0147_merge_chunk_preview_migrations_2"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodeAgentNode",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "content_hash",
                    models.CharField(editable=False, max_length=64, null=True),
                ),
                (
                    "id",
                    models.BigIntegerField(
                        db_default=tables.models.base_models.NextVal(
                            models.Value("tables_global_node_seq")
                        ),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("node_name", models.CharField(blank=True, max_length=255)),
                ("input_map", models.JSONField(default=dict)),
                (
                    "output_variable_path",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                ("agent_mode", models.CharField(default="build", max_length=10)),
                ("system_prompt", models.TextField(blank=True, default="")),
                ("stream_handler_code", models.TextField(blank=True, default="")),
                ("libraries", models.JSONField(blank=True, default=list)),
                ("polling_interval_ms", models.IntegerField(default=1000)),
                ("silence_indicator_s", models.IntegerField(default=3)),
                ("indicator_repeat_s", models.IntegerField(default=5)),
                ("chunk_timeout_s", models.IntegerField(default=30)),
                ("inactivity_timeout_s", models.IntegerField(default=120)),
                ("max_wait_s", models.IntegerField(default=300)),
                (
                    "graph",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="code_agent_node_list",
                        to="tables.graph",
                    ),
                ),
                (
                    "llm_config",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tables.llmconfig",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("graph", "node_name"),
                        name="unique_graph_node_name_for_code_agent_node",
                    )
                ],
            },
        ),
    ]
