# 0148_cleanup_old_keys.py
# Generated by Django 5.1.3 on 2026-02-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tables", "0147_edge_keys_and_decision_data"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="conditionaledge",
            name="unique_graph_conditional_edge_source",
        ),
        migrations.RemoveConstraint(
            model_name="edge",
            name="unique_graph_edge",
        ),

        migrations.RemoveField(
            model_name="conditionaledge",
            name="source",
        ),
        migrations.RemoveField(
            model_name="edge",
            name="end_key",
        ),
        migrations.RemoveField(
            model_name="edge",
            name="start_key",
        ),
        migrations.RemoveField(
            model_name="decisiontablenode",
            name="default_next_node",
        ),
        migrations.RemoveField(
            model_name="decisiontablenode",
            name="next_error_node",
        ),
        migrations.RemoveField(
            model_name="conditiongroup",
            name="next_node",
        ),

        migrations.AddConstraint(
            model_name="conditionaledge",
            constraint=models.UniqueConstraint(
                fields=("graph", "source_node_id"),
                name="unique_graph_conditional_edge_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="edge",
            constraint=models.UniqueConstraint(
                fields=("graph", "start_node_id", "end_node_id"),
                name="unique_graph_edge",
            ),
        ),
    ]