# Generated by Django 5.1.3 on 2026-02-23 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0148_codeagentnode"),
    ]

    operations = [
        migrations.AddField(
            model_name="codeagentnode",
            name="session_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
