# Generated by Django 5.1.3 on 2026-02-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tables",
            "0148_remove_conditionaledge_unique_graph_conditional_edge_source_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="conditiongroup",
            name="expression",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="conditiongroup",
            name="manipulation",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
