# Generated by Django 5.1.3 on 2026-03-06 12:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0148_graph_created_at_graph_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="graph",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
