# Generated by Django 5.1.3 on 2026-03-09 17:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0148_graph_created_at_graph_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="NgrokWebhookConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "auth_token",
                    models.CharField(
                        help_text="Token from dashboard.ngrok.com",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        blank=True, help_text="Your domain", max_length=255, null=True
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        choices=[("us", "Us"), ("eu", "Eu"), ("ap", "Ap")],
                        default="eu",
                        max_length=2,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="telegramtriggernode",
            name="url_path",
        ),
        migrations.AddField(
            model_name="telegramtriggernode",
            name="webhook_trigger",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="telegram_trigger_nodes",
                to="tables.webhooktrigger",
            ),
        ),
        migrations.AlterField(
            model_name="webhooktrigger",
            name="path",
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Path may only contain letters, numbers, hyphens, and underscores, and must start with a letter or number.",
                        regex="^[a-zA-Z0-9]{1}[a-zA-Z0-9-_]*$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="webhooktrigger",
            name="ngrok_webhook_config",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="tables.ngrokwebhookconfig",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="webhooktrigger",
            unique_together={("path", "ngrok_webhook_config")},
        ),
    ]
