# Generated by Django 5.1.3 on 2026-03-06 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0147_merge_chunk_preview_migrations_2"),
        ("tables", "0148_fix_webhooktrigger_per_flow"),
    ]

    operations = []
