# Generated by Django 5.1.3 on 2026-03-06 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0148_graph_created_at_graph_updated_at"),
        ("tables", "0149_merge_tunnels_configuration_1"),
    ]

    operations = []
