# Generated by Django 5.1.3 on 2026-03-11 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0149_allow_blank_conditional_edge_source"),
        ("tables", "0149_ngrokwebhookconfig_and_more"),
    ]

    operations = []
