# Generated by Django 5.1.3 on 2026-03-06 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0147_merge_chunk_preview_migrations_2"),
        ("tables", "0149_alter_conditiongroup_expression_and_more"),
    ]

    operations = []
