# Generated by Django 5.1.3 on 2026-03-10 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "tables",
            "0148_label_graph_labels_label_unique_label_name_per_level_and_more",
        ),
        ("tables", "0149_ngrokwebhookconfig_and_more"),
    ]

    operations = []
