# Generated by Django 5.1.3 on 2026-03-06 12:45

import uuid
from django.db import migrations


def populate_uuid(apps, schema_editor):
    Graph = apps.get_model("tables", "Graph")
    for graph in Graph.objects.filter(uuid__isnull=True):
        graph.uuid = uuid.uuid4()
        graph.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0149_graph_uuid"),
    ]

    operations = [
        migrations.RunPython(populate_uuid, migrations.RunPython.noop),
    ]
