# Generated by Django 5.1.3 on 2026-03-06 12:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0150_populate_graph_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="graph",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
