# Generated by Django 5.1.3 on 2026-03-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0150_merge_est_1999"),
    ]

    operations = [
        migrations.AddField(
            model_name="pythoncode",
            name="content_hash",
            field=models.CharField(editable=False, max_length=64, null=True),
        ),
    ]
