# Generated by Django 5.1.3 on 2026-03-11 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0150_merge_20260306_1326"),
        ("tables", "0150_merge_est_1999"),
    ]

    operations = []
