# Generated by Django 5.1.3 on 2026-03-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0151_codeagentnode_output_schema"),
    ]

    operations = [
        migrations.AddField(
            model_name="graph",
            name="epicchat_enabled",
            field=models.BooleanField(
                default=False,
                help_text="If 'True' -> flow is connected to EpicChat widget.",
            ),
        ),
    ]
