# Generated by Django 5.1.3 on 2026-03-10 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0149_ngrokwebhookconfig_and_more"),
        ("tables", "0151_alter_graph_uuid"),
    ]

    operations = []
