# Generated by Django 4.2.7 on 2026-03-03 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0150_graph_is_ralph'),
        ('tables', '0151_codeagentnode_output_schema'),
    ]

    operations = [
    ]
