# Generated by Django 5.1.3 on 2026-03-16 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0154_remove_unique_node_names"),
    ]

    operations = [
        migrations.CreateModel(
            name="DefaultModels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agent_fcm_llm_config",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_models_agent_fcm_llm",
                        to="tables.llmconfig",
                    ),
                ),
                (
                    "agent_llm_config",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_models_agent_llm",
                        to="tables.llmconfig",
                    ),
                ),
                (
                    "memory_embedding_config",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_models_memory_embedding",
                        to="tables.embeddingconfig",
                    ),
                ),
                (
                    "memory_llm_config",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_models_memory_llm",
                        to="tables.llmconfig",
                    ),
                ),
                (
                    "project_manager_llm_config",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_models_manager_llm",
                        to="tables.llmconfig",
                    ),
                ),
                (
                    "transcription_llm_config",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_models_transcription_llm",
                        to="tables.realtimetranscriptionconfig",
                    ),
                ),
                (
                    "voice_llm_config",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_models_voice_llm",
                        to="tables.realtimeconfig",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
