# Generated by Django 5.1.3 on 2026-03-16 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0151_pythoncode_content_hash"),
        ("tables", "0154_remove_unique_node_names"),
    ]

    operations = []
