# Generated by Django 5.1.3 on 2026-03-19 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0154_remove_unique_node_names"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="NoteNode",
            new_name="GraphNote",
        ),
        migrations.AlterField(
            model_name="graphnote",
            name="graph",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="graph_note_list",
                to="tables.graph",
            ),
        ),
    ]
