# Generated by Django 5.1.3 on 2026-03-17 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "tables",
            "0138_rename_tables_apik_prefix_3f7e47_idx_tables_apik_prefix_fbdead_idx",
        ),
        ("tables", "0154_remove_unique_node_names"),
    ]

    operations = []
