# Generated by Django 5.1.3 on 2026-03-16 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0153_codeagentnode_streamconfig_epicchat"),
        ("tables", "0154_remove_unique_node_names"),
    ]

    operations = []
