# Generated by Django 5.1.3 on 2026-03-16 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0150_merge_20260310_1215"),
        ("tables", "0154_remove_unique_node_names"),
    ]

    operations = []
