# Generated by Django 5.1.3 on 2026-03-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0155_merge_20260316_2004"),
    ]

    operations = [
        migrations.AddField(
            model_name="label",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
