# Generated by Django 5.1.3 on 2026-03-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0155_defaultmodels"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmconfig",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="llm_configs", to="tables.llmconfigtag"
            ),
        ),
    ]
