# Generated by Django 5.1.3 on 2026-03-18 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0155_merge_est_2004"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="audiotranscriptionnode",
            name="content_hash",
        ),
        migrations.RemoveField(
            model_name="conditionaledge",
            name="content_hash",
        ),
        migrations.RemoveField(
            model_name="crewnode",
            name="content_hash",
        ),
        migrations.RemoveField(
            model_name="decisiontablenode",
            name="content_hash",
        ),
        migrations.RemoveField(
            model_name="edge",
            name="content_hash",
        ),
        migrations.RemoveField(
            model_name="endnode",
            name="content_hash",
        ),
        migrations.RemoveField(
            model_name="fileextractornode",
            name="content_hash",
        ),
        migrations.RemoveField(
            model_name="llmnode",
            name="content_hash",
        ),
        migrations.RemoveField(
            model_name="notenode",
            name="content_hash",
        ),
        migrations.RemoveField(
            model_name="pythoncode",
            name="content_hash",
        ),
        migrations.RemoveField(
            model_name="pythonnode",
            name="content_hash",
        ),
        migrations.RemoveField(
            model_name="startnode",
            name="content_hash",
        ),
        migrations.RemoveField(
            model_name="subgraphnode",
            name="content_hash",
        ),
        migrations.RemoveField(
            model_name="telegramtriggernode",
            name="content_hash",
        ),
        migrations.RemoveField(
            model_name="webhooktriggernode",
            name="content_hash",
        ),
    ]
