# Generated by Django 5.1.3 on 2026-03-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0156_llmconfig_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmbeddingConfigTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
                ("predefined", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="embeddingconfig",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="embedding_configs",
                to="tables.embeddingconfigtag",
            ),
        ),
    ]
