# Generated by Django 5.1.3 on 2026-03-20 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0150_graph_name_unique"),
        ("tables", "0156_remove_audiotranscriptionnode_content_hash_and_more"),
    ]

    operations = []
