# Generated by Django 5.1.3 on 2026-03-24 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0152_merge_20260310_1429"),
        ("tables", "0157_merge_20260320_1426"),
    ]

    operations = []
