# Generated by Django 5.1.3 on 2026-03-20 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0155_merge_20260316_2004"),
        ("tables", "0157_merge_20260320_1426"),
    ]

    operations = []
