# Generated by Django 5.1.3 on 2026-03-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0157_embeddingconfigtag_embeddingconfig_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="RealtimeConfigTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
                ("predefined", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RealtimeTranscriptionConfigTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
                ("predefined", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="realtimeconfig",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="realtime_configs",
                to="tables.realtimeconfigtag",
            ),
        ),
        migrations.AddField(
            model_name="realtimetranscriptionconfig",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="realtime_transcription_configs",
                to="tables.realtimetranscriptionconfigtag",
            ),
        ),
    ]
