# Generated by Django 5.1.3 on 2026-03-23 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0158_merge_20260320_1738"),
        ("tables", "0158_merge_20260320_1826"),
    ]

    operations = []
