# Generated by Django 5.1.3 on 2026-03-24 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0155_merge_epic_chat"),
        ("tables", "0159_merge_20260323_1646"),
    ]

    operations = []
