# Generated by Django 5.1.3 on 2026-03-24 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0160_merge_epic_chat_2"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="codeagentnode",
            name="unique_graph_node_name_for_code_agent_node",
        ),
        migrations.RemoveField(
            model_name="codeagentnode",
            name="content_hash",
        ),
    ]
