# Generated by Django 5.1.3 on 2026-03-24 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "tables",
            "0161_remove_codeagentnode_unique_graph_node_name_for_code_agent_node_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="parent_session",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subgraph_sessions",
                to="tables.session",
            ),
        ),
    ]
