# Generated by Django 5.1.3 on 2026-03-26 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0152_merge_20260310_1429"),
        (
            "tables",
            "0161_remove_codeagentnode_unique_graph_node_name_for_code_agent_node_and_more",
        ),
    ]

    operations = []
