# Generated by Django 5.1.3 on 2026-03-26 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0162_merge_20260326_1203"),
        ("tables", "0162_session_parent_session"),
    ]

    operations = []
