# Generated by Django 5.1.3 on 2026-04-03 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0163_merge_20260326_1806"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GraphFile",
        ),
    ]
