# Generated by Django 5.1.3 on 2026-04-03 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0159_alter_voice_no_choices"),
        ("tables", "0163_merge_20260326_1806"),
    ]

    operations = []
