# Generated by Django 5.1.3 on 2026-03-30 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0151_classificationdecisiontablenode_expression_errors_as_false"),
        ("tables", "0163_merge_20260326_1806"),
    ]

    operations = []
