# Generated by Django 5.1.3 on 2026-04-03 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0162_merge_make_settings_accord_to_req"),
        ("tables", "0163_merge_20260326_1806"),
    ]

    operations = []
