# Generated by Django 5.1.3 on 2026-04-07 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0148_merge_graph_ragmigrations_2"),
        ("tables", "0163_merge_20260326_1806"),
    ]

    operations = []
