# Generated by Django 5.1.3 on 2026-04-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0164_delete_graphfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeagentnode',
            name='use_storage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pythonnode',
            name='use_storage',
            field=models.BooleanField(default=False),
        ),
    ]
