# Generated by Django 5.1.3 on 2026-04-03 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0164_merge_20260403_1200"),
        ("tables", "0164_merge_20260403_1226"),
    ]

    operations = []
