# Generated by Django 5.1.3 on 2026-04-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0165_merge_20260403_1649"),
    ]

    operations = [
        migrations.AlterField(
            model_name="llmconfig",
            name="seed",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="voicesettings",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
