# Generated by Django 5.1.3 on 2026-04-09 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0165_codeagentnode_use_storage_pythonnode_use_storage'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(help_text="Org-relative path, never starts with '/'", max_length=2048)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_files', to='tables.organization')),
            ],
        ),
        migrations.CreateModel(
            name='GraphStorageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_files', to='tables.graph')),
                ('storage_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graph_storage_files', to='tables.storagefile')),
            ],
        ),
        migrations.AddIndex(
            model_name='storagefile',
            index=models.Index(fields=['org', 'path'], name='tables_stor_org_id_f9ae19_idx'),
        ),
        migrations.AddConstraint(
            model_name='storagefile',
            constraint=models.UniqueConstraint(fields=('org', 'path'), name='unique_storage_file_per_org'),
        ),
        migrations.AddConstraint(
            model_name='graphstoragefile',
            constraint=models.UniqueConstraint(fields=('graph', 'storage_file'), name='unique_graph_storage_file'),
        ),
    ]
