# Generated by Django 5.1.3 on 2026-04-10 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0164_merge_0156_label_metadata_0163_merge_20260326_1806"),
        ("tables", "0166_alter_llmconfig_seed"),
    ]

    operations = []
