# Generated by Django 5.1.3 on 2026-04-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0167_merge_20260410_1240"),
    ]

    operations = [
        migrations.AddField(
            model_name="pythonnode",
            name="test_input",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
