# Generated by Django 5.1.3 on 2026-04-10 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0167_merge_20260409_2043"),
        ("tables", "0167_merge_20260410_1240"),
    ]

    operations = []
