# Generated by Django 5.1.3 on 2026-04-11 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0164_merge_20260330_1744'),
        ('tables', '0167_merge_20260410_1240'),
    ]

    operations = [
    ]
