# Generated by Django 5.1.3 on 2026-04-16 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0155_merge_20260317_1513"),
        ("tables", "0168_merge_graph_rag_migrations_4"),
    ]

    operations = []
