# Generated by Django 5.1.3 on 2026-04-14 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0168_merge_20260410_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionStorageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_files', to='tables.session')),
                ('storage_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_storage_files', to='tables.storagefile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('session', 'storage_file'), name='unique_session_storage_file')],
            },
        ),
    ]
