# Generated by Django 5.1.3 on 2026-04-16 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0168_merge_20260411_1540'),
        ('tables', '0168_merge_graph_rag_migrations_4'),
    ]

    operations = [
    ]
