# Generated by Django 5.1.3 on 2026-04-17 10:11

import django.utils.timezone
import tables.models.base_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0169_merge_20260416_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificationconditiongroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classificationconditiongroup',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='classificationconditiongroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='classificationdecisiontablenode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classificationdecisiontablenode',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='classificationdecisiontablenode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='classificationdecisiontablenode',
            name='id',
            field=models.BigIntegerField(db_default=tables.models.base_models.NextVal(models.Value('tables_global_node_seq')), editable=False, primary_key=True, serialize=False),
        ),
    ]
