# Generated by Django 5.1.3 on 2026-04-17 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0168_merge_graph_rag_migrations_4'),
        ('tables', '0169_sessionstoragefile'),
    ]

    operations = [
    ]
