# Generated by Django 5.1.3 on 2026-04-17 16:51

import django.db.models.deletion
import django.utils.timezone
import tables.models.rbac_models.managers
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("tables", "0169_merge_imp_auth"),
    ]

    operations = [
        # --- Pre-step: wipe legacy data ---
        # Legacy graph-domain `Organization` and `OrganizationUser` rows (named
        # flow end-users) have no mapping into the new RBAC schema. Per-flow
        # persistent variables (GraphOrganization, GraphOrganizationUser) are
        # also dropped because they FK into the above. Session.graph_user is
        # on_delete=SET_NULL, so those pointers nullify automatically.
        migrations.RunSQL(
            sql=(
                "DELETE FROM tables_graphorganizationuser;"
                "DELETE FROM tables_graphorganization;"
                "DELETE FROM tables_organizationuser;"
                "DELETE FROM tables_organization;"
                # Force deferred FK constraint triggers to fire now so the
                # follow-up ALTER TABLE operations don't hit "pending trigger
                # events" inside the same transaction.
                "SET CONSTRAINTS ALL IMMEDIATE;"
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Drop default-Django-User tables. Safe because no model has an FK to
        # auth.User. `auth_group` / `auth_permission` remain (PermissionsMixin
        # still references them).
        migrations.RunSQL(
            sql=(
                "DROP TABLE IF EXISTS auth_user_user_permissions CASCADE;"
                "DROP TABLE IF EXISTS auth_user_groups CASCADE;"
                "DROP TABLE IF EXISTS auth_user CASCADE;"
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "display_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="avatars/"),
                ),
                ("is_superadmin", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "rbac_user",
            },
            managers=[
                ("objects", tables.models.rbac_models.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="PasswordResetToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.UUIDField(db_index=True, default=uuid.uuid4)),
                ("is_used", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "rbac_password_reset_token",
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_built_in", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "rbac_role",
            },
        ),
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("flows", "Flows"),
                            ("agents", "Agents"),
                            ("tools", "Tools"),
                            ("knowledge_sources", "Knowledge Sources"),
                            ("files", "Files"),
                            ("projects", "Projects"),
                            ("llm_configs", "LLM Configs"),
                            ("secrets", "Secrets"),
                            ("users", "Users"),
                            ("roles", "Roles"),
                        ],
                        max_length=32,
                    ),
                ),
                ("permissions", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "rbac_role_permission",
            },
        ),
        migrations.RemoveConstraint(
            model_name="graphorganizationuser",
            name="unique_user_per_flow",
        ),
        migrations.RemoveConstraint(
            model_name="organizationuser",
            name="unique_flow_user_for_organization",
        ),
        migrations.RemoveField(
            model_name="graphorganizationuser",
            name="user",
        ),
        migrations.AddField(
            model_name="graphorganizationuser",
            name="organization_user",
            field=models.ForeignKey(
                # Placeholder default (never applied — rows wiped above). The
                # real default is not preserved (preserve_default=False).
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="graph_persistent_states",
                to="tables.organizationuser",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="organization",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="organization",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="organizationuser",
            name="joined_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="organizationuser",
            name="org",
            field=models.ForeignKey(
                default=1,  # placeholder, never applied (rows wiped above)
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="tables.organization",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="graphorganization",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="graph_persistent_states",
                to="tables.organization",
            ),
        ),
        migrations.AlterField(
            model_name="graphorganization",
            name="user_variables",
            field=models.JSONField(
                default=dict,
                help_text="Seed template of variables copied into each user's GraphOrganizationUser row",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddConstraint(
            model_name="graphorganizationuser",
            constraint=models.UniqueConstraint(
                fields=("graph", "organization_user"), name="unique_user_per_flow"
            ),
        ),
        migrations.AlterModelTable(
            name="organization",
            table="rbac_organization",
        ),
        migrations.AlterModelTable(
            name="organizationuser",
            table="rbac_organization_user",
        ),
        migrations.AddField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AddField(
            model_name="organizationuser",
            name="user",
            field=models.ForeignKey(
                default=1,  # placeholder, never applied (rows wiped above)
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organization_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="organizationuser",
            unique_together={("user", "org")},
        ),
        migrations.AddField(
            model_name="passwordresettoken",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="password_reset_tokens",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="org",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roles",
                to="tables.organization",
            ),
        ),
        migrations.AddField(
            model_name="organizationuser",
            name="role",
            field=models.ForeignKey(
                default=1,  # placeholder, never applied (rows wiped above)
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organization_users",
                to="tables.role",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rolepermission",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="permissions_set",
                to="tables.role",
            ),
        ),
        migrations.RemoveField(
            model_name="organizationuser",
            name="name",
        ),
        migrations.RemoveField(
            model_name="organizationuser",
            name="organization",
        ),
        migrations.AlterUniqueTogether(
            name="rolepermission",
            unique_together={("role", "resource_type")},
        ),
    ]
