# Generated by Django 5.1.3 on 2026-04-21 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0169_merge_20260416_1127"),
        ("tables", "0169_merge_imp_auth"),
    ]

    operations = []
