# Generated by Django 5.1.3 on 2026-04-17 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0169_merge_imp_auth"),
    ]

    operations = [
        migrations.CreateModel(
            name="GraphVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        default=None,
                        editable=False,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "snapshot",
                    models.JSONField(
                        help_text="Serialized graph state: nodes, edges, conditional edges, metadata."
                    ),
                ),
                (
                    "dependencies",
                    models.JSONField(
                        default=dict,
                        help_text="Lightweight manifest of external dependency IDs referenced at snapshot time.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "graph",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="tables.graph",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
