# Generated by Django 5.1.3 on 2026-04-27 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0170_graphversion"),
        ("tables", "0170_pythoncodetool_variables_drop_args_schema"),
    ]

    operations = []
