# Generated by Django 5.1.3 on 2026-04-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0170_merge_20260417_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagefile',
            name='path',
            field=models.CharField(help_text="Org-relative path, never starts with '/'", max_length=1000),
        ),
    ]
