# Generated by Django 5.1.3 on 2026-04-20 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0170_classificationconditiongroup_created_at_and_more'),
        ('tables', '0170_merge_20260417_1811'),
    ]

    operations = [
    ]
