# Generated by Django 5.1.3 on 2026-04-21 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0172_cdt_python_code_fks'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificationdecisiontablenode',
            name='default_llm_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cdt_nodes_as_default', to='tables.llmconfig'),
        ),
        migrations.CreateModel(
            name='ClassificationDecisionTablePrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prompt_key', models.CharField(max_length=255)),
                ('prompt_text', models.TextField(blank=True, default='')),
                ('output_schema', models.JSONField(blank=True, default=dict)),
                ('result_variable', models.CharField(default='prompt_result', max_length=255)),
                ('variable_mappings', models.JSONField(blank=True, default=dict)),
                ('cdt_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_configs', to='tables.classificationdecisiontablenode')),
                ('llm_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cdt_prompts', to='tables.llmconfig')),
            ],
            options={
                'unique_together': {('cdt_node', 'prompt_key')},
            },
        ),
    ]
