# Generated by Django 5.1.3 on 2026-04-28 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0172_apikey_created_by"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="storagefile",
            name="storagefile_name_trgm_idx",
        ),
        migrations.RenameIndex(
            model_name="apikey",
            new_name="tables_apik_prefix_fbdead_idx",
            old_name="tables_apik_prefix_3f7e47_idx",
        ),
    ]
