# Generated by Django 5.1.3 on 2026-04-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0173_classificationdecisiontablenode_default_llm_config_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classificationconditiongroup',
            name='route_code',
        ),
        migrations.AddField(
            model_name='classificationconditiongroup',
            name='next_node_id',
            field=models.BigIntegerField(default=None, null=True),
        ),
    ]
