# Generated by Django 5.1.3 on 2026-04-29 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0171_alter_graphversion_deleted_at"),
        ("tables", "0173_remove_storagefile_storagefile_name_trgm_idx_and_more"),
    ]

    operations = []
