# Generated by Django 5.1.3 on 2026-05-04 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0170_merge_0169_merge_20260416_1127_0169_merge_imp_auth"),
        ("tables", "0174_merge_20260429_1147"),
    ]

    operations = []
