# Generated by Django 5.1.3 on 2026-05-05 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tables", "0174_merge_20260429_1147"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subgraphnode",
            name="subgraph",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="as_subgraph",
                to="tables.graph",
            ),
        ),
    ]
