# Generated by Django 5.1.3 on 2026-04-29 16:55

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0174_merge_20260429_1147"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name="organization",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                name="rbac_organization_name_ci_uniq",
            ),
        ),
    ]
