# Generated by Django 5.1.3 on 2026-04-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0174_remove_classificationconditiongroup_route_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classificationdecisiontableprompt',
            name='output_schema',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
