# Generated by Django 5.1.3 on 2026-04-27 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0170_graphversion"),
        ("tables", "0174_remove_classificationconditiongroup_route_code_and_more"),
        ("tables", "0174_storagefile_name_trgm_index"),
    ]

    operations = []
