# Generated by Django 5.1.3 on 2026-04-27 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0170_graphversion"),
        ("tables", "0174_storagefile_name_trgm_index"),
    ]

    operations = []
