# Generated by Django 5.1.3 on 2026-05-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0175_alter_organization_name_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="organizationuser",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="organizationuser",
            constraint=models.UniqueConstraint(
                fields=("user", "org"), name="rbac_organization_user_user_org_uniq"
            ),
        ),
    ]
