# Generated by Django 5.1.3 on 2026-05-01 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0171_merge_tools_configuration"),
        ("tables", "0174_merge_20260429_1147"),
        ("tables", "0175_merge_20260427_1053"),
    ]

    operations = []
