# Generated by Django 5.1.3 on 2026-05-13 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0175_alter_organization_name_and_more"),
        ("tables", "0175_merge_20260504_1000"),
    ]

    operations = []
