# Generated by Django 5.1.3 on 2026-04-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tables", "0175_merge_20260427_1405"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classificationdecisiontablenode",
            name="default_next_node",
        ),
        migrations.RemoveField(
            model_name="classificationdecisiontablenode",
            name="next_error_node",
        ),
        migrations.AddField(
            model_name="classificationconditiongroup",
            name="route_code",
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="classificationdecisiontablenode",
            name="default_next_node_id",
            field=models.BigIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="classificationdecisiontablenode",
            name="next_error_node_id",
            field=models.BigIntegerField(default=None, null=True),
        ),
        migrations.AddConstraint(
            model_name="classificationconditiongroup",
            constraint=models.UniqueConstraint(
                condition=models.Q(("route_code__isnull", False)),
                fields=("classification_decision_table_node", "route_code"),
                name="unique_route_code_per_cdt_node",
            ),
        ),
    ]
