# Generated by Django 5.1.3 on 2026-05-11 08:55

import django.db.models.deletion
import tables.models.base_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0174_merge_20260429_1147"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduleTriggerNode",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "id",
                    models.BigIntegerField(
                        db_default=tables.models.base_models.NextVal(
                            models.Value("tables_global_node_seq")
                        ),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("node_name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "timezone",
                    models.CharField(blank=True, default="UTC", max_length=64),
                ),
                (
                    "run_mode",
                    models.CharField(
                        blank=True,
                        choices=[("once", "Once"), ("repeat", "Repeat")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("start_date_time", models.DateTimeField(blank=True, null=True)),
                ("every", models.IntegerField(blank=True, null=True)),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("seconds", "Seconds"),
                            ("minutes", "Minutes"),
                            ("hours", "Hours"),
                            ("days", "Days"),
                            ("weeks", "Weeks"),
                            ("months", "Months"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("weekdays", models.JSONField(blank=True, null=True)),
                (
                    "end_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("never", "Never"),
                            ("on_date", "On Date"),
                            ("after_n_runs", "After N Runs"),
                        ],
                        max_length=15,
                        null=True,
                    ),
                ),
                ("end_date_time", models.DateTimeField(blank=True, null=True)),
                ("max_runs", models.IntegerField(blank=True, null=True)),
                ("current_runs", models.IntegerField(default=0)),
                ("next_run_date_time", models.DateTimeField(blank=True, null=True)),
                (
                    "graph",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_trigger_node_list",
                        to="tables.graph",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
