# Generated by Django 5.1.3 on 2026-05-15 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0126_merge_20251112_1805"),
        ("tables", "0175_merge_20260504_1000"),
    ]

    operations = []
