# Generated by Django 5.1.3 on 2026-05-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0175_alter_geminirealtimeconfig_model_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openairealtimeconfig",
            name="model_name",
            field=models.CharField(default="gpt-realtime-1.5", max_length=250),
        ),
    ]
