# Generated by Django 5.1.3 on 2026-05-15 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0175_alter_subgraphnode_subgraph"),
        ("tables", "0176_merge_organizations_migrations"),
    ]

    operations = []
