# Generated by Django 5.1.3 on 2026-05-15 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0176_merge_20260515_1532"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crewnode",
            name="crew",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="crew_node",
                to="tables.crew",
            ),
        ),
    ]
