# Generated by Django 5.1.3 on 2026-05-13 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0176_merge_organizations_migrations"),
        ("tables", "0177_merge_user_management_migrations"),
    ]

    operations = []
