# Generated by Django 5.1.3 on 2026-05-11 21:23

import tables.models.rbac_models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0177_merge_user_management_migrations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=tables.models.rbac_models.user._avatar_upload_path,
            ),
        ),
    ]
