# Generated by Django 5.1.3 on 2026-05-21 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0176_merge_20260501_1015"),
        ("tables", "0177_merge_20260515_1407"),
    ]

    operations = []
