# Generated by Django 5.1.3 on 2026-05-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0177_merge_20260511_1502"),
    ]

    operations = [
        migrations.AddField(
            model_name="classificationconditiongroup",
            name="section",
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
