# Generated by Django 5.1.3 on 2026-05-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0178_add_localhost_webhook_config"),
    ]

    operations = [
        migrations.AlterField(
            model_name="localhostwebhookconfig",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="webhooktrigger",
            unique_together={
                ("path", "localhost_webhook_config"),
                ("path", "ngrok_webhook_config"),
            },
        ),
    ]
