# Generated by Django 5.1.3 on 2026-05-13 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0178_merge_user_management_migrations_2"),
        ("tables", "0178_user_profile_migration"),
    ]

    operations = []
