# Generated by Django 5.1.3 on 2026-05-14 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0176_merge_organizations_migrations"),
        ("tables", "0178_classificationconditiongroup_section"),
    ]

    operations = []
