# Generated by Django 5.1.3 on 2026-05-14 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0176_pythoncodetool_use_storage"),
        ("tables", "0179_merge_demo_migrations"),
    ]

    operations = []
