# Generated by Django 5.1.3 on 2026-05-18 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0176_create_schedule_trigger_node"),
        ("tables", "0180_merge_user_profile_migrations_2"),
    ]

    operations = []
