# Generated by Django 5.1.3 on 2026-05-18 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0177_merge_20260515_1407"),
        ("tables", "0180_merge_20260514_1302"),
    ]

    operations = []
