# Generated by Django 5.1.3 on 2026-05-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0180_merge_user_profile_migrations_2"),
    ]

    operations = [
        migrations.AddField(
            model_name="graphsessionmessage",
            name="parent_subgraph_execution_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name="graphsessionmessage",
            index=models.Index(
                fields=["session", "parent_subgraph_execution_id", "id"],
                name="gsm_session_parent_id_idx",
            ),
        ),
    ]
