# Generated by Django 5.1.3 on 2026-05-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0181_merge_schedule_trigger_node"),
    ]

    operations = [
        migrations.AddField(
            model_name="graph",
            name="save_version",
            field=models.IntegerField(default=1),
        ),
    ]
