# Generated by Django 5.1.3 on 2026-05-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0181_merge_schedule_trigger_node"),
    ]

    operations = [
        migrations.AddField(
            model_name="naiveragdocumentconfig",
            name="error_code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("chunking_failed", "Chunking Failed"),
                    ("embedding_failed", "Embedding Failed"),
                    ("embedder_auth", "Embedder Auth"),
                    ("embedder_rate_limit", "Embedder Rate Limit"),
                    ("unknown", "Unknown"),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="naiveragdocumentconfig",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="naiveragdocumentconfig",
            name="failed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
