# Generated by Django 5.1.3 on 2026-05-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0181_merge_schedule_trigger_node"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rolepermission",
            name="resource_type",
            field=models.CharField(
                choices=[
                    ("organizations", "Organizations"),
                    ("flows", "Flows"),
                    ("agents", "Agents"),
                    ("tools", "Tools"),
                    ("knowledge_sources", "Knowledge Sources"),
                    ("files", "Files"),
                    ("projects", "Projects"),
                    ("llm_configs", "LLM Configs"),
                    ("secrets", "Secrets"),
                    ("users", "Users"),
                    ("roles", "Roles"),
                ],
                max_length=32,
            ),
        ),
    ]
