# Generated by Django 5.1.3 on 2026-05-26 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0178_merge_20260521_0947"),
        ("tables", "0181_merge_schedule_trigger_node"),
    ]

    operations = []
