# Generated by Django 5.1.3 on 2026-05-22 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0181_merge_schedule_trigger_node"),
    ]

    operations = [
        migrations.CreateModel(
            name="DefaultAgentDefinitionConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "max_iter",
                    models.IntegerField(
                        default=None,
                        help_text="Default max reasoning iterations for an AgentDefinition when its own value is null.",
                        null=True,
                    ),
                ),
                (
                    "max_rpm",
                    models.IntegerField(
                        default=None,
                        help_text="Default max LLM requests per minute when AgentDefinition.max_rpm is null.",
                        null=True,
                    ),
                ),
                (
                    "max_execution_time",
                    models.IntegerField(
                        default=None,
                        help_text="Default per-run wall-clock budget in seconds when AgentDefinition.max_execution_time is null.",
                        null=True,
                    ),
                ),
                (
                    "cache",
                    models.BooleanField(
                        default=None,
                        help_text="Default for whether tool-result caching is enabled when AgentDefinition.cache is null.",
                        null=True,
                    ),
                ),
                (
                    "max_retry_limit",
                    models.IntegerField(
                        default=None,
                        help_text="Default max retries on transient failures when AgentDefinition.max_retry_limit is null.",
                        null=True,
                    ),
                ),
                (
                    "default_temperature",
                    models.FloatField(
                        default=None,
                        help_text="Default sampling temperature applied when neither the AgentDefinition nor its LLMConfig specify one.",
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AgentDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Stable identifier (slug-like) unique within an organization. Used to reference this agent from flows, code, and the UI.",
                        max_length=255,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Short human-readable persona label, e.g. 'Senior Researcher'.",
                        max_length=255,
                    ),
                ),
                (
                    "instructions",
                    models.TextField(
                        help_text="Free-form prompt for the agent. Put behavior, goals, tone, and constraints here."
                    ),
                ),
                (
                    "max_iter",
                    models.IntegerField(
                        default=None,
                        help_text="Max reasoning iterations per task before forcing a final answer. Null falls back to DefaultAgentDefinitionConfig.",
                        null=True,
                    ),
                ),
                (
                    "max_rpm",
                    models.IntegerField(
                        default=None,
                        help_text="LLM request rate cap (requests per minute). Null falls back to DefaultAgentDefinitionConfig; no cap if both are null.",
                        null=True,
                    ),
                ),
                (
                    "max_execution_time",
                    models.IntegerField(
                        default=None,
                        help_text="Wall-clock budget in seconds for a single agent run. Null falls back to DefaultAgentDefinitionConfig.",
                        null=True,
                    ),
                ),
                (
                    "cache",
                    models.BooleanField(
                        default=None,
                        help_text="Enable tool-result caching for this agent. Null falls back to DefaultAgentDefinitionConfig.",
                        null=True,
                    ),
                ),
                (
                    "max_retry_limit",
                    models.IntegerField(
                        default=None,
                        help_text="Max retries on transient LLM/tool failures. Null falls back to DefaultAgentDefinitionConfig.",
                        null=True,
                    ),
                ),
                (
                    "default_temperature",
                    models.FloatField(
                        default=None,
                        help_text="Sampling temperature applied when the LLMConfig leaves it unset. Null falls back to DefaultAgentDefinitionConfig.",
                        null=True,
                    ),
                ),
                (
                    "fcm_llm_config",
                    models.ForeignKey(
                        default=None,
                        help_text="Optional dedicated LLM for function/tool-call routing. Falls back to llm_config when null.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fcm_agent_definitions",
                        to="tables.llmconfig",
                    ),
                ),
                (
                    "llm_config",
                    models.ForeignKey(
                        default=None,
                        help_text="Primary LLM used for reasoning and tool selection.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_definitions",
                        to="tables.llmconfig",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization this agent belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_definitions",
                        to="tables.organization",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "name"),
                        name="unique_agent_definition_name_per_organization",
                    )
                ],
            },
        ),
    ]
