# Generated by Django 5.1.3 on 2026-05-28 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0179_alter_localhostwebhookconfig_id_and_more"),
        ("tables", "0181_merge_schedule_trigger_node"),
    ]

    operations = []
