# Generated by Django 5.1.3 on 2026-06-03 10:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0181_merge_schedule_trigger_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphraglocalsearchconfig',
            name='community_level',
            field=models.IntegerField(default=2, help_text='Max Leiden community-hierarchy level to include in context.'),
        ),
        migrations.AddField(
            model_name='llmconfig',
            name='context_window',
            field=models.IntegerField(default=16000, validators=[django.core.validators.MinValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='agentgraphrag',
            name='search_method',
            field=models.CharField(choices=[('basic', 'Basic Search'), ('local', 'Local Search'), ('global_search', 'Global Search'), ('drift_search', 'Drift Search')], default='basic', help_text='Active search method: basic, local, global_search or drift_search', max_length=20),
        ),
        migrations.CreateModel(
            name='GraphRagDriftSearchConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(blank=True, default=None, help_text='The drift search prompt to use.', null=True)),
                ('reduce_prompt', models.TextField(blank=True, default=None, help_text='The drift search reduce prompt to use.', null=True)),
                ('data_max_tokens', models.IntegerField(default=12000, help_text='The data llm maximum tokens.')),
                ('reduce_max_tokens', models.IntegerField(blank=True, default=None, help_text='The reduce llm maximum tokens response to produce.', null=True)),
                ('reduce_temperature', models.FloatField(default=0.0, help_text='The temperature to use for token generation in reduce.')),
                ('reduce_max_completion_tokens', models.IntegerField(blank=True, default=None, help_text='The reduce llm maximum tokens response to produce.', null=True)),
                ('concurrency', models.IntegerField(default=32, help_text='The number of concurrent requests.')),
                ('drift_k_followups', models.IntegerField(default=20, help_text='The number of top global results to retrieve.')),
                ('primer_folds', models.IntegerField(default=5, help_text='The number of folds for search priming.')),
                ('primer_llm_max_tokens', models.IntegerField(default=12000, help_text='The maximum number of tokens for the LLM in primer.')),
                ('n_depth', models.IntegerField(default=3, help_text='The number of drift search steps to take.')),
                ('community_level', models.IntegerField(default=2, help_text='Max Leiden community-hierarchy level to include in context.')),
                ('local_search_text_unit_prop', models.FloatField(default=0.9, help_text='The proportion of search dedicated to text units.')),
                ('local_search_community_prop', models.FloatField(default=0.1, help_text='The proportion of search dedicated to community properties.')),
                ('local_search_top_k_mapped_entities', models.IntegerField(default=10, help_text='The number of top K entities to map during local search.')),
                ('local_search_top_k_relationships', models.IntegerField(default=10, help_text='The number of top K relationships to map during local search.')),
                ('local_search_max_data_tokens', models.IntegerField(default=12000, help_text='The maximum context size in tokens for local search.')),
                ('local_search_temperature', models.FloatField(default=0.0, help_text='The temperature to use for token generation in local search.')),
                ('local_search_top_p', models.FloatField(default=1.0, help_text='The top-p value to use for token generation in local search.')),
                ('local_search_n', models.IntegerField(default=1, help_text='The number of completions to generate in local search.')),
                ('local_search_llm_max_gen_tokens', models.IntegerField(blank=True, default=None, help_text='The maximum number of generated tokens for the LLM in local search.', null=True)),
                ('local_search_llm_max_gen_completion_tokens', models.IntegerField(blank=True, default=None, help_text='The maximum number of generated tokens for the LLM in local search.', null=True)),
                ('agent', models.OneToOneField(help_text='Agent this drift search configuration belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='graph_drift_search_config', to='tables.agent')),
            ],
            options={
                'db_table': 'graph_rag_drift_search_config',
            },
        ),
        migrations.CreateModel(
            name='GraphRagGlobalSearchConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_prompt', models.TextField(blank=True, default=None, help_text='The global search mapper prompt to use.', null=True)),
                ('reduce_prompt', models.TextField(blank=True, default=None, help_text='The global search reducer prompt to use.', null=True)),
                ('knowledge_prompt', models.TextField(blank=True, default=None, help_text='The global search general prompt to use.', null=True)),
                ('max_context_tokens', models.IntegerField(default=12000, help_text='The maximum context size in tokens.')),
                ('data_max_tokens', models.IntegerField(default=12000, help_text='The data llm maximum tokens.')),
                ('map_max_length', models.IntegerField(default=1000, help_text='The map llm maximum response length in words.')),
                ('reduce_max_length', models.IntegerField(default=2000, help_text='The reduce llm maximum response length in words.')),
                ('dynamic_community_selection', models.BooleanField(default=False, help_text='Enable dynamic community selection at query time.')),
                ('dynamic_search_threshold', models.IntegerField(default=1, help_text='Rating threshold to include a community report.')),
                ('dynamic_search_keep_parent', models.BooleanField(default=False, help_text='Keep parent community if any of the child communities are relevant.')),
                ('dynamic_search_num_repeats', models.IntegerField(default=1, help_text='Number of times to rate the same community report.')),
                ('dynamic_search_use_summary', models.BooleanField(default=False, help_text='Use community summary instead of full_context.')),
                ('dynamic_search_max_level', models.IntegerField(default=2, help_text='The maximum level of community hierarchy to consider if none of the processed communities are relevant.')),
                ('agent', models.OneToOneField(help_text='Agent this global search configuration belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='graph_global_search_config', to='tables.agent')),
            ],
            options={
                'db_table': 'graph_rag_global_search_config',
            },
        ),
    ]
