# Generated by Django 5.1.3 on 2026-05-25 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0177_graph_rag_global_and_drift_search"),
        ("tables", "0181_merge_schedule_trigger_node"),
    ]

    operations = []
