# Generated by Django 5.1.3 on 2026-06-04 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0181_graphsessionmessage_parent_subgraph_execution_id_and_more"),
        ("tables", "0182_drop_llmnode"),
    ]

    operations = []
