# Generated by Django 5.1.3 on 2026-05-22 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0182_defaultagentdefinitionconfig_agentdefinition"),
    ]

    operations = [
        migrations.CreateModel(
            name="Surface",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Stable identifier unique within the organization. Used as the user-facing name for this surface.",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional human-readable description shown in the UI. Empty string means no description.",
                    ),
                ),
                (
                    "additional_instructions",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Free-form text appended to the agent prompt when this surface is resolved. Empty string means no extra instructions.",
                    ),
                ),
                (
                    "allowed_agents",
                    models.ManyToManyField(
                        blank=True,
                        help_text="AgentDefinition instances permitted to select this surface. Empty set means any agent in the organization may use it.",
                        related_name="allowed_surfaces",
                        to="tables.agentdefinition",
                    ),
                ),
                (
                    "knowledge_collections",
                    models.ManyToManyField(
                        blank=True,
                        help_text="RAG SourceCollection instances this surface grants access to.",
                        related_name="surfaces",
                        to="tables.sourcecollection",
                    ),
                ),
                (
                    "mcp_tools",
                    models.ManyToManyField(
                        blank=True,
                        help_text="MCP tool instances exposed by this surface. Auth and URL are stored on McpTool directly.",
                        related_name="surfaces",
                        to="tables.mcptool",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization this surface belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="surfaces",
                        to="tables.organization",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional parent surface. Effective resources are the union of this surface and its full parent chain (root first). Null means no parent.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="tables.surface",
                    ),
                ),
                (
                    "python_code_tool_configs",
                    models.ManyToManyField(
                        blank=True,
                        help_text="PythonCodeToolConfig instances exposed by this surface.",
                        related_name="surfaces",
                        to="tables.pythoncodetoolconfig",
                    ),
                ),
                (
                    "tool_configs",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Standard ToolConfig instances (configured tool invocations) exposed by this surface.",
                        related_name="surfaces",
                        to="tables.toolconfig",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SurfaceStorageFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this file was attached to the surface.",
                    ),
                ),
                (
                    "storage_file",
                    models.ForeignKey(
                        help_text="Object-storage file granted by this surface.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tables.storagefile",
                    ),
                ),
                (
                    "surface",
                    models.ForeignKey(
                        help_text="Surface this file attachment belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tables.surface",
                    ),
                ),
            ],
            options={
                "unique_together": {("surface", "storage_file")},
            },
        ),
        migrations.AddField(
            model_name="surface",
            name="storage_files",
            field=models.ManyToManyField(
                blank=True,
                help_text="Object-storage files this surface grants access to. Linked via SurfaceStorageFile through-table.",
                related_name="surfaces",
                through="tables.SurfaceStorageFile",
                to="tables.storagefile",
            ),
        ),
        migrations.AddConstraint(
            model_name="surface",
            constraint=models.UniqueConstraint(
                fields=("organization", "name"),
                name="unique_surface_name_per_organization",
            ),
        ),
    ]
