# Generated by Django 5.1.3 on 2026-05-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0182_naiveragdocumentconfig_error_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="graphrag",
            name="rag_status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="new",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="sourcecollection",
            name="status",
            field=models.CharField(
                choices=[("empty", "Empty"), ("non_empty", "Non Empty")],
                default="empty",
                max_length=20,
            ),
        ),
    ]
