# Generated by Django 5.1.3 on 2026-05-27 14:04

import django.db.models.deletion
import tables.models.base_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0182_defaultagentdefinitionconfig_agentdefinition"),
    ]

    operations = [
        migrations.CreateModel(
            name="InlineSurface",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "allowed_knowledge_collections",
                    models.ManyToManyField(
                        blank=True,
                        help_text="SourceCollection instances explicitly allowed by this surface.",
                        related_name="+",
                        to="tables.sourcecollection",
                    ),
                ),
                (
                    "allowed_mcp_tools",
                    models.ManyToManyField(
                        blank=True,
                        help_text="McpTool instances explicitly allowed by this surface.",
                        related_name="+",
                        to="tables.mcptool",
                    ),
                ),
                (
                    "allowed_python_tools",
                    models.ManyToManyField(
                        blank=True,
                        help_text="PythonCodeToolConfig instances explicitly allowed by this surface.",
                        related_name="+",
                        to="tables.pythoncodetoolconfig",
                    ),
                ),
                (
                    "allowed_storage_files",
                    models.ManyToManyField(
                        blank=True,
                        help_text="StorageFile instances explicitly allowed by this surface.",
                        related_name="+",
                        to="tables.storagefile",
                    ),
                ),
                (
                    "disabled_knowledge_collections",
                    models.ManyToManyField(
                        blank=True,
                        help_text="SourceCollection instances explicitly denied by this surface. Deny wins over any allow.",
                        related_name="+",
                        to="tables.sourcecollection",
                    ),
                ),
                (
                    "disabled_mcp_tools",
                    models.ManyToManyField(
                        blank=True,
                        help_text="McpTool instances explicitly denied by this surface. Deny wins over any allow.",
                        related_name="+",
                        to="tables.mcptool",
                    ),
                ),
                (
                    "disabled_python_tools",
                    models.ManyToManyField(
                        blank=True,
                        help_text="PythonCodeToolConfig instances explicitly denied by this surface. Deny wins over any allow.",
                        related_name="+",
                        to="tables.pythoncodetoolconfig",
                    ),
                ),
                (
                    "disabled_storage_files",
                    models.ManyToManyField(
                        blank=True,
                        help_text="StorageFile instances explicitly denied by this surface. Deny wins over any allow.",
                        related_name="+",
                        to="tables.storagefile",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization this surface belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tables.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Surface",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Stable identifier unique within the organization. Used as the user-facing name for this surface.",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional human-readable description shown in the UI. Empty string means no description.",
                    ),
                ),
                (
                    "additional_instructions",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Free-form text appended to the agent prompt when this surface is resolved. Empty string means no extra instructions.",
                    ),
                ),
                (
                    "allowed_agents",
                    models.ManyToManyField(
                        blank=True,
                        help_text="AgentDefinition instances permitted to select this surface. Empty set means any agent in the organization may use it.",
                        related_name="allowed_surfaces",
                        to="tables.agentdefinition",
                    ),
                ),
                (
                    "allowed_knowledge_collections",
                    models.ManyToManyField(
                        blank=True,
                        help_text="SourceCollection instances explicitly allowed by this surface.",
                        related_name="+",
                        to="tables.sourcecollection",
                    ),
                ),
                (
                    "allowed_mcp_tools",
                    models.ManyToManyField(
                        blank=True,
                        help_text="McpTool instances explicitly allowed by this surface.",
                        related_name="+",
                        to="tables.mcptool",
                    ),
                ),
                (
                    "allowed_python_tools",
                    models.ManyToManyField(
                        blank=True,
                        help_text="PythonCodeToolConfig instances explicitly allowed by this surface.",
                        related_name="+",
                        to="tables.pythoncodetoolconfig",
                    ),
                ),
                (
                    "allowed_storage_files",
                    models.ManyToManyField(
                        blank=True,
                        help_text="StorageFile instances explicitly allowed by this surface.",
                        related_name="+",
                        to="tables.storagefile",
                    ),
                ),
                (
                    "disabled_knowledge_collections",
                    models.ManyToManyField(
                        blank=True,
                        help_text="SourceCollection instances explicitly denied by this surface. Deny wins over any allow.",
                        related_name="+",
                        to="tables.sourcecollection",
                    ),
                ),
                (
                    "disabled_mcp_tools",
                    models.ManyToManyField(
                        blank=True,
                        help_text="McpTool instances explicitly denied by this surface. Deny wins over any allow.",
                        related_name="+",
                        to="tables.mcptool",
                    ),
                ),
                (
                    "disabled_python_tools",
                    models.ManyToManyField(
                        blank=True,
                        help_text="PythonCodeToolConfig instances explicitly denied by this surface. Deny wins over any allow.",
                        related_name="+",
                        to="tables.pythoncodetoolconfig",
                    ),
                ),
                (
                    "disabled_storage_files",
                    models.ManyToManyField(
                        blank=True,
                        help_text="StorageFile instances explicitly denied by this surface. Deny wins over any allow.",
                        related_name="+",
                        to="tables.storagefile",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization this surface belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tables.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AgentNode",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "id",
                    models.BigIntegerField(
                        db_default=tables.models.base_models.NextVal(
                            models.Value("tables_global_node_seq")
                        ),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("node_name", models.CharField(blank=True, max_length=255)),
                ("input_map", models.JSONField(default=dict)),
                (
                    "output_variable_path",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "agent_definition",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text="AgentDefinition that executes this node's tasks. Null allowed — runtime surfaces a missing-agent error.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_nodes",
                        to="tables.agentdefinition",
                    ),
                ),
                (
                    "graph",
                    models.ForeignKey(
                        help_text="Graph this agent node belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_node_list",
                        to="tables.graph",
                    ),
                ),
                (
                    "inline_surface",
                    models.OneToOneField(
                        blank=True,
                        default=None,
                        help_text="Node-local inline surface carrying ad-hoc tools/files/knowledge for this node only. Null until assigned.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="tables.inlinesurface",
                    ),
                ),
                (
                    "surfaces",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Reusable Surface bundles whose resources are merged at runtime and shared across all sub-tasks.",
                        related_name="agent_nodes",
                        to="tables.surface",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="agentdefinition",
            name="default_surface",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Surface applied to this agent by default when a node does not specify one. Null means no default surface.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_for_agents",
                to="tables.surface",
            ),
        ),
        migrations.CreateModel(
            name="TaskNode",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "id",
                    models.BigIntegerField(
                        db_default=tables.models.base_models.NextVal(
                            models.Value("tables_global_node_seq")
                        ),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("node_name", models.CharField(blank=True, max_length=255)),
                ("input_map", models.JSONField(default=dict)),
                (
                    "output_variable_path",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "instructions",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Prompt text passed to the agent for this task. Empty means no task-level instructions.",
                    ),
                ),
                (
                    "output_schema",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON schema the task output must conform to. Empty dict means no schema enforcement.",
                    ),
                ),
                (
                    "remember_output",
                    models.BooleanField(
                        default=False,
                        help_text="If True, task output is memoized in session state and reused on re-runs within the same session.",
                    ),
                ),
                (
                    "agent_definition",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text="AgentDefinition that executes this task. Null allowed — runtime surfaces a missing-agent error.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="task_nodes",
                        to="tables.agentdefinition",
                    ),
                ),
                (
                    "graph",
                    models.ForeignKey(
                        help_text="Graph this task node belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_node_list",
                        to="tables.graph",
                    ),
                ),
                (
                    "inline_surface",
                    models.OneToOneField(
                        blank=True,
                        default=None,
                        help_text="Node-local inline surface carrying ad-hoc tools/files/knowledge for this node only. Null until assigned.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="tables.inlinesurface",
                    ),
                ),
                (
                    "surfaces",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Reusable Surface bundles whose resources are merged at runtime for this task.",
                        related_name="task_nodes",
                        to="tables.surface",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AgentNodeTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.PositiveIntegerField(
                        help_text="Zero-based position within the parent agent node. Tasks execute in ascending order."
                    ),
                ),
                (
                    "instructions",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Prompt text passed to the agent for this sub-task. Empty means no task-level instructions.",
                    ),
                ),
                (
                    "output_schema",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Optional JSON schema the task output must conform to. Empty dict = no enforcement.",
                    ),
                ),
                (
                    "agent_node",
                    models.ForeignKey(
                        help_text="Parent AgentNode this task belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="tables.agentnode",
                    ),
                ),
                (
                    "context_tasks",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Earlier sibling tasks whose outputs are injected as context for this task.",
                        related_name="dependent_tasks",
                        to="tables.agentnodetask",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("agent_node", "order"),
                        name="uniq_agentnodetask_node_order",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="surface",
            constraint=models.UniqueConstraint(
                fields=("organization", "name"), name="uniq_surface_org_name"
            ),
        ),
    ]
