# Generated by Django 5.1.3 on 2026-05-27 14:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0182_merge_graph_gar_drift_global_search"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmconfig",
            name="context_window",
            field=models.IntegerField(
                default=16000,
                validators=[django.core.validators.MinValueValidator(1000)],
            ),
        ),
    ]
