# Generated by Django 5.1.3 on 2026-05-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0182_merge_20260528_1247"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhooktrigger",
            name="provider_type",
            field=models.CharField(
                blank=True,
                choices=[("ngrok", "Ngrok"), ("localhost", "Localhost")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="localhostwebhookconfig",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="ngrokwebhookconfig",
            name="auth_token",
            field=models.CharField(
                help_text="Token from dashboard.ngrok.com", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="ngrokwebhookconfig",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
