# Generated by Django 5.1.3 on 2026-06-03 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0182_drop_llmnode"),
        ("tables", "0182_graph_save_version"),
    ]

    operations = []
