# Generated by Django 5.1.3 on 2026-05-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0183_alter_graphrag_rag_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="naiveragdocumentconfig",
            name="indexed_additional_params",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="naiveragdocumentconfig",
            name="indexed_chunk_overlap",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="naiveragdocumentconfig",
            name="indexed_chunk_size",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="naiveragdocumentconfig",
            name="indexed_chunk_strategy",
            field=models.CharField(
                blank=True,
                choices=[
                    ("token", "Token"),
                    ("character", "Character"),
                    ("markdown", "Markdown"),
                    ("json", "Json"),
                    ("html", "Html"),
                    ("csv", "Csv"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
