# Generated by Django 5.1.3 on 2026-06-02 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0183_inlinesurface_surface_agentnode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagefile',
            name='is_system',
            field=models.BooleanField(default=False, help_text='True for files written by the platform itself (e.g. session outputs). Not filtered yet.'),
        ),
        migrations.AddField(
            model_name='storagefile',
            name='item_type',
            field=models.CharField(choices=[('file', 'file'), ('folder', 'folder')], default='file', help_text='Whether this row represents a file or a folder.', max_length=6),
        ),
        migrations.AddField(
            model_name='storagefile',
            name='parent_path',
            field=models.CharField(default='', help_text="Immediate parent directory path ending in '/', or '' for root entries. Enables single-level listing.", max_length=1000),
        ),
        migrations.AddField(
            model_name='storagefile',
            name='s3_modified',
            field=models.DateTimeField(blank=True, help_text='LastModified timestamp from the storage backend. NULL when unknown.', null=True),
        ),
        migrations.AddField(
            model_name='storagefile',
            name='size',
            field=models.BigIntegerField(blank=True, help_text='File size in bytes. NULL for folders or when size is unknown.', null=True),
        ),
        migrations.AlterField(
            model_name='storagefile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when this DB row was first created.'),
        ),
        migrations.AlterField(
            model_name='storagefile',
            name='name',
            field=models.CharField(help_text='Last path segment, denormalized for search.', max_length=255),
        ),
        migrations.AlterField(
            model_name='storagefile',
            name='org',
            field=models.ForeignKey(help_text='Organization that owns this storage entry.', on_delete=django.db.models.deletion.CASCADE, related_name='storage_files', to='tables.organization'),
        ),
        migrations.AlterField(
            model_name='storagefile',
            name='path',
            field=models.CharField(help_text="Org-relative path, never starts with '/'. Folders end with '/'.", max_length=1000),
        ),
        migrations.AlterField(
            model_name='storagefile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp of the last update to this row.'),
        ),
        migrations.AddIndex(
            model_name='storagefile',
            index=models.Index(fields=['org', 'parent_path'], name='tables_stor_org_id_2ca27b_idx'),
        ),
    ]
