# Generated by Django 5.1.3 on 2026-06-04 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0183_merge_0182_drop_llmnode_0182_graph_save_version"),
        ("tables", "0183_merge_20260604_1425"),
    ]

    operations = []
