# Generated by Django 5.1.3 on 2026-05-24 10:45

import django.db.models.deletion
import tables.models.base_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0183_surface_surfacestoragefile_surface_storage_files_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InlineSurface",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TaskNode",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "id",
                    models.BigIntegerField(
                        db_default=tables.models.base_models.NextVal(
                            models.Value("tables_global_node_seq")
                        ),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("node_name", models.CharField(blank=True, max_length=255)),
                ("input_map", models.JSONField(default=dict)),
                (
                    "output_variable_path",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "instructions",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Prompt text passed to the agent for this task. Empty means no task-level instructions.",
                    ),
                ),
                (
                    "output_schema",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON schema the task output must conform to. Empty dict means no schema enforcement.",
                    ),
                ),
                (
                    "remember_output",
                    models.BooleanField(
                        default=False,
                        help_text="If True, task output is memoized in session state and reused on re-runs within the same session.",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterUniqueTogether(
            name="surfacestoragefile",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="surfacestoragefile",
            name="storage_file",
        ),
        migrations.RemoveField(
            model_name="surfacestoragefile",
            name="surface",
        ),
        migrations.RemoveConstraint(
            model_name="surface",
            name="unique_surface_name_per_organization",
        ),
        migrations.AlterField(
            model_name="surface",
            name="knowledge_collections",
            field=models.ManyToManyField(
                blank=True,
                help_text="RAG SourceCollection instances this surface grants access to.",
                related_name="%(class)ss",
                to="tables.sourcecollection",
            ),
        ),
        migrations.AlterField(
            model_name="surface",
            name="mcp_tools",
            field=models.ManyToManyField(
                blank=True,
                help_text="MCP tool instances exposed by this surface. Auth and URL are stored on McpTool directly.",
                related_name="%(class)ss",
                to="tables.mcptool",
            ),
        ),
        migrations.AlterField(
            model_name="surface",
            name="organization",
            field=models.ForeignKey(
                help_text="Organization this surface belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="tables.organization",
            ),
        ),
        migrations.AlterField(
            model_name="surface",
            name="python_code_tool_configs",
            field=models.ManyToManyField(
                blank=True,
                help_text="PythonCodeToolConfig instances exposed by this surface.",
                related_name="%(class)ss",
                to="tables.pythoncodetoolconfig",
            ),
        ),
        migrations.AlterField(
            model_name="surface",
            name="storage_files",
            field=models.ManyToManyField(
                blank=True,
                help_text="Object-storage files this surface grants access to.",
                related_name="%(class)ss",
                to="tables.storagefile",
            ),
        ),
        migrations.AlterField(
            model_name="surface",
            name="tool_configs",
            field=models.ManyToManyField(
                blank=True,
                help_text="Standard ToolConfig instances (configured tool invocations) exposed by this surface.",
                related_name="%(class)ss",
                to="tables.toolconfig",
            ),
        ),
        migrations.AddConstraint(
            model_name="surface",
            constraint=models.UniqueConstraint(
                fields=("organization", "name"), name="uniq_surface_org_name"
            ),
        ),
        migrations.AddField(
            model_name="inlinesurface",
            name="knowledge_collections",
            field=models.ManyToManyField(
                blank=True,
                help_text="RAG SourceCollection instances this surface grants access to.",
                related_name="%(class)ss",
                to="tables.sourcecollection",
            ),
        ),
        migrations.AddField(
            model_name="inlinesurface",
            name="mcp_tools",
            field=models.ManyToManyField(
                blank=True,
                help_text="MCP tool instances exposed by this surface. Auth and URL are stored on McpTool directly.",
                related_name="%(class)ss",
                to="tables.mcptool",
            ),
        ),
        migrations.AddField(
            model_name="inlinesurface",
            name="organization",
            field=models.ForeignKey(
                help_text="Organization this surface belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="tables.organization",
            ),
        ),
        migrations.AddField(
            model_name="inlinesurface",
            name="python_code_tool_configs",
            field=models.ManyToManyField(
                blank=True,
                help_text="PythonCodeToolConfig instances exposed by this surface.",
                related_name="%(class)ss",
                to="tables.pythoncodetoolconfig",
            ),
        ),
        migrations.AddField(
            model_name="inlinesurface",
            name="storage_files",
            field=models.ManyToManyField(
                blank=True,
                help_text="Object-storage files this surface grants access to.",
                related_name="%(class)ss",
                to="tables.storagefile",
            ),
        ),
        migrations.AddField(
            model_name="inlinesurface",
            name="tool_configs",
            field=models.ManyToManyField(
                blank=True,
                help_text="Standard ToolConfig instances (configured tool invocations) exposed by this surface.",
                related_name="%(class)ss",
                to="tables.toolconfig",
            ),
        ),
        migrations.AddField(
            model_name="tasknode",
            name="agent_definition",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="AgentDefinition that executes this task. Null allowed — runtime surfaces a missing-agent error.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="task_nodes",
                to="tables.agentdefinition",
            ),
        ),
        migrations.AddField(
            model_name="tasknode",
            name="graph",
            field=models.ForeignKey(
                help_text="Graph this task node belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_node_list",
                to="tables.graph",
            ),
        ),
        migrations.AddField(
            model_name="tasknode",
            name="inline_surface",
            field=models.OneToOneField(
                blank=True,
                default=None,
                help_text="Node-local inline surface carrying ad-hoc tools/files/knowledge for this node only. Null until assigned.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="tables.inlinesurface",
            ),
        ),
        migrations.AddField(
            model_name="tasknode",
            name="surfaces",
            field=models.ManyToManyField(
                blank=True,
                help_text="Reusable Surface bundles whose resources are merged at runtime for this task.",
                related_name="task_nodes",
                to="tables.surface",
            ),
        ),
        migrations.DeleteModel(
            name="SurfaceStorageFile",
        ),
    ]
