# Generated by Django 5.1.3 on 2026-06-02 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0183_seed_builtin_role_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="org",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="tables.organization",
            ),
        ),
        migrations.AddField(
            model_name="crew",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="crew",
            name="org",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="tables.organization",
            ),
        ),
        migrations.AddField(
            model_name="graph",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="graph",
            name="org",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="tables.organization",
            ),
        ),
        migrations.AlterField(
            model_name="graph",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AddIndex(
            model_name="agent",
            index=models.Index(fields=["org"], name="tables_agen_org_id_478f96_idx"),
        ),
        migrations.AddIndex(
            model_name="crew",
            index=models.Index(fields=["org"], name="tables_crew_org_id_3e1d1e_idx"),
        ),
        migrations.AddIndex(
            model_name="graph",
            index=models.Index(fields=["org"], name="tables_grap_org_id_b7653b_idx"),
        ),
        migrations.AddConstraint(
            model_name="graph",
            constraint=models.UniqueConstraint(
                fields=("org", "name"), name="unique_graph_name_per_org"
            ),
        ),
    ]
