# Generated by Django 5.1.3 on 2026-06-08 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0184_merge_20260604_1512"),
        ("tables", "0184_merge_rbac_roles_and_permissions"),
    ]

    operations = []
