# Generated by Django 5.1.3 on 2026-05-24 12:38

import django.db.models.deletion
import tables.models.base_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0184_inlinesurface_tasknode_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentNode",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "id",
                    models.BigIntegerField(
                        db_default=tables.models.base_models.NextVal(
                            models.Value("tables_global_node_seq")
                        ),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("node_name", models.CharField(blank=True, max_length=255)),
                ("input_map", models.JSONField(default=dict)),
                (
                    "output_variable_path",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "agent_definition",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text="AgentDefinition that executes this node's tasks. Null allowed — runtime surfaces a missing-agent error.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_nodes",
                        to="tables.agentdefinition",
                    ),
                ),
                (
                    "graph",
                    models.ForeignKey(
                        help_text="Graph this agent node belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_node_list",
                        to="tables.graph",
                    ),
                ),
                (
                    "inline_surface",
                    models.OneToOneField(
                        blank=True,
                        default=None,
                        help_text="Node-local inline surface carrying ad-hoc tools/files/knowledge for this node only. Null until assigned.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="tables.inlinesurface",
                    ),
                ),
                (
                    "surfaces",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Reusable Surface bundles whose resources are merged at runtime and shared across all sub-tasks.",
                        related_name="agent_nodes",
                        to="tables.surface",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AgentNodeTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.PositiveIntegerField(
                        help_text="Zero-based position within the parent agent node. Tasks execute in ascending order."
                    ),
                ),
                (
                    "instructions",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Prompt text passed to the agent for this sub-task. Empty means no task-level instructions.",
                    ),
                ),
                (
                    "output_schema",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Optional JSON schema the task output must conform to. Empty dict = no enforcement.",
                    ),
                ),
                (
                    "agent_node",
                    models.ForeignKey(
                        help_text="Parent AgentNode this task belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="tables.agentnode",
                    ),
                ),
                (
                    "context_tasks",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Earlier sibling tasks whose outputs are injected as context for this task.",
                        related_name="dependent_tasks",
                        to="tables.agentnodetask",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("agent_node", "order"),
                        name="uniq_agentnodetask_node_order",
                    )
                ],
            },
        ),
    ]
