# Generated by Django 5.1.3 on 2026-05-19 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0180_merge_user_profile_migrations_2"),
        ("tables", "0184_flow_assistant_message"),
    ]

    operations = []
