# Generated by Django 5.1.3 on 2026-06-09 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0182_merge_20260526_1446"),
        ("tables", "0185_merge_rbac_roles_and_permissions_2"),
    ]

    operations = []
