# Generated by Django 5.1.7 on 2026-06-10 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0182_naiveragdocumentconfig_error_code_and_more"),
        ("tables", "0185_merge_rbac_roles_and_permissions_2"),
    ]

    operations = []
