# Generated by Django 5.1.7 on 2026-06-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0185_merge_rbac_roles_and_permissions_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='naiveragdocumentconfig',
            name='error_code',
            field=models.CharField(choices=[('chunking_failed', 'Chunking Failed'), ('embedding_failed', 'Embedding Failed'), ('embedder_auth', 'Embedder Auth'), ('embedder_rate_limit', 'Embedder Rate Limit'), ('unknown', 'Unknown'), ('none', 'None')], default='none', max_length=32),
        ),
        migrations.AddField(
            model_name='naiveragdocumentconfig',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='naiveragdocumentconfig',
            name='failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='naiveragdocumentconfig',
            name='indexed_additional_params',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='naiveragdocumentconfig',
            name='indexed_chunk_overlap',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='naiveragdocumentconfig',
            name='indexed_chunk_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='naiveragdocumentconfig',
            name='indexed_chunk_strategy',
            field=models.CharField(blank=True, choices=[('token', 'Token'), ('character', 'Character'), ('markdown', 'Markdown'), ('json', 'Json'), ('html', 'Html'), ('csv', 'Csv')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='documentcontent',
            name='content',
            field=models.BinaryField(help_text='Binary file content (max 20MB)'),
        ),
        migrations.AlterField(
            model_name='sourcecollection',
            name='status',
            field=models.CharField(choices=[('empty', 'Empty'), ('non_empty', 'Non Empty')], default='empty', max_length=20),
        ),
    ]
