# Generated by Django 5.1.3 on 2026-06-05 14:12

import django.db.models.deletion
from django.db import migrations, models


def migrate_prompt_id_to_fk(apps, schema_editor):
    ClassificationConditionGroup = apps.get_model(
        "tables", "ClassificationConditionGroup"
    )
    ClassificationDecisionTablePrompt = apps.get_model(
        "tables", "ClassificationDecisionTablePrompt"
    )

    groups = ClassificationConditionGroup.objects.filter(
        prompt_id__isnull=False
    ).select_related("classification_decision_table_node__graph")

    for group in groups:
        graph = group.classification_decision_table_node.graph
        try:
            prompt = ClassificationDecisionTablePrompt.objects.get(
                cdt_node__graph=graph,
                prompt_key=group.prompt_id,
            )
            group.prompt_fk = prompt
            group.save(update_fields=["prompt_fk"])
        except ClassificationDecisionTablePrompt.DoesNotExist:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0185_merge_main_into_demo_migrations"),
    ]

    operations = [
        # Step 1: add the FK using a temporary field name "prompt_fk" so Django
        # stores it as column "prompt_fk_id", leaving the old "prompt_id" varchar
        # column untouched while both columns coexist.
        migrations.AddField(
            model_name="classificationconditiongroup",
            name="prompt_fk",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="condition_groups",
                to="tables.classificationdecisiontableprompt",
            ),
        ),
        # Step 2: copy data from old varchar column into the new FK column.
        migrations.RunPython(
            migrate_prompt_id_to_fk,
            reverse_code=migrations.RunPython.noop,
        ),
        # Step 3: drop old varchar column.
        migrations.RemoveField(
            model_name="classificationconditiongroup",
            name="prompt_id",
        ),
        # Step 4: rename field "prompt_fk" → "prompt" (renames DB column
        # "prompt_fk_id" → "prompt_id").
        migrations.RenameField(
            model_name="classificationconditiongroup",
            old_name="prompt_fk",
            new_name="prompt",
        ),
        migrations.AlterField(
            model_name="flowassistant",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="flowassistantconversation",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="flowassistantconversation",
            name="last_message_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
