# Generated by Django 5.1.3 on 2026-06-08 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0184_merge_20260604_1512"),
        ("tables", "0185_merge_main_into_demo_migrations"),
    ]

    operations = []
