# Generated by Django 5.1.3 on 2026-06-08 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0185_merge_rbac_roles_and_permissions_2"),
        ("tables", "0186_core_org_not_null"),
    ]

    operations = []
