# Generated by Django 5.1.7 on 2026-06-12 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0182_merge_20260528_1247"),
        ("tables", "0186_tool_configuration_for_0182_and_0185"),
    ]

    operations = []
