# Generated by Django 5.1.3 on 2026-06-09 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0185_merge_rbac_roles_and_permissions_2"),
        ("tables", "0186_merge_20260608_1013"),
    ]

    operations = []
