# Generated by Django 5.1.3 on 2026-06-16 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0186_merge_20260608_1013"),
        ("tables", "0186_remove_classificationconditiongroup_prompt_id_and_more"),
    ]

    operations = []
