# Generated by Django 5.1.7 on 2026-06-13 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0182_graph_search_params_and_llmconfig_context_window"),
        ("tables", "0186_tool_configuration_for_0182_and_0185"),
    ]

    operations = []
