# Generated by Django 5.1.3 on 2026-06-18 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0186_tool_configuration_for_0182_and_0185"),
        ("tables", "0187_merge_demo_migrations"),
    ]

    operations = []
