# Generated by Django 5.1.7 on 2026-06-18 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0186_tool_configuration_for_0182_and_0185'),
        ('tables', '0187_naiverag_chunk_fk_on_delete_cascade'),
    ]

    operations = [
    ]
