# Generated by Django 5.1.3 on 2026-06-11 14:21

from django.db import migrations, models

from tables.constants.organization_constants import DEFAULT_ORGANIZATION_NAME


def stamp_default_org(apps, schema_editor):
    organization_model = apps.get_model("tables", "Organization")
    org = organization_model.objects.filter(
        name__iexact=DEFAULT_ORGANIZATION_NAME
    ).first()
    if org is None:
        return  # nothing bootstrapped yet (e.g. brand-new empty install path)
    org.is_default = True
    org.save(update_fields=["is_default"])


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0187_merge_rbac_org_scoped_migrations"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="organization",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("is_default",),
                name="rbac_organization_single_default",
            ),
        ),
        migrations.RunPython(stamp_default_org, migrations.RunPython.noop),
    ]
