# Generated by Django 5.1.3 on 2026-06-17 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "tables",
            "0187_merge_change_classificationconditiongroup_prompt_id_field_type",
        ),
        ("tables", "0187_merge_demo_migrations"),
    ]

    operations = []
