# Generated by Django 5.1.3 on 2026-06-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0188_merge_20260618_1643"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flowassistant",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="flowassistantconversation",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="flowassistantconversation",
            name="last_message_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
