# Generated by Django 5.1.3 on 2026-05-29 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0188_deduplicate_webhook_triggers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twiliochannel',
            name='ngrok_config',
        ),
        migrations.AddField(
            model_name='twiliochannel',
            name='webhook_trigger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='twilio_channels', to='tables.webhooktrigger'),
        ),
    ]
