# Generated by Django 5.1.3 on 2026-06-15 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0188_organization_is_default_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="embeddingconfig",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="embeddingconfig",
            name="org",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="tables.organization",
            ),
        ),
        migrations.AddField(
            model_name="embeddingmodel",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="embeddingmodel",
            name="org",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="tables.organization",
            ),
        ),
        migrations.AddField(
            model_name="llmconfig",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="llmconfig",
            name="org",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="tables.organization",
            ),
        ),
        migrations.AddField(
            model_name="llmmodel",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="llmmodel",
            name="org",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="tables.organization",
            ),
        ),
        migrations.AddField(
            model_name="realtimeconfig",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="realtimeconfig",
            name="org",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="tables.organization",
            ),
        ),
        migrations.AddField(
            model_name="realtimemodel",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="realtimemodel",
            name="org",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="tables.organization",
            ),
        ),
        migrations.AddField(
            model_name="realtimetranscriptionconfig",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="realtimetranscriptionconfig",
            name="org",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="tables.organization",
            ),
        ),
        migrations.AddField(
            model_name="realtimetranscriptionmodel",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="realtimetranscriptionmodel",
            name="org",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="tables.organization",
            ),
        ),
        migrations.AlterField(
            model_name="embeddingconfig",
            name="custom_name",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="llmconfig",
            name="custom_name",
            field=models.TextField(),
        ),
        migrations.AddIndex(
            model_name="embeddingconfig",
            index=models.Index(fields=["org"], name="tables_embe_org_id_2a1831_idx"),
        ),
        migrations.AddIndex(
            model_name="embeddingmodel",
            index=models.Index(fields=["org"], name="tables_embe_org_id_4cb2cf_idx"),
        ),
        migrations.AddIndex(
            model_name="llmconfig",
            index=models.Index(fields=["org"], name="tables_llmc_org_id_620637_idx"),
        ),
        migrations.AddIndex(
            model_name="llmmodel",
            index=models.Index(fields=["org"], name="tables_llmm_org_id_b6b1a6_idx"),
        ),
        migrations.AddIndex(
            model_name="realtimeconfig",
            index=models.Index(fields=["org"], name="tables_real_org_id_6a4ecf_idx"),
        ),
        migrations.AddIndex(
            model_name="realtimemodel",
            index=models.Index(fields=["org"], name="tables_real_org_id_5398b2_idx"),
        ),
        migrations.AddIndex(
            model_name="realtimetranscriptionconfig",
            index=models.Index(fields=["org"], name="tables_real_org_id_487b4f_idx"),
        ),
        migrations.AddIndex(
            model_name="realtimetranscriptionmodel",
            index=models.Index(fields=["org"], name="tables_real_org_id_1422b3_idx"),
        ),
        migrations.AddConstraint(
            model_name="embeddingconfig",
            constraint=models.UniqueConstraint(
                fields=("org", "custom_name"),
                name="unique_embeddingconfig_name_per_org",
            ),
        ),
        migrations.AddConstraint(
            model_name="llmconfig",
            constraint=models.UniqueConstraint(
                fields=("org", "custom_name"), name="unique_llmconfig_name_per_org"
            ),
        ),
    ]
