# Generated by Django 5.1.7 on 2026-06-18 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0188_merge_20260618_1627'),
        ('tables', '0188_merge_20260618_1643'),
    ]

    operations = [
    ]
