# Generated by Django 5.1.3 on 2026-06-05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tables", "0183_merge_20260604_1425"),
        ("tables", "0189_twilio_channel_use_webhook_trigger"),
    ]

    operations = []
