# Generated by Django 5.1.3 on 2026-06-17 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0191_llm_configs_org_not_null"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="pythoncodetoolconfig",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="mcptool",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="mcptool",
            name="org",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="tables.organization",
            ),
        ),
        migrations.AddField(
            model_name="pythoncodetool",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pythoncodetool",
            name="org",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="tables.organization",
            ),
        ),
        migrations.AddField(
            model_name="pythoncodetoolconfig",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pythoncodetoolconfig",
            name="org",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="tables.organization",
            ),
        ),
        migrations.AlterField(
            model_name="mcptool",
            name="name",
            field=models.CharField(
                help_text="Unique name for mcp configuration", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="pythoncodetool",
            name="name",
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name="pythoncodetoolconfig",
            unique_together={("org", "tool", "name")},
        ),
        migrations.AddIndex(
            model_name="mcptool",
            index=models.Index(fields=["org"], name="tables_mcpt_org_id_eea9ba_idx"),
        ),
        migrations.AddIndex(
            model_name="pythoncodetool",
            index=models.Index(fields=["org"], name="tables_pyth_org_id_947bd6_idx"),
        ),
        migrations.AddIndex(
            model_name="pythoncodetoolconfig",
            index=models.Index(fields=["org"], name="tables_pyth_org_id_955ff9_idx"),
        ),
        migrations.AddConstraint(
            model_name="mcptool",
            constraint=models.UniqueConstraint(
                fields=("org", "name"), name="unique_mcptool_name_per_org"
            ),
        ),
        migrations.AddConstraint(
            model_name="pythoncodetool",
            constraint=models.UniqueConstraint(
                fields=("org", "name"), name="unique_pythoncodetool_name_per_org"
            ),
        ),
    ]
