#!/usr/bin/env python3
"""
setup_prod.py — Interactively fill in production variables
based on prod/prod.env.manifest.yaml → prod/prod.env
"""

import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    import subprocess

    subprocess.check_call([sys.executable, "-m", "pip", "install", "pyyaml", "-q"])
    import yaml

ROOT = Path(__file__).parent.parent
MANIFEST = ROOT / "prod" / "prod.env.manifest.yaml"
PROD_ENV = ROOT / "prod" / "prod.env"
BASE_ENV = ROOT / "src" / ".env"


def load_env(path: Path) -> dict:
    result = {}
    if not path.exists():
        return result
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        key, _, value = line.partition("=")
        result[key.strip()] = value
    return result


def ask(key, description, hint, required, default, current, base):
    # Already set in prod.env — keep it
    if key in current:
        print(f"  ✓ {key} (already set)")
        return current[key]

    lines = [f"  {key} — {description}"]
    if hint:
        lines.append(f"     hint: {hint}")
    if not required:
        lines.append("     (optional — Enter to skip)")

    print("\n".join(lines))

    # Effective default: base .env overrides manifest default
    effective = base.get(key, default)
    placeholder = f"[{effective}] " if effective != "" else ""
    value = input(f"  > {placeholder}").strip()

    if value:
        return value
    if not required:
        return None
    if effective != "":
        return effective
    print("  ⚠  Left empty — fill in prod/prod.env manually if needed.")
    return ""


def main():
    if not MANIFEST.exists():
        print(f"ERROR: Manifest not found: {MANIFEST}")
        sys.exit(1)

    with open(MANIFEST, encoding="utf-8") as f:
        manifest = yaml.safe_load(f)

    current = load_env(PROD_ENV)
    base = load_env(BASE_ENV)

    print("=" * 44)
    print("  Production environment setup")
    print(f"  → {PROD_ENV.relative_to(ROOT)}")
    print("=" * 44)
    print("Press Enter to keep the default/current value.\n")

    results = {}  # section_name → list of (key, value)

    for section in manifest.get("sections", []):
        print(f"--- {section['name']} ---")
        section_results = []
        for var in section.get("vars", []):
            key = var["key"]
            description = var.get("description", "")
            hint = var.get("hint", "")
            required = var.get("required", True)
            default = str(var.get("default", ""))

            value = ask(key, description, hint, required, default, current, base)
            if value is not None:
                section_results.append((key, value))

        results[section["name"]] = section_results

    # Write prod.env
    lines = [
        "# Production overrides — generated by make setup-prod",
        f"# {__import__('datetime').datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
    ]
    for section in manifest.get("sections", []):
        name = section["name"]
        section_lines = results.get(name, [])
        if not section_lines:
            continue
        lines.append(f"\n# {name}")
        for key, value in section_lines:
            lines.append(f"{key}={value}")

    PROD_ENV.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print("\n" + "=" * 44)
    print(f"  Saved to {PROD_ENV.relative_to(ROOT)}")
    print("=" * 44)


if __name__ == "__main__":
    main()
