"""
Project Settings
"""

from django_app.settings import BASE_DIR, env

DEFAULT_ORGANIZATION_NAME = env.str("DEFAULT_ORGANIZATION_NAME", "Default Organization")

FRONTEND_BASE_URL = env.str("FRONTEND_BASE_URL", "http://localhost:4200").rstrip("/")
FRONTEND_PASSWORD_RESET_PATH = env.str(
    "FRONTEND_PASSWORD_RESET_PATH", "/reset-password"
)

PASSWORD_RESET_TOKEN_TTL = env.int("PASSWORD_RESET_TOKEN_TTL", 900)  # 15m

TELEGRAM_TRIGGER_FIELDS_PATH = BASE_DIR / "tables/utils/data/telegram_fields.json"

SSE_TICKET_TTL_SECONDS = 30
PASSWORD_CHANGE_TICKET_TTL_SECONDS = env.int(
    "PASSWORD_CHANGE_TICKET_TTL_SECONDS", 300
)  # 5m

AVATAR_MAX_BYTES = env.int("AVATAR_MAX_BYTES", 5 * 1024 * 1024)  # 5MB
AVATAR_ALLOWED_FORMATS = env.list("AVATAR_ALLOWED_FORMATS", default=["JPEG", "PNG"])
MAX_TOTAL_FILE_SIZE = 10 * 1024 * 1024  # 10MB


REDIS_TUNNEL_CONFIG_CHANNEL = env.str(
    "REDIS_TUNNEL_CONFIG_CHANNEL", "REDIS_TUNNEL_CONFIG_CHANNEL"
)
TUNNEL_URLS_HASH_KEY = env.str("TUNNEL_URLS_HASH_KEY", "tunnel_urls")

KNOWLEDGE_DOCUMENT_CHUNK_CHANNEL = env.str(
    "KNOWLEDGE_DOCUMENT_CHUNK_CHANNEL", "knowledge:chunk"
)
KNOWLEDGE_DOCUMENT_CHUNK_RESPONSE = env.str(
    "KNOWLEDGE_DOCUMENT_CHUNK_RESPONSE", "knowledge:chunk:response"
)
KNOWLEDGE_INDEXING_CHANNEL = env.str("KNOWLEDGE_INDEXING_CHANNEL", "knowledge:indexing")

STOP_SESSION_CHANNEL = env.str("STOP_SESSION_CHANNEL", "sessions:stop")

WEBHOOK_USE_TUNNEL = env.bool("WEBHOOK_USE_TUNNEL", False)
WEBHOOK_TUNNEL = env("WEBHOOK_TUNNEL", default=None)
if not WEBHOOK_USE_TUNNEL:
    WEBHOOK_TUNNEL = None

REQUEST_WEBHOOK_UPDATE_CHANNEL = env.str(
    "REQUEST_WEBHOOK_UPDATE_CHANNEL", "REQUEST_WEBHOOK_UPDATE_CHANNEL"
)
SESSION_STATUS_CHANNEL = env.str("SESSION_STATUS_CHANNEL", "sessions:session_status")
CODE_RESULT_CHANNEL = env.str("CODE_RESULT_CHANNEL", "code_results")
GRAPH_MESSAGES_CHANNEL = env.str("GRAPH_MESSAGES_CHANNEL", "graph:messages")
GRAPH_MESSAGE_UPDATE_CHANNEL = env.str(
    "GRAPH_MESSAGE_UPDATE_CHANNEL", "graph:message:update"
)
WEBHOOK_MESSAGE_CHANNEL = env.str("WEBHOOK_MESSAGE_CHANNEL", "webhooks")
STORAGE_MUTATION_CHANNEL = env.str("STORAGE_MUTATION_CHANNEL", "storage_mutations")
TELEGRAM_TRIGGER_PREFIX = "telegram-trigger/"

WEBHOOK_HOST_NAME = env.str("WEBHOOK_HOST_NAME", "localhost")
WEBHOOK_PORT = env.int("WEBHOOK_PORT", 8009)
