FROM python:3.12.10

WORKDIR /home/user/root/app

COPY ./sandbox .
COPY shared/ ../shared/

RUN pip install --upgrade --no-cache-dir pip setuptools wheel

RUN pip install poetry

COPY ./sandbox/pyproject.toml .
COPY ./sandbox/poetry.lock .

RUN poetry config virtualenvs.create false 
RUN poetry install --no-root
RUN rm -rf /root/.cache



CMD python main.py
