# docker-compose.dev.yaml

services:
  django_app:
    command: sh -lc "
      python manage.py check_db_init &&
      python manage.py migrate &&
      python manage.py fix_sequences &&
      python manage.py upload_models &&
      python manage.py collectstatic --noinput &&
      python manage.py listen_redis &
      python manage.py cache_redis &
      uvicorn django_app.asgi:application --host 0.0.0.0 --port ${DJANGO_PORT:-8000} --reload --reload-dir /app/src/django_app"
    ports:
      - "${DJANGO_PORT:-8000}:${DJANGO_PORT:-8000}"
    environment:
      GUNICORN_RELOAD: 1
      WATCHFILES_FORCE_POLLING: "true"
    volumes:
      - ./django_app:/app/src/django_app:cached
      - ./shared:/app/src/shared:cached

  crewdb:
    ports:
      - "${DB_PORT:-5432}:${DB_PORT:-5432}"

  redis:
    ports:
      - "${REDIS_PORT:-6379}:${REDIS_PORT:-6379}"

  realtime:
    ports:
      - "${REALTIME_PORT:-8050}:${REALTIME_PORT:-8050}"
    environment:
      REALTIME_RELOAD: "True"
      WATCHFILES_FORCE_POLLING: "true"
    volumes:
      - ./realtime:/app/src/realtime

  manager:
    command: uvicorn app:app --host 0.0.0.0 --port ${MANAGER_PORT:-8001} --workers 1 --reload
    ports:
      - "${MANAGER_PORT:-8001}:${MANAGER_PORT:-8001}"
    env_file:
      - .env
      - ../dev/dev.env
    environment:
      WATCHFILES_FORCE_POLLING: "true"
    volumes:
      - ./manager:/app/src/manager
      - ./tool:/app/src/manager/tool

  crew:
    command: >
      sh -lc "cd /app/src/crew &&
      poetry run watchfiles
      --filter python
      --ignore-paths /app/src/crew/.venv
      'poetry run python3 /app/src/crew/main.py'
      /app/src/crew/"
    environment:
      WATCHFILES_FORCE_POLLING: "true"
    volumes:
      - ./crew/callbacks:/app/src/crew/callbacks:cached
      - ./crew/config:/app/src/crew/config:cached
      - ./crew/models:/app/src/crew/models:cached
      - ./crew/services:/app/src/crew/services:cached
      - ./crew/utils:/app/src/crew/utils:cached
      - ./crew/main.py:/app/src/crew/main.py:cached

  frontend:
    ports:
      - "${FRONTEND_PORT:-4201}:80"
    env_file:
      - ./.env
      - ../dev/dev.env
    environment:
      API_URL: "http://127.0.0.1:${DJANGO_PORT:-8000}/api/"
      REALTIME_API_URL: "http://127.0.0.1:${REALTIME_PORT:-8050}/"

  webhook:
    command: >
      sh -c "watchfiles --filter python 'python run.py' /app/src/webhook"
    ports:
      - "${WEBHOOK_PORT:-8051}:${WEBHOOK_PORT:-8051}"
    env_file:
      - ./.env
      - ../dev/dev.env
    environment:
      WATCHFILES_FORCE_POLLING: "true"
    volumes:
      - ./webhook/app:/app/src/webhook/app
      - ./webhook/run.py:/app/src/webhook/run.py

  knowledge:
    command: sh -c "watchfiles --filter python 'python main.py' ."
    environment:
      WATCHFILES_FORCE_POLLING: "true"
    volumes:
      - ./knowledge:/app/src/knowledge

  sandbox:
    command: sh -c "watchfiles --filter python --ignore-paths ./executions,./savefiles,./venvs 'python main.py' ."
    environment:
      WATCHFILES_FORCE_POLLING: "true"
    volumes:
      - ./sandbox:/app/src/sandbox
      - ./shared:/app/src/shared

  epicstaff-nginx:
    profiles:
      - prod