# docker-compose.yaml

include:
  - docker-compose.base.yaml

services:
  epicstaff-nginx:
    image: nginx
    container_name: epicstaff-nginx
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - SSL_ENABLE=${SSL_ENABLE}
    volumes:
      - ./nginx/templates/default.conf.template:/etc/nginx/templates/default.conf.template
      - ./nginx/certs:/etc/nginx/certs:ro
      - media_data:/usr/share/nginx/html/media:ro
    networks:
      - backend-network
      - frontend-network
    depends_on:
      django_app:
        condition: service_healthy
      frontend:
        condition: service_started
      realtime: 
        condition: service_started
    restart: always

  django_app:
    command: ./entrypoint.sh
    environment:
      LOAD_DEBUG_ENV: ${LOAD_DEBUG_ENV}

  manager:
    env_file:
      - .env

  webhook:
    ports:
      - "${WEBHOOK_PORT:-8051}:${WEBHOOK_PORT:-8051}"