FROM python:3.12.10

WORKDIR /app/src/

COPY ./shared ./shared

WORKDIR /app/src/knowledge

RUN pip install --upgrade --no-cache-dir pip setuptools wheel

RUN pip install poetry

COPY ./knowledge/pyproject.toml .
COPY ./knowledge/poetry.lock .

RUN poetry config virtualenvs.create false
RUN poetry install --no-root
RUN rm -rf /root/.cache

COPY ./knowledge .

CMD python main.py
