name: EpicStaff Pipeline

on:
  push:
    branches: [ main, Dev, feature-github-actions ]
  workflow_dispatch:
    inputs:
      installer_job:
        description: 'Installer job mode'
        default: 'skip'
        type: choice
        options: [ auto, force, skip ]

# env:
#   INSTALLER_JOB: ${{ github.event.inputs.installer_job || 'auto' }}
#   RELEASE_JOB: ${{ github.event.inputs.release || 'auto' }}
  

jobs:
  # Call the installer workflow
  build-installers:
    uses: ./.github/workflows/installer.yml
    with:
      installer_job: ${{ github.event.inputs.installer_job || 'auto' }}
    secrets: inherit

  # cleanup:
  #   if: always()
  #   needs: [build-installers, create-release]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Cleanup artifacts
  #       run: echo "Cleanup completed"